export interface ExamQuestion {
  id: number;
  question: string;
  choices: string[];
  correct: number;
  explanation: string;
}

export interface ExamSection {
  id: string;
  title: string;
  shortTitle: string;
  questionCount: number;
  totalScore: number;
  passingPercent: number;
  timeRecommended: number;
  questions: ExamQuestion[];
}

export interface MockExam {
  id: string;
  title: string;
  totalTime: number;
  xpReward: number;
  rankReward: string;
  sections: ExamSection[];
}

const section1: ExamSection = {
  id: "s1",
  title: "วิชาความรู้ความสามารถทั่วไป (คณิตศาสตร์ & ภาษาไทย)",
  shortTitle: "วิชาที่ 1",
  questionCount: 50,
  totalScore: 100,
  passingPercent: 60,
  timeRecommended: 90,
  questions: [
    // ── อนุกรม ──────────────────────────────────────────────
    {
      id: 1,
      question: "อนุกรม 3, 8, 15, 24, 35, ? มีค่าเท่าใด",
      choices: ["46", "47", "48", "49"],
      correct: 2,
      explanation: "ผลต่างคือ 5,7,9,11,13 → 35+13 = 48",
    },
    {
      id: 2,
      question: "อนุกรม 2, 3, 5, 8, 13, 21, ? มีค่าเท่าใด",
      choices: ["30", "32", "34", "35"],
      correct: 2,
      explanation: "Fibonacci: แต่ละตัวเท่ากับผลรวมสองตัวก่อนหน้า 13+21 = 34",
    },
    {
      id: 3,
      question: "อนุกรม 128, 64, 32, 16, 8, ? มีค่าเท่าใด",
      choices: ["2", "4", "6", "8"],
      correct: 1,
      explanation: "หารด้วย 2 ทุกครั้ง: 8÷2 = 4",
    },
    {
      id: 4,
      question: "อนุกรม 1, 4, 9, 16, 25, 36, ? มีค่าเท่าใด",
      choices: ["42", "47", "49", "52"],
      correct: 2,
      explanation: "กำลังสอง: 7² = 49",
    },
    {
      id: 5,
      question: "อนุกรม 5, 11, 23, 47, 95, ? มีค่าเท่าใด",
      choices: ["175", "185", "191", "200"],
      correct: 2,
      explanation: "×2+1: 95×2+1 = 191",
    },
    // ── เงื่อนไขสัญลักษณ์ ────────────────────────────────────
    {
      id: 6,
      question: "กำหนดให้ A★B = A×B − A − B\nคำนวณ 5★4 ได้เท่าใด",
      choices: ["9", "10", "11", "12"],
      correct: 2,
      explanation: "5×4 − 5 − 4 = 20 − 9 = 11",
    },
    {
      id: 7,
      question: "กำหนดให้ A⊕B = 2A + B − 3\nคำนวณ 3⊕5 ได้เท่าใด",
      choices: ["7", "8", "9", "10"],
      correct: 1,
      explanation: "2(3) + 5 − 3 = 6 + 5 − 3 = 8",
    },
    {
      id: 8,
      question: "กำหนดให้ A◆B = (A + B)² − AB\nคำนวณ 2◆3 ได้เท่าใด",
      choices: ["19", "22", "25", "29"],
      correct: 1,
      explanation: "(2+3)² − 2×3 = 25 − 6 = 19... wait: (5)²=25, 25−6=19",
    },
    {
      id: 9,
      question: "กำหนดให้ A▲B = A² − B²\nถ้า X▲3 = 16 แล้ว X มีค่าเท่าใด",
      choices: ["4", "5", "6", "7"],
      correct: 1,
      explanation: "X² − 9 = 16 → X² = 25 → X = 5",
    },
    {
      id: 10,
      question: "กำหนดให้ f(x) = 3x − 7\nถ้า f(a) = 14 แล้ว a มีค่าเท่าใด",
      choices: ["6", "7", "8", "9"],
      correct: 1,
      explanation: "3a − 7 = 14 → 3a = 21 → a = 7",
    },
    // ── ร้อยละ ──────────────────────────────────────────────
    {
      id: 11,
      question: "สินค้าราคา 3,200 บาท ลดราคา 25% ราคาหลังลดเป็นเท่าใด",
      choices: ["2,200 บาท", "2,400 บาท", "2,600 บาท", "2,800 บาท"],
      correct: 1,
      explanation: "3,200 × 0.75 = 2,400 บาท",
    },
    {
      id: 12,
      question: "นักเรียน 240 คน สอบผ่าน 75% สอบไม่ผ่านกี่คน",
      choices: ["50 คน", "60 คน", "70 คน", "80 คน"],
      correct: 1,
      explanation: "ไม่ผ่าน 25% → 240 × 0.25 = 60 คน",
    },
    {
      id: 13,
      question: "เงินต้น 50,000 บาท ดอกเบี้ยทบต้น 10% ต่อปี ครบ 2 ปี มีเงินรวมเท่าใด",
      choices: ["60,000 บาท", "60,500 บาท", "61,000 บาท", "61,500 บาท"],
      correct: 1,
      explanation: "50,000 × 1.1² = 50,000 × 1.21 = 60,500 บาท",
    },
    {
      id: 14,
      question: "สินค้าราคาทุน 800 บาท ขายได้กำไร 35% ราคาขายเท่าใด",
      choices: ["1,000 บาท", "1,020 บาท", "1,080 บาท", "1,100 บาท"],
      correct: 2,
      explanation: "800 × 1.35 = 1,080 บาท",
    },
    {
      id: 15,
      question: "เปอร์เซ็นต์การเปลี่ยนแปลงจาก 400 เป็น 520 คือข้อใด",
      choices: ["20%", "25%", "30%", "35%"],
      correct: 2,
      explanation: "(520−400)/400 × 100 = 120/400 × 100 = 30%",
    },
    // ── สัดส่วน/อัตรา ─────────────────────────────────────
    {
      id: 16,
      question: "ถ้า A:B = 3:5 และ B:C = 4:7 แล้ว A:C เท่าใด",
      choices: ["3:7", "12:35", "15:28", "21:20"],
      correct: 1,
      explanation: "A:B:C = 3×4 : 5×4 : 5×7 = 12:20:35 → A:C = 12:35",
    },
    {
      id: 17,
      question: "แบ่งเงิน 9,600 บาท ในสัดส่วน 2:3:7 ส่วนมากสุดได้เท่าใด",
      choices: ["1,600 บาท", "2,400 บาท", "5,600 บาท", "6,720 บาท"],
      correct: 2,
      explanation: "รวม 12 ส่วน, ส่วนมากสุด 7 ส่วน: 9,600/12×7 = 5,600 บาท",
    },
    {
      id: 18,
      question: "A ทำงานเสร็จใน 12 วัน B ทำเสร็จใน 8 วัน ทำด้วยกันเสร็จในกี่วัน",
      choices: ["4 วัน", "4.8 วัน", "5 วัน", "5.5 วัน"],
      correct: 1,
      explanation: "1/12 + 1/8 = 2/24 + 3/24 = 5/24 ต่อวัน → 24/5 = 4.8 วัน",
    },
    {
      id: 19,
      question: "รถวิ่งจากเมือง A ถึง B ระยะทาง 360 กม. ด้วยความเร็ว 90 กม./ชม. ใช้เวลากี่ชั่วโมง",
      choices: ["3 ชั่วโมง", "3.5 ชั่วโมง", "4 ชั่วโมง", "4.5 ชั่วโมง"],
      correct: 2,
      explanation: "360 ÷ 90 = 4 ชั่วโมง",
    },
    {
      id: 20,
      question: "ถ้าคนงาน 6 คน ทำงานเสร็จใน 10 วัน คนงาน 4 คน ทำงานเดียวกันเสร็จในกี่วัน",
      choices: ["12 วัน", "15 วัน", "18 วัน", "20 วัน"],
      correct: 1,
      explanation: "งาน = 6×10 = 60 คน-วัน → 60÷4 = 15 วัน",
    },
    // ── ตรรกะ/เงื่อนไขภาษา ──────────────────────────────────
    {
      id: 21,
      question: "ถ้า \"ผู้ที่ขยันทุกคนประสบความสำเร็จ\" และ \"นายดำขยัน\"\nข้อสรุปใดถูกต้อง",
      choices: [
        "นายดำอาจประสบความสำเร็จ",
        "นายดำประสบความสำเร็จ",
        "นายดำไม่ประสบความสำเร็จ",
        "สรุปไม่ได้",
      ],
      correct: 1,
      explanation: "Syllogism: ขยัน→สำเร็จ, ดำขยัน ∴ ดำสำเร็จ",
    },
    {
      id: 22,
      question: "ถ้า \"ฝนตกแล้วถนนเปียก\" และ \"ถนนไม่เปียก\"\nข้อสรุปใดถูกต้อง",
      choices: [
        "ฝนอาจตกหรือไม่ตกก็ได้",
        "ฝนตก",
        "ฝนไม่ตก",
        "สรุปไม่ได้",
      ],
      correct: 2,
      explanation: "Modus Tollens: P→Q, ¬Q ∴ ¬P",
    },
    {
      id: 23,
      question: "สัตว์ทุกตัวต้องตาย มังกรเป็นสัตว์ในนิยาย ข้อสรุปใดถูกต้อง",
      choices: [
        "มังกรต้องตาย",
        "มังกรไม่ต้องตาย",
        "สรุปไม่ได้เพราะมังกรไม่มีจริง",
        "มังกรอาจต้องตายหรือไม่ก็ได้",
      ],
      correct: 2,
      explanation: "มังกรเป็น 'สัตว์ในนิยาย' ไม่ใช่ 'สัตว์' ตามนิยามที่ใช้ในสมมติฐาน จึงสรุปไม่ได้แน่ชัด",
    },
    {
      id: 24,
      question: "ถ้า A มาก่อน B, C มาหลัง D, B มาก่อน C\nลำดับที่ถูกต้องคือข้อใด",
      choices: ["A B C D", "A B D C", "D A B C", "A D B C"],
      correct: 1,
      explanation: "A→B→C และ D→C → ลำดับที่เป็นไปได้: A B D C",
    },
    {
      id: 25,
      question: "นักเรียน 5 คน: A สูงกว่า B, C สูงกว่า A, D เตี้ยกว่า B, E สูงกว่า C\nใครสูงที่สุด",
      choices: ["A", "C", "D", "E"],
      correct: 3,
      explanation: "E>C>A>B>D → E สูงที่สุด",
    },
    // ── ภาษาไทย: คำศัพท์ ────────────────────────────────────
    {
      id: 26,
      question: "คำใดมีความหมายตรงกับ \"ประหยัด\"",
      choices: ["ฟุ่มเฟือย", "มัธยัสถ์", "ใจกว้าง", "สุรุ่ยสุร่าย"],
      correct: 1,
      explanation: "มัธยัสถ์ แปลว่า ประหยัด รู้จักเก็บออม",
    },
    {
      id: 27,
      question: "ข้อใดเป็นคำพ้องความหมายกับ \"ทนทาน\"",
      choices: ["บอบบาง", "แข็งแกร่ง", "อ่อนแอ", "เปราะบาง"],
      correct: 1,
      explanation: "แข็งแกร่ง หมายถึง ทนทาน คงทน ไม่แตกหักง่าย",
    },
    {
      id: 28,
      question: "สำนวน \"น้ำขึ้นให้รีบตัก\" หมายความว่าอย่างไร",
      choices: [
        "ควรตักน้ำในช่วงน้ำขึ้นเท่านั้น",
        "ใช้โอกาสที่ดีให้เป็นประโยชน์ทันที",
        "รีบทำงานให้เสร็จก่อนเวลา",
        "อย่ารอช้าในการทำงาน",
      ],
      correct: 1,
      explanation: "หมายถึงเมื่อมีโอกาสหรือวาสนาก็ควรรีบใช้ประโยชน์ก่อนจะหมดไป",
    },
    {
      id: 29,
      question: "ข้อใดใช้ภาษาได้ถูกต้องตามหลักภาษาไทย",
      choices: [
        "เขาไปซื้อของที่ตลาดสดแล้วก็กลับบ้านมา",
        "เขาได้ไปซื้อของที่ตลาดสดแล้วก็ได้กลับบ้านมา",
        "เขาไปซื้อของที่ตลาดสดและกลับบ้าน",
        "เขาได้ไปซื้อของที่ตลาดสดและกลับบ้านมาด้วย",
      ],
      correct: 2,
      explanation: "ข้อ ค. ใช้ภาษากระชับ ไม่ซ้ำซาก ไม่ใช้ 'ได้' เกินความจำเป็น",
    },
    {
      id: 30,
      question: "คำใดสะกดถูกต้องทุกคำ",
      choices: [
        "ปัจจุบัน, สัญลักษณ์, ประสงค์",
        "ปัจจุบัณ, สัญลักษณ์, ประสงค์",
        "ปัจจุบัน, สัญลักษณ, ประสงค์",
        "ปัจจุบัน, สัญลักษณ์, ประสงส์",
      ],
      correct: 0,
      explanation: "ปัจจุบัน, สัญลักษณ์, ประสงค์ ล้วนสะกดถูกต้องทั้ง 3 คำ",
    },
    {
      id: 31,
      question: "ข้อใดเป็นประโยคที่มีกริยาครบถ้วน",
      choices: [
        "เด็กที่ขยันทุกคน",
        "ครูสอนนักเรียน",
        "หนังสือบนโต๊ะ",
        "ดอกไม้ริมถนนสวย",
      ],
      correct: 1,
      explanation: "ครู (ประธาน) สอน (กริยา) นักเรียน (กรรม) ครบองค์ประกอบ",
    },
    {
      id: 32,
      question: "คำว่า \"วิทยา\" มีความหมายว่าอะไร",
      choices: ["ความรู้", "ความเก่ง", "ความฉลาด", "ความสำเร็จ"],
      correct: 0,
      explanation: "วิทยา (สันสกฤต) แปลว่า ความรู้ วิชาความรู้",
    },
    {
      id: 33,
      question: "ข้อใดเป็นคำยืมจากภาษาอังกฤษ",
      choices: ["โทรศัพท์", "คอมพิวเตอร์", "อินเทอร์เน็ต", "ข้อ ข. และ ค."],
      correct: 3,
      explanation: "คอมพิวเตอร์ (computer) และอินเทอร์เน็ต (internet) ยืมมาจากอังกฤษโดยตรง",
    },
    {
      id: 34,
      question: "สุภาษิต \"รักยาวให้บั่น รักสั้นให้ต่อ\" หมายความว่าอย่างไร",
      choices: [
        "ถ้าอยากให้รักยั่งยืนต้องบั่นทอนกัน",
        "ถ้าต้องการให้ความสัมพันธ์ยืนยาว ต้องตัดสิ่งที่เสียหายออก",
        "รักสั้นดีกว่ารักยาว",
        "ตัดความรักออกจะทำให้ชีวิตดีขึ้น",
      ],
      correct: 1,
      explanation: "หมายถึงถ้าต้องการให้สิ่งดีคงอยู่นานต้องตัดส่วนที่เสียออก เช่น ตัดกิ่งแห้งเพื่อให้ต้นไม้แข็งแรง",
    },
    {
      id: 35,
      question: "\"เขาพูดเป็นน้ำไหลไฟดับ\" หมายความว่าอย่างไร",
      choices: [
        "พูดได้คล่องแคล่วไม่สะดุด",
        "พูดเรื่องน้ำและไฟ",
        "พูดไม่ออก",
        "พูดช้ามาก",
      ],
      correct: 0,
      explanation: "สำนวนหมายถึงพูดได้ราบรื่น คล่องแคล่ว ไม่ติดขัด",
    },
    // ── ภาษาไทย: อ่านจับใจความ ──────────────────────────────
    {
      id: 36,
      question: "\"การออกกำลังกายสม่ำเสมออย่างน้อยสัปดาห์ละ 3 วัน วันละ 30 นาที ช่วยลดความเสี่ยงโรคหัวใจได้ถึง 35% และยังช่วยควบคุมน้ำหนัก ลดความเครียด และเสริมสร้างภูมิคุ้มกัน\"\n\nข้อใดคือใจความสำคัญของข้อความนี้",
      choices: [
        "ควรออกกำลังกายวันละ 30 นาที",
        "การออกกำลังกายสม่ำเสมอมีประโยชน์ต่อสุขภาพหลายด้าน",
        "โรคหัวใจสามารถป้องกันได้ด้วยการออกกำลังกาย",
        "ความเครียดลดลงได้ถ้าออกกำลังกาย",
      ],
      correct: 1,
      explanation: "ใจความสำคัญครอบคลุมประโยชน์ทั้งหมด ไม่ใช่แค่ด้านใดด้านหนึ่ง",
    },
    {
      id: 37,
      question: "\"เศรษฐกิจพอเพียงไม่ได้หมายความว่าต้องพอใจกับสิ่งที่มี แต่หมายถึงการดำเนินชีวิตอย่างมีเหตุผล ไม่ฟุ่มเฟือย รู้จักประมาณตน และมีภูมิคุ้มกันที่ดี\"\n\nข้อใดสอดคล้องกับข้อความนี้มากที่สุด",
      choices: [
        "เศรษฐกิจพอเพียงคือการไม่ทำงานหาเงิน",
        "เศรษฐกิจพอเพียงสอนให้คนพอใจกับสิ่งที่มีอยู่แล้ว",
        "เศรษฐกิจพอเพียงเน้นการใช้เหตุผลและความพอประมาณ",
        "เศรษฐกิจพอเพียงใช้ได้เฉพาะเกษตรกร",
      ],
      correct: 2,
      explanation: "ข้อความระบุชัดว่าเน้นเหตุผล ประมาณตน ไม่ฟุ่มเฟือย",
    },
    {
      id: 38,
      question: "ข้อใดเป็นการเรียงลำดับข้อความที่ถูกต้อง\nก. จึงทำให้ร่างกายขาดน้ำได้ง่าย\nข. อากาศร้อนทำให้เหงื่อออกมาก\nค. ควรดื่มน้ำอย่างน้อยวันละ 8 แก้ว\nง. โดยเฉพาะในฤดูร้อน",
      choices: ["ข ก ง ค", "ข ง ก ค", "ง ข ก ค", "ค ข ง ก"],
      correct: 1,
      explanation: "ข(อากาศร้อน→เหงื่อ) ง(โดยเฉพาะฤดูร้อน) ก(จึงขาดน้ำ) ค(ควรดื่มน้ำ) เป็นเหตุเป็นผลกัน",
    },
    {
      id: 39,
      question: "คำว่า \"ดิจิทัล\" ในบริบท \"ยุคดิจิทัล\" หมายถึงอะไร",
      choices: [
        "ยุคที่ใช้เทคโนโลยีดิจิทัลเป็นหลักในการดำเนินชีวิต",
        "ยุคที่มีดิจิทัลทีวีเกิดขึ้น",
        "ยุคที่คนนิยมเล่นเกมดิจิทัล",
        "ยุคที่มีอินเทอร์เน็ตความเร็วสูง",
      ],
      correct: 0,
      explanation: "ยุคดิจิทัลหมายถึงยุคที่เทคโนโลยีสารสนเทศและการสื่อสารดิจิทัลเป็นส่วนสำคัญของชีวิตประจำวัน",
    },
    {
      id: 40,
      question: "ข้อใดไม่ใช่ลักษณะของการเขียนเรียงความที่ดี",
      choices: [
        "มีการเรียบเรียงความคิดอย่างเป็นระบบ",
        "ใช้ภาษาที่ถูกต้องตามหลักไวยากรณ์",
        "ใส่ข้อมูลให้มากที่สุดเท่าที่จะทำได้",
        "มีเนื้อหาที่สอดคล้องกับชื่อเรื่อง",
      ],
      correct: 2,
      explanation: "เรียงความที่ดีควรกระชับ ไม่ยืดเยื้อ มีเนื้อหาที่เกี่ยวข้องและจำเป็นเท่านั้น",
    },
    // ── คณิตศาสตร์เพิ่มเติม ─────────────────────────────────
    {
      id: 41,
      question: "ถ้าขายสินค้าในราคา 1,400 บาท ขาดทุน 12.5% ราคาทุนของสินค้าคือเท่าใด",
      choices: ["1,550 บาท", "1,575 บาท", "1,600 บาท", "1,650 บาท"],
      correct: 2,
      explanation: "ราคาขาย = ราคาทุน × (1−0.125) → ราคาทุน = 1,400/0.875 = 1,600 บาท",
    },
    {
      id: 42,
      question: "ถังน้ำจุน้ำได้ 500 ลิตร มีน้ำอยู่ 60% ต้องเติมน้ำอีกกี่ลิตรจึงจะเต็ม",
      choices: ["150 ลิตร", "175 ลิตร", "200 ลิตร", "250 ลิตร"],
      correct: 2,
      explanation: "มีน้ำ 500×0.6 = 300 ลิตร ต้องเติม 500−300 = 200 ลิตร",
    },
    {
      id: 43,
      question: "สี่เหลี่ยมผืนผ้ากว้าง 12 ซม. ยาว 18 ซม. พื้นที่เท่าใด",
      choices: ["196 ตร.ซม.", "206 ตร.ซม.", "216 ตร.ซม.", "226 ตร.ซม."],
      correct: 2,
      explanation: "พื้นที่ = 12 × 18 = 216 ตร.ซม.",
    },
    {
      id: 44,
      question: "วงกลมรัศมี 7 ซม. มีพื้นที่เท่าใด (π ≈ 22/7)",
      choices: ["144 ตร.ซม.", "154 ตร.ซม.", "164 ตร.ซม.", "174 ตร.ซม."],
      correct: 1,
      explanation: "พื้นที่ = π × r² = 22/7 × 49 = 154 ตร.ซม.",
    },
    {
      id: 45,
      question: "ค่าเฉลี่ยของ 15, 18, 21, 24, 27 คือเท่าใด",
      choices: ["19", "20", "21", "22"],
      correct: 2,
      explanation: "รวม = 105, ค่าเฉลี่ย = 105/5 = 21",
    },
    {
      id: 46,
      question: "ถ้า x + y = 10 และ x − y = 4 แล้ว xy มีค่าเท่าใด",
      choices: ["18", "20", "21", "24"],
      correct: 2,
      explanation: "x=7, y=3 → xy = 21",
    },
    {
      id: 47,
      question: "จำนวนเฉพาะระหว่าง 20 ถึง 40 มีกี่จำนวน",
      choices: ["3", "4", "5", "6"],
      correct: 1,
      explanation: "23, 29, 31, 37 = 4 จำนวน",
    },
    {
      id: 48,
      question: "ถ้าสินค้าชิ้นหนึ่งราคา 560 บาท หลังลด 20% แล้วลดอีก 10% ราคาสุดท้ายเท่าใด",
      choices: ["392 บาท", "396 บาท", "403 บาท", "412 บาท"],
      correct: 3,
      explanation: "560 × 0.8 = 448 → 448 × 0.9 = 403.20 ≈ 403 บาท... 560×0.8×0.9 = 560×0.72 = 403.2",
    },
    {
      id: 49,
      question: "ห้องสี่เหลี่ยมจัตุรัสมีพื้นที่ 196 ตร.ม. เส้นรอบวงของห้องนี้คือเท่าใด",
      choices: ["48 ม.", "52 ม.", "56 ม.", "64 ม."],
      correct: 2,
      explanation: "ด้าน = √196 = 14 ม. เส้นรอบวง = 4×14 = 56 ม.",
    },
    {
      id: 50,
      question: "สินค้า A และ B ราคารวม 1,200 บาท ถ้า A แพงกว่า B อยู่ 200 บาท ราคา A คือเท่าใด",
      choices: ["600 บาท", "650 บาท", "700 บาท", "750 บาท"],
      correct: 2,
      explanation: "A + B = 1200, A − B = 200 → A = 700, B = 500",
    },
  ],
};

const section2: ExamSection = {
  id: "s2",
  title: "วิชาภาษาอังกฤษ",
  shortTitle: "วิชาที่ 2",
  questionCount: 25,
  totalScore: 50,
  passingPercent: 50,
  timeRecommended: 50,
  questions: [
    // ── Vocabulary ──────────────────────────────────────────
    {
      id: 51,
      question: "Choose the word closest in meaning to \"DILIGENT\"",
      choices: ["Lazy", "Hardworking", "Careless", "Ignorant"],
      correct: 1,
      explanation: "DILIGENT means showing care and effort in work — hardworking.",
    },
    {
      id: 52,
      question: "Choose the word opposite in meaning to \"TRANSPARENT\"",
      choices: ["Clear", "Obvious", "Opaque", "Visible"],
      correct: 2,
      explanation: "TRANSPARENT means see-through; its opposite is OPAQUE (not clear).",
    },
    {
      id: 53,
      question: "The word \"OBSOLETE\" most nearly means:",
      choices: ["Modern", "No longer used", "Very popular", "Difficult"],
      correct: 1,
      explanation: "OBSOLETE means out of date, no longer in use.",
    },
    {
      id: 54,
      question: "Choose the word closest in meaning to \"INTEGRITY\"",
      choices: ["Dishonesty", "Moral uprightness", "Intelligence", "Popularity"],
      correct: 1,
      explanation: "INTEGRITY refers to honesty and strong moral principles.",
    },
    {
      id: 55,
      question: "\"AMBIGUOUS\" most nearly means:",
      choices: ["Clear and direct", "Having more than one meaning", "Very important", "Easy to understand"],
      correct: 1,
      explanation: "AMBIGUOUS means open to more than one interpretation.",
    },
    // ── Grammar ─────────────────────────────────────────────
    {
      id: 56,
      question: "Choose the correct sentence:",
      choices: [
        "She doesn't knows the answer.",
        "She don't know the answer.",
        "She doesn't know the answer.",
        "She not knows the answer.",
      ],
      correct: 2,
      explanation: "With third-person singular, use doesn't + base verb: doesn't know.",
    },
    {
      id: 57,
      question: "\"By the time we arrived, the meeting ______ already ______.\"",
      choices: ["had / started", "has / started", "was / started", "will / start"],
      correct: 0,
      explanation: "Past perfect: had + past participle for action completed before another past action.",
    },
    {
      id: 58,
      question: "Choose the correct passive form of: \"The manager signed the contract.\"",
      choices: [
        "The contract is signed by the manager.",
        "The contract was signed by the manager.",
        "The contract has signed by the manager.",
        "The contract signed by the manager.",
      ],
      correct: 1,
      explanation: "Past passive: was/were + past participle.",
    },
    {
      id: 59,
      question: "\"If I ______ you, I would accept the offer.\"",
      choices: ["am", "was", "were", "be"],
      correct: 2,
      explanation: "Subjunctive mood (hypothetical): If I were you...",
    },
    {
      id: 60,
      question: "\"He is the ______ student in the class.\"",
      choices: ["more intelligent", "most intelligent", "much intelligent", "intelligenter"],
      correct: 1,
      explanation: "Superlative form: the most + adjective (for long adjectives).",
    },
    {
      id: 61,
      question: "Choose the sentence with correct subject-verb agreement:",
      choices: [
        "The news are bad today.",
        "Mathematics are my favourite subject.",
        "Each of the students has submitted their assignment.",
        "A number of people is waiting outside.",
      ],
      correct: 2,
      explanation: "'Each' takes singular verb. 'The news' and 'Mathematics' are singular. 'A number of' is plural.",
    },
    // ── Conversation ─────────────────────────────────────────
    {
      id: 62,
      question: "A: \"Could you please send me the report by Friday?\"\nB: \"______\"\n\nWhich response is most appropriate?",
      choices: [
        "Yes, I could.",
        "Certainly, I'll make sure it's done by then.",
        "No, I can't do it.",
        "Maybe, I will try.",
      ],
      correct: 1,
      explanation: "A formal, polite and committed response is most appropriate in a professional context.",
    },
    {
      id: 63,
      question: "A: \"I'm afraid I can't attend the meeting tomorrow.\"\nB: \"______\"\n\nChoose the best response:",
      choices: [
        "That's fine, goodbye.",
        "No problem. Could you let us know your thoughts via email instead?",
        "Why not?",
        "You have to come.",
      ],
      correct: 1,
      explanation: "The best professional response acknowledges the absence and proposes an alternative.",
    },
    {
      id: 64,
      question: "\"______ you mind if I open the window?\"",
      choices: ["Do", "Would", "Should", "Shall"],
      correct: 1,
      explanation: "'Would you mind' is the polite form for asking permission.",
    },
    {
      id: 65,
      question: "To express strong disagreement politely, which phrase is most appropriate?",
      choices: [
        "That's completely wrong!",
        "I'm afraid I see it differently.",
        "No, you're mistaken.",
        "That can't be right.",
      ],
      correct: 1,
      explanation: "'I'm afraid I see it differently' softens disagreement with 'I'm afraid'.",
    },
    // ── Reading Comprehension ────────────────────────────────
    {
      id: 66,
      question: "Read the passage:\n\"Remote work has transformed how companies operate. Studies show that employees working from home report higher job satisfaction and productivity. However, challenges such as communication barriers and feelings of isolation remain significant concerns.\"\n\nWhat is the main idea of this passage?",
      choices: [
        "Remote work is better than office work.",
        "Remote work has both benefits and challenges.",
        "Communication is the biggest problem with remote work.",
        "Companies should stop using remote work.",
      ],
      correct: 1,
      explanation: "The passage presents both positive aspects (satisfaction, productivity) and negatives (barriers, isolation).",
    },
    {
      id: 67,
      question: "Using the passage from Q66, which word is closest in meaning to 'isolation'?",
      choices: ["Connection", "Separation", "Communication", "Satisfaction"],
      correct: 1,
      explanation: "Isolation means being separated from others — closest to 'separation'.",
    },
    {
      id: 68,
      question: "Read: \"Despite its small size, Singapore has one of the world's most competitive economies, ranking consistently in the top positions for ease of doing business, infrastructure quality, and innovation.\"\n\nWhat can be inferred from this passage?",
      choices: [
        "Large countries always have stronger economies.",
        "Economic success is not solely determined by a country's size.",
        "Singapore has poor infrastructure.",
        "Innovation is not important for economic growth.",
      ],
      correct: 1,
      explanation: "The contrast 'despite its small size' implies that size is not the determining factor.",
    },
    {
      id: 69,
      question: "Choose the sentence with the correct use of articles:",
      choices: [
        "She is an university student.",
        "He bought the umbrella from a shop near the station.",
        "I need a advice from you.",
        "The honesty is the best policy.",
      ],
      correct: 1,
      explanation: "'The umbrella' (specific), 'a shop' (non-specific) — both correctly used.",
    },
    {
      id: 70,
      question: "\"The project was ______ because of insufficient funding.\"",
      choices: ["called off", "called on", "called up", "called for"],
      correct: 0,
      explanation: "'Called off' means cancelled — the project was cancelled due to lack of funding.",
    },
    {
      id: 71,
      question: "Which sentence correctly uses a relative clause?",
      choices: [
        "The man which works here is my uncle.",
        "The woman who I met yesterday is a doctor.",
        "The book what I read was interesting.",
        "The car which it broke down has been repaired.",
      ],
      correct: 1,
      explanation: "'who' is correct for people; no extra pronoun needed after 'who'.",
    },
    {
      id: 72,
      question: "\"She ______ in this company since 2019.\"",
      choices: ["works", "worked", "has worked", "is working"],
      correct: 2,
      explanation: "Present perfect: has + past participle for action continuing from past to present.",
    },
    {
      id: 73,
      question: "Choose the word that correctly completes the sentence:\n\"The committee reached a ______ after hours of discussion.\"",
      choices: ["conclusion", "conclusions", "conclude", "concluded"],
      correct: 0,
      explanation: "'A conclusion' — singular noun after article 'a'.",
    },
    {
      id: 74,
      question: "\"He ______ the report before the deadline.\"",
      choices: [
        "had submitted",
        "has submitted",
        "submits",
        "is submitting",
      ],
      correct: 0,
      explanation: "Past perfect 'had submitted' is used for action completed before another past event (the deadline).",
    },
    {
      id: 75,
      question: "Choose the most formal way to begin a business email:",
      choices: [
        "Hey there,",
        "Dear Sir/Madam,",
        "Hi,",
        "What's up,",
      ],
      correct: 1,
      explanation: "'Dear Sir/Madam,' is the standard formal salutation for business correspondence.",
    },
  ],
};

const section3: ExamSection = {
  id: "s3",
  title: "วิชาความรู้และลักษณะการเป็นข้าราชการที่ดี",
  shortTitle: "วิชาที่ 3",
  questionCount: 25,
  totalScore: 50,
  passingPercent: 60,
  timeRecommended: 40,
  questions: [
    {
      id: 76,
      question: "รัฐธรรมนูญแห่งราชอาณาจักรไทย พ.ศ. 2560 กำหนดให้ประเทศไทยมีรูปแบบการปกครองแบบใด",
      choices: [
        "ประชาธิปไตยแบบรัฐสภา",
        "ประชาธิปไตยอันมีพระมหากษัตริย์ทรงเป็นประมุข",
        "สาธารณรัฐประชาธิปไตย",
        "ราชาธิปไตยภายใต้รัฐธรรมนูญ",
      ],
      correct: 1,
      explanation: "มาตรา 2 ระบุว่า ประเทศไทยมีการปกครองระบอบประชาธิปไตยอันมีพระมหากษัตริย์ทรงเป็นประมุข",
    },
    {
      id: 77,
      question: "ตามพระราชบัญญัติระเบียบข้าราชการพลเรือน พ.ศ. 2551 คณะกรรมการข้าราชการพลเรือน (ก.พ.) มีกี่คน",
      choices: ["ไม่เกิน 10 คน", "ไม่เกิน 12 คน", "ไม่เกิน 15 คน", "ไม่เกิน 20 คน"],
      correct: 1,
      explanation: "ก.พ. ประกอบด้วยประธาน และกรรมการอื่นอีกไม่เกิน 12 คน",
    },
    {
      id: 78,
      question: "ข้อใดไม่ใช่หลักการบริหารกิจการบ้านเมืองที่ดี (Good Governance) ตาม พ.ร.บ. ระเบียบบริหารราชการแผ่นดิน",
      choices: ["หลักนิติธรรม", "หลักคุณธรรม", "หลักการแข่งขัน", "หลักการมีส่วนร่วม"],
      correct: 2,
      explanation: "หลักธรรมาภิบาล 6 หลักคือ นิติธรรม คุณธรรม ความโปร่งใส การมีส่วนร่วม ความรับผิดชอบ ความคุ้มค่า ไม่มีหลักการแข่งขัน",
    },
    {
      id: 79,
      question: "ข้าราชการพลเรือนสามัญที่กระทำผิดวินัยอย่างไม่ร้ายแรง อาจได้รับโทษทางวินัยสูงสุดในระดับใด",
      choices: ["ภาคทัณฑ์", "ตัดเงินเดือน", "ลดเงินเดือน", "ปลดออก"],
      correct: 2,
      explanation: "โทษทางวินัยไม่ร้ายแรง ได้แก่ ภาคทัณฑ์ ตัดเงินเดือน และลดเงินเดือน โดยลดเงินเดือนเป็นโทษสูงสุดในกรณีไม่ร้ายแรง",
    },
    {
      id: 80,
      question: "ตามพระราชกฤษฎีกาว่าด้วยหลักเกณฑ์และวิธีการบริหารกิจการบ้านเมืองที่ดี ข้อใดไม่ใช่เป้าหมายของการบริหารกิจการบ้านเมืองที่ดี",
      choices: [
        "เกิดประโยชน์สุขของประชาชน",
        "เกิดผลสัมฤทธิ์ต่อภารกิจของรัฐ",
        "มีการขยายกำลังคนภาครัฐให้มากขึ้น",
        "ประชาชนได้รับการอำนวยความสะดวก",
      ],
      correct: 2,
      explanation: "เป้าหมายไม่ได้เน้นการขยายกำลังคน แต่เน้นประสิทธิภาพและประโยชน์ต่อประชาชน",
    },
    {
      id: 81,
      question: "ข้าราชการพลเรือนมีหน้าที่ตามกฎหมายต้องกระทำสิ่งใด",
      choices: [
        "เข้าร่วมชุมนุมทางการเมืองเพื่อแสดงจุดยืน",
        "ปฏิบัติหน้าที่ราชการด้วยความซื่อสัตย์ สุจริต",
        "รับของขวัญจากผู้มาติดต่อได้หากมีมูลค่าไม่สูง",
        "ใช้ทรัพย์สินของราชการเพื่อกิจการส่วนตัวได้บ้าง",
      ],
      correct: 1,
      explanation: "ข้าราชการต้องปฏิบัติหน้าที่ด้วยความซื่อสัตย์สุจริต ห้ามรับสินบน ห้ามใช้ทรัพย์สินราชการส่วนตัว",
    },
    {
      id: 82,
      question: "พระราชบัญญัติข้อมูลข่าวสารของราชการ พ.ศ. 2540 กำหนดให้ประชาชนมีสิทธิในข้อใด",
      choices: [
        "เข้าถึงข้อมูลราชการทุกประเภทได้โดยไม่มีข้อยกเว้น",
        "ขอดูข้อมูลราชการที่หน่วยงานต้องเปิดเผย",
        "คัดค้านการเก็บข้อมูลส่วนตัวของตนได้ทุกกรณี",
        "ได้รับข้อมูลลับของรัฐเมื่อร้องขอ",
      ],
      correct: 1,
      explanation: "กฎหมายให้สิทธิประชาชนขอดูข้อมูลที่หน่วยงานต้องเปิดเผย มีข้อยกเว้นสำหรับข้อมูลที่กระทบความมั่นคง",
    },
    {
      id: 83,
      question: "ตาม พ.ร.บ. วิธีปฏิบัติราชการทางปกครอง พ.ศ. 2539 หากคำสั่งทางปกครองไม่แจ้งสิทธิอุทธรณ์ ผู้รับคำสั่งมีเวลาอุทธรณ์นานเท่าใด",
      choices: ["30 วัน", "60 วัน", "90 วัน", "1 ปี"],
      correct: 3,
      explanation: "หากไม่แจ้งสิทธิอุทธรณ์ ระยะเวลาอุทธรณ์ขยายเป็น 1 ปีนับแต่วันที่รับทราบคำสั่ง",
    },
    {
      id: 84,
      question: "หน่วยงานของรัฐที่รับผิดชอบจัดสอบเพื่อวัดความรู้ความสามารถทั่วไปสำหรับข้าราชการพลเรือนสามัญคือหน่วยงานใด",
      choices: ["กรมบัญชีกลาง", "สำนักงาน ก.พ.", "สำนักนายกรัฐมนตรี", "กระทรวงการคลัง"],
      correct: 1,
      explanation: "สำนักงาน ก.พ. (สำนักงานคณะกรรมการข้าราชการพลเรือน) รับผิดชอบการสอบ ก.พ.",
    },
    {
      id: 85,
      question: "ข้อใดเป็นลักษณะต้องห้ามของผู้จะสมัครสอบเพื่อเข้ารับราชการ",
      choices: [
        "เป็นบุคคลที่มีหนี้สิน",
        "เป็นบุคคลล้มละลาย",
        "เคยเปลี่ยนชื่อ-นามสกุล",
        "มีคู่สมรสเป็นชาวต่างชาติ",
      ],
      correct: 1,
      explanation: "บุคคลล้มละลายเป็นลักษณะต้องห้ามตาม พ.ร.บ. ระเบียบข้าราชการพลเรือน มาตรา 36",
    },
    {
      id: 86,
      question: "ข้อใดคือความหมายของ \"ธรรมาภิบาล\" ในการบริหารราชการ",
      choices: [
        "การปกครองโดยธรรมชาติ",
        "การบริหารจัดการที่ดี มีความโปร่งใสและรับผิดชอบ",
        "การปกครองด้วยกฎหมายอย่างเดียว",
        "การบริหารโดยคณะกรรมการที่ดี",
      ],
      correct: 1,
      explanation: "ธรรมาภิบาล (Good Governance) หมายถึงการบริหารกิจการบ้านเมืองที่ดี โปร่งใส รับผิดชอบ มีส่วนร่วม",
    },
    {
      id: 87,
      question: "ข้าราชการที่รับสินบนจะมีความผิดตามกฎหมายใด",
      choices: [
        "ประมวลกฎหมายแพ่งและพาณิชย์",
        "ประมวลกฎหมายอาญา มาตรา 149",
        "พ.ร.บ. ระเบียบข้าราชการพลเรือนเท่านั้น",
        "พ.ร.บ. วิธีปฏิบัติราชการทางปกครอง",
      ],
      correct: 1,
      explanation: "ความผิดฐานรับสินบนบัญญัติไว้ในประมวลกฎหมายอาญา มาตรา 149 และมีโทษทางวินัยด้วย",
    },
    {
      id: 88,
      question: "\"จริยธรรมข้าราชการ\" ตามประมวลจริยธรรมข้าราชการพลเรือน ข้อใดถือว่าสำคัญที่สุด",
      choices: [
        "ความจงรักภักดีต่อผู้บังคับบัญชา",
        "การยึดถือประโยชน์ส่วนรวมเหนือประโยชน์ส่วนตน",
        "ความสัมพันธ์ที่ดีกับเพื่อนร่วมงาน",
        "การทำงานให้ครบเวลาราชการ",
      ],
      correct: 1,
      explanation: "ประมวลจริยธรรมกำหนดให้ข้าราชการยึดถือประโยชน์ส่วนรวมเหนือประโยชน์ส่วนตนเป็นหลักสำคัญ",
    },
    {
      id: 89,
      question: "หน่วยงานใดเป็นผู้รับผิดชอบในการป้องกันและปราบปรามการทุจริตของเจ้าหน้าที่รัฐ",
      choices: ["สำนักงาน ก.พ.", "สำนักงาน ป.ป.ช.", "กรมสอบสวนคดีพิเศษ (DSI)", "สำนักงานตำรวจแห่งชาติ"],
      correct: 1,
      explanation: "สำนักงาน ป.ป.ช. (คณะกรรมการป้องกันและปราบปรามการทุจริตแห่งชาติ) มีหน้าที่โดยตรง",
    },
    {
      id: 90,
      question: "ผู้ที่ถูกลงโทษ \"ไล่ออก\" จากราชการมีความแตกต่างจาก \"ปลดออก\" อย่างไร",
      choices: [
        "ไล่ออกไม่ได้รับบำเหน็จบำนาญ ปลดออกได้รับ",
        "ไม่มีความแตกต่าง",
        "ปลดออกรุนแรงกว่าไล่ออก",
        "ไล่ออกยังมีสิทธิ์สมัครงานราชการ ปลดออกไม่มี",
      ],
      correct: 0,
      explanation: "ผู้ถูกไล่ออกจะเสียสิทธิบำเหน็จบำนาญ แต่ผู้ถูกปลดออกยังคงได้รับสิทธิบำเหน็จบำนาญอยู่",
    },
    {
      id: 91,
      question: "ตามพระราชบัญญัติความรับผิดทางละเมิดของเจ้าหน้าที่ พ.ศ. 2539 หากเจ้าหน้าที่กระทำละเมิดโดยจงใจ ใครต้องรับผิดชดใช้ค่าเสียหายแก่ผู้เสียหาย",
      choices: [
        "หน่วยงานของรัฐเท่านั้น",
        "เจ้าหน้าที่โดยตรง",
        "หน่วยงานของรัฐ แต่มีสิทธิ์ไล่เบี้ยเจ้าหน้าที่",
        "เจ้าหน้าที่และหน่วยงานร่วมกัน",
      ],
      correct: 2,
      explanation: "หน่วยงานรัฐชดใช้แก่ผู้เสียหายก่อน แล้วจึงไล่เบี้ยเจ้าหน้าที่ที่กระทำโดยจงใจหรือประมาทเลินเล่ออย่างร้ายแรง",
    },
    {
      id: 92,
      question: "ข้อใดคือสิทธิขั้นพื้นฐานของประชาชนที่รัฐธรรมนูญ พ.ศ. 2560 รับรองไว้",
      choices: [
        "สิทธิในการได้รับเงินเดือนจากรัฐ",
        "สิทธิในการเข้าถึงบริการสาธารณสุขขั้นพื้นฐาน",
        "สิทธิในการไม่เสียภาษี",
        "สิทธิในการปฏิเสธนโยบายรัฐ",
      ],
      correct: 1,
      explanation: "รัฐธรรมนูญรับรองสิทธิในการเข้าถึงบริการสาธารณสุขขั้นพื้นฐาน รวมถึงการศึกษาและความปลอดภัย",
    },
    {
      id: 93,
      question: "หลักการใดที่สำคัญที่สุดในการปฏิบัติงานราชการตามแนวทาง \"ราชการ 4.0\"",
      choices: [
        "เน้นกระดาษให้น้อยที่สุด",
        "เปิดเผย เชื่อมโยง และยึดประชาชนเป็นศูนย์กลาง",
        "ลดจำนวนข้าราชการ",
        "เพิ่มงบประมาณให้ทุกหน่วยงาน",
      ],
      correct: 1,
      explanation: "ราชการ 4.0 เน้น Open (เปิดเผย) Connected (เชื่อมโยง) Citizen-Centric (ยึดประชาชนเป็นศูนย์กลาง)",
    },
    {
      id: 94,
      question: "ข้าราชการพลเรือนสามัญบรรจุใหม่ จะได้รับการบรรจุในตำแหน่งระดับใด",
      choices: ["ระดับปฏิบัติการ", "ระดับชำนาญการ", "ระดับชำนาญการพิเศษ", "ระดับอาวุโส"],
      correct: 0,
      explanation: "ผู้ที่สอบบรรจุใหม่จะได้รับการบรรจุในระดับปฏิบัติการ (ระดับเริ่มต้น)",
    },
    {
      id: 95,
      question: "การ \"ล็อบบี้\" เพื่อให้ได้รับผลประโยชน์จากเจ้าหน้าที่รัฐเกี่ยวข้องกับข้อใด",
      choices: [
        "การใช้สิทธิตามรัฐธรรมนูญ",
        "การทุจริตและประพฤติมิชอบในวงราชการ",
        "การมีส่วนร่วมของประชาชน",
        "การยื่นคำร้องตามกฎหมาย",
      ],
      correct: 1,
      explanation: "การล็อบบี้เพื่อประโยชน์โดยมิชอบถือเป็นการทุจริตที่ขัดต่อหลักธรรมาภิบาล",
    },
    {
      id: 96,
      question: "ตามพระราชบัญญัติระเบียบข้าราชการพลเรือน ข้อใดไม่ใช่วิธีการได้มาซึ่งตำแหน่งข้าราชการพลเรือน",
      choices: ["การสอบแข่งขัน", "การคัดเลือก", "การซื้อตำแหน่ง", "การโอนย้าย"],
      correct: 2,
      explanation: "การซื้อตำแหน่งเป็นความผิดทางกฎหมาย ตำแหน่งราชการได้มาโดยการสอบ คัดเลือก หรือโอนย้ายเท่านั้น",
    },
    {
      id: 97,
      question: "ข้อใดคือความหมายของ \"ผลประโยชน์ทับซ้อน\" (Conflict of Interest)",
      choices: [
        "การที่เจ้าหน้าที่มีผลประโยชน์ส่วนตัวซึ่งอาจกระทบต่อการตัดสินใจในหน้าที่",
        "การแข่งขันระหว่างหน่วยงานของรัฐ",
        "ความขัดแย้งระหว่างผู้บังคับบัญชากับลูกน้อง",
        "ผลประโยชน์ที่ทับซ้อนกันระหว่างประชาชนสองกลุ่ม",
      ],
      correct: 0,
      explanation: "ผลประโยชน์ทับซ้อนเกิดเมื่อเจ้าหน้าที่มีส่วนได้ส่วนเสียส่วนตัวในเรื่องที่ตนต้องตัดสินใจในหน้าที่",
    },
    {
      id: 98,
      question: "หลัก \"Accountability\" ในการบริหารราชการหมายถึงข้อใด",
      choices: [
        "การทำบัญชีให้ถูกต้อง",
        "ความรับผิดชอบต่อผลการปฏิบัติงานที่ตรวจสอบได้",
        "การรับผิดชอบหนี้สินของหน่วยงาน",
        "การจัดทำรายงานประจำปี",
      ],
      correct: 1,
      explanation: "Accountability คือความรับผิดชอบในผลการดำเนินงานและความสามารถในการถูกตรวจสอบได้",
    },
    {
      id: 99,
      question: "ตามแผนยุทธศาสตร์ชาติ 20 ปี (พ.ศ. 2561-2580) เป้าหมายหลักของประเทศไทยคือข้อใด",
      choices: [
        "เป็นประเทศมหาอำนาจทางทหาร",
        "ความมั่นคง มั่งคั่ง และยั่งยืน",
        "เพิ่ม GDP ให้ติด Top 10 โลก",
        "ลดจำนวนประชากรให้เหมาะสม",
      ],
      correct: 1,
      explanation: "วิสัยทัศน์ยุทธศาสตร์ชาติ 20 ปีคือ 'ประเทศไทยมีความมั่นคง มั่งคั่ง ยั่งยืน'",
    },
    {
      id: 100,
      question: "ข้อใดถือเป็นการปฏิบัติที่ถูกต้องตามจริยธรรมของข้าราชการที่ดี",
      choices: [
        "รับของขวัญจากผู้มาติดต่อเพื่อรักษาความสัมพันธ์",
        "ใช้ตำแหน่งหน้าที่เพื่อช่วยเหลือญาติพี่น้อง",
        "ปฏิเสธของขวัญและเปิดเผยผลประโยชน์ทับซ้อน",
        "เลือกปฏิบัติงานตามความพึงพอใจส่วนตัว",
      ],
      correct: 2,
      explanation: "ข้าราชการที่ดีต้องปฏิเสธของขวัญ (ตามระเบียบ ป.ป.ช.) และเปิดเผยผลประโยชน์ทับซ้อนเพื่อความโปร่งใส",
    },
  ],
};

export const KP_MOCK_1: MockExam = {
  id: "kp-mock-1",
  title: "ข้อสอบจำลอง ก.พ. ชุดที่ 1",
  totalTime: 180,
  xpReward: 2000,
  rankReward: "ผู้ผ่านด่าน ก.พ. ระดับ 1",
  sections: [section1, section2, section3],
};
