import type { ExamQuestion, ExamSection, MockExam } from "./kp-mock-1";

// Contains the exam answer key — must never be imported from a "use client" file.
if (typeof window !== "undefined") {
  throw new Error("lib/exam-data/kp-mock-2 must only be imported on the server");
}

const section1: ExamSection = {
  id: "s1",
  title: "วิชาความรู้ความสามารถทั่วไป (คณิตศาสตร์ & ภาษาไทย)",
  shortTitle: "วิชาที่ 1",
  questionCount: 50,
  totalScore: 100,
  passingPercent: 60,
  timeRecommended: 90,
  questions: [
    // ── 1. อนุกรมตัวเลข ──────────────────────────────────────
    {
      id: 1,
      question: "อนุกรม 2, 6, 12, 20, 30, 42, ? มีค่าเท่าใด",
      choices: ["54", "55", "56", "57"],
      correct: 2,
      explanation: "รูปแบบ n×(n+1): 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42 → 7×8=56",
    },
    {
      id: 2,
      question: "อนุกรม 3, 7, 15, 31, 63, ? มีค่าเท่าใด",
      choices: ["125", "126", "127", "128"],
      correct: 2,
      explanation: "กฎ ×2+1: 3×2+1=7, 7×2+1=15, 15×2+1=31, 31×2+1=63 → 63×2+1=127",
    },
    {
      id: 3,
      question: "อนุกรม 2, 5, 11, 20, 32, ? มีค่าเท่าใด",
      choices: ["44", "46", "47", "49"],
      correct: 2,
      explanation: "ผลต่างเพิ่มทีละ 3: 3, 6, 9, 12, (15) → 32+15=47",
    },
    {
      id: 4,
      question: "อนุกรม 4, 7, 12, 20, 33, 54, ? มีค่าเท่าใด",
      choices: ["85", "86", "87", "88"],
      correct: 3,
      explanation: "ผลต่างเป็นอนุกรมฟีโบนักชี 3, 5, 8, 13, 21, (34) → 54+34=88",
    },
    {
      id: 5,
      question: "อนุกรม 6, 9, 15, 27, 51, ? มีค่าเท่าใด",
      choices: ["96", "97", "98", "99"],
      correct: 3,
      explanation: "กฎ ×2−3: 6×2−3=9, 9×2−3=15, 15×2−3=27, 27×2−3=51 → 51×2−3=99",
    },
    // ── 2. คณิตศาสตร์ทั่วไป ──────────────────────────────────
    {
      id: 6,
      question: "ราคาสินค้าขึ้นราคา 20% แล้วลดราคา 20% จากราคาที่ขึ้นแล้ว ราคาสุดท้ายเทียบกับราคาเดิมเปลี่ยนแปลงอย่างไร",
      choices: ["เท่าเดิม", "เพิ่มขึ้น 4%", "ลดลง 4%", "ลดลง 8%"],
      correct: 2,
      explanation: "100×1.2=120, 120×0.8=96 → ลดลง 4% จากราคาเดิม (ไม่เท่าเดิมเพราะฐานคำนวณคนละค่า)",
    },
    {
      id: 7,
      question: "งานชิ้นหนึ่ง นาย ก ทำคนเดียวเสร็จใน 12 วัน นาย ข ทำคนเดียวเสร็จใน 18 วัน ถ้าทำร่วมกันจะเสร็จภายในกี่วัน",
      choices: ["6 วัน", "7.2 วัน", "8 วัน", "9 วัน"],
      correct: 1,
      explanation: "อัตราเร็วรวม = 1/12+1/18 = 3/36+2/36 = 5/36 งาน/วัน → เวลา = 36/5 = 7.2 วัน",
    },
    {
      id: 8,
      question: "ผสมสารละลายเกลือความเข้มข้น 10% จำนวน 200 กรัม กับสารละลายเกลือความเข้มข้น 25% จำนวน 100 กรัม จะได้สารละลายความเข้มข้นกี่เปอร์เซ็นต์",
      choices: ["12.5%", "15%", "17.5%", "20%"],
      correct: 1,
      explanation: "เกลือรวม=200×0.1+100×0.25=20+25=45 กรัม จากสารละลายรวม 300 กรัม → 45/300×100=15%",
    },
    {
      id: 9,
      question: "รถออกเดินทางด้วยความเร็วเฉลี่ย 60 กม./ชม. เป็นเวลา 2 ชั่วโมง แล้วหยุดพัก 30 นาที จากนั้นเดินทางต่อด้วยความเร็ว 80 กม./ชม. อีก 1.5 ชั่วโมง ระยะทางรวมทั้งหมดเท่าใด",
      choices: ["200 กม.", "220 กม.", "240 กม.", "260 กม."],
      correct: 2,
      explanation: "ระยะทาง = (60×2)+(80×1.5) = 120+120 = 240 กม. (เวลาพักไม่มีผลต่อระยะทาง)",
    },
    {
      id: 10,
      question: "อัตราส่วน A:B = 2:3 และ B:C = 4:5 อัตราส่วน A:B:C เท่ากับเท่าใด",
      choices: ["6:9:15", "8:12:15", "8:9:15", "6:12:15"],
      correct: 1,
      explanation: "ปรับ B ให้เท่ากัน (คูณ A:B ด้วย 4, B:C ด้วย 3) → A:B=8:12, B:C=12:15 → A:B:C=8:12:15",
    },
    // ── 3. ตารางข้อมูล ────────────────────────────────────────
    {
      id: 11,
      question: "ตารางกำไรสุทธิ 4 สาขา (พันบาท) รายไตรมาส\nสาขา W: Q1=90  Q2=110 Q3=95  Q4=130\nสาขา X: Q1=150 Q2=140 Q3=160 Q4=170\nสาขา Y: Q1=60  Q2=70  Q3=90  Q4=100\nสาขา Z: Q1=120 Q2=115 Q3=118 Q4=112\n\nสาขาใดมีอัตราการเติบโตของกำไรจาก Q1 ถึง Q4 สูงสุด (เป็นเปอร์เซ็นต์)",
      choices: ["สาขา W", "สาขา X", "สาขา Y", "สาขา Z"],
      correct: 2,
      explanation: "%เติบโต: W=(130−90)/90=44.4%, X=(170−150)/150=13.3%, Y=(100−60)/60=66.7%, Z=(112−120)/120=−6.7% → Y สูงสุด",
    },
    {
      id: 12,
      question: "จากตารางข้อ 11 กำไรรวมทั้งปีของสาขาใดสูงสุด",
      choices: ["สาขา W", "สาขา X", "สาขา Y", "สาขา Z"],
      correct: 1,
      explanation: "กำไรรวม W=425, X=620, Y=320, Z=465 (พันบาท) → สาขา X สูงสุด",
    },
    {
      id: 13,
      question: "จากตารางข้อ 11 กำไรเฉลี่ยต่อไตรมาสของทั้ง 4 สาขารวมกันเท่ากับเท่าใด",
      choices: ["427.5 พันบาท", "447.5 พันบาท", "457.5 พันบาท", "467.5 พันบาท"],
      correct: 2,
      explanation: "กำไรรวมทั้งปีทุกสาขา=425+620+320+465=1,830 พันบาท ÷ 4 ไตรมาส = 457.5 พันบาท/ไตรมาส",
    },
    {
      id: 14,
      question: "จากตารางข้อ 11 สาขา Z มีกำไรลดลงจากไตรมาสก่อนหน้ามากที่สุดในไตรมาสใด",
      choices: ["Q2 ลดลงประมาณ 4.2%", "Q3 ลดลงประมาณ 2.5%", "Q4 ลดลงประมาณ 5.1%", "ไม่มีไตรมาสใดลดลง"],
      correct: 2,
      explanation: "Q2 ลดจาก 120→115 = 4.2%, Q3 กลับเพิ่มขึ้นเป็น 118 (ไม่ลด), Q4 ลดจาก 118→112 = 5.1% (มากกว่า) → คำตอบคือ Q4",
    },
    {
      id: 15,
      question: "จากตารางข้อ 11 กำไร Q3 รวมของทุกสาขา คิดเป็นสัดส่วนกี่เปอร์เซ็นต์ของกำไรรวมทั้งปีของทุกสาขา (ปัดเศษทศนิยม 1 ตำแหน่ง)",
      choices: ["23.5%", "24.7%", "25.3%", "26.8%"],
      correct: 2,
      explanation: "กำไร Q3 รวม=95+160+90+118=463 พันบาท จากกำไรรวมทั้งปี 1,830 พันบาท → 463/1830×100≈25.3%",
    },
    // ── 4. เงื่อนไขสัญลักษณ์ (อสมการ) ──────────────────────
    {
      id: 16,
      question: "กำหนดให้ x > y > z > 0 และ w = x − z\nข้อสรุปที่ 1: w > x − y\nข้อสรุปที่ 2: w > y − z\nข้อใดถูกต้อง",
      choices: [
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ผิด",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ผิด",
      ],
      correct: 0,
      explanation: "w=(x−y)+(y−z) ทั้งสองพจน์เป็นบวก → w>x−y (เพราะ y−z>0) ✓ และ w>y−z (เพราะ x−y>0) ✓ ทั้งสองถูก",
    },
    {
      id: 17,
      question: "กำหนดให้ x > y > z > 0 และ w = x − z\nข้อสรุปที่ 1: w < x\nข้อสรุปที่ 2: w > z\nข้อใดถูกต้อง",
      choices: [
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ผิด",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ผิด",
      ],
      correct: 1,
      explanation: "w=x−z<x เสมอเพราะ z>0 ✓ แต่ w>z ⟺ x>2z ซึ่งไม่ได้กำหนดไว้ จึงสรุปแน่นอนไม่ได้ ถือว่าผิด",
    },
    {
      id: 18,
      question: "กำหนดให้ a, b, c เป็นจำนวนจริง โดย a+b=10, b+c=14, a+c=12\nข้อสรุปที่ 1: a+b+c=18\nข้อสรุปที่ 2: b>a\nข้อใดถูกต้อง",
      choices: [
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ผิด",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ผิด",
      ],
      correct: 0,
      explanation: "รวม 3 สมการ: 2(a+b+c)=36 → a+b+c=18 ✓ แก้สมการได้ a=4, b=6, c=8 → b=6>a=4 ✓ ทั้งสองถูก",
    },
    {
      id: 19,
      question: "จากข้อมูลข้อ 18 (a=4, b=6, c=8)\nข้อสรุปที่ 1: c > a+b\nข้อสรุปที่ 2: a×c = b²\nข้อใดถูกต้อง",
      choices: [
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ผิด",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ผิด",
      ],
      correct: 3,
      explanation: "a+b=10>c=8 → c ไม่มากกว่า a+b ผิด และ a×c=32≠b²=36 → ผิด ทั้งสองผิด",
    },
    {
      id: 20,
      question: "กำหนดให้ p, q เป็นจำนวนเต็มบวก โดย p²−q²=45 และ p−q=5\nข้อสรุปที่ 1: p+q=9\nข้อสรุปที่ 2: p=7\nข้อใดถูกต้อง",
      choices: [
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ผิด",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ผิด",
      ],
      correct: 0,
      explanation: "(p−q)(p+q)=p²−q²=45 และ p−q=5 → p+q=9 ✓ แก้ระบบสมการได้ p=7, q=2 ✓ ทั้งสองถูก",
    },
    {
      id: 21,
      question: "จากข้อมูลข้อ 20 (p=7, q=2)\nข้อสรุปที่ 1: q²=4\nข้อสรุปที่ 2: p×q=15\nข้อใดถูกต้อง",
      choices: [
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ผิด",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ผิด",
      ],
      correct: 1,
      explanation: "q=2 → q²=4 ✓ แต่ p×q=7×2=14≠15 → ผิด",
    },
    {
      id: 22,
      question: "กำหนดให้ A = 25% ของ 240, B = 60% ของ A\nข้อสรุปที่ 1: B=36\nข้อสรุปที่ 2: A−B=24\nข้อใดถูกต้อง",
      choices: [
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ผิด",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ผิด",
      ],
      correct: 0,
      explanation: "A=25%×240=60, B=60%×60=36 ✓ และ A−B=60−36=24 ✓ ทั้งสองถูก",
    },
    {
      id: 23,
      question: "จากข้อมูลข้อ 22 (A=60, B=36)\nข้อสรุปที่ 1: B/A=0.5\nข้อสรุปที่ 2: A+B>2B\nข้อใดถูกต้อง",
      choices: [
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ผิด",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ผิด",
      ],
      correct: 2,
      explanation: "B/A=36/60=0.6≠0.5 → ผิด แต่ A+B=96>2B=72 → ถูก",
    },
    {
      id: 24,
      question: "ชุดตัวเลข 3 จำนวน มีค่าเฉลี่ยเท่ากับ 15 จำนวนที่มากที่สุดคือ 22 จำนวนที่น้อยที่สุดคือ 9\nข้อสรุปที่ 1: จำนวนที่สามมีค่า 14\nข้อสรุปที่ 2: จำนวนที่สามมากกว่าค่าเฉลี่ย\nข้อใดถูกต้อง",
      choices: [
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ผิด",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ผิด",
      ],
      correct: 1,
      explanation: "ผลรวม=15×3=45 → จำนวนที่สาม=45−22−9=14 ✓ แต่ 14<15 (ค่าเฉลี่ย) → ผิด",
    },
    {
      id: 25,
      question: "กำหนดให้ x เป็นจำนวนเต็ม โดย 3x−7 < 14 และ 2x+1 > 9\nข้อสรุปที่ 1: x อาจเท่ากับ 5\nข้อสรุปที่ 2: x อาจเท่ากับ 7\nข้อใดถูกต้อง",
      choices: [
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ถูก และข้อสรุปที่ 2 ผิด",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ถูก",
        "ข้อสรุปที่ 1 ผิด และข้อสรุปที่ 2 ผิด",
      ],
      correct: 1,
      explanation: "3x−7<14 → x<7 และ 2x+1>9 → x>4 ดังนั้น 4<x<7 → x เป็นได้แค่ 5 หรือ 6 → x=5 ได้ ✓ แต่ x=7 ไม่ได้ (ไม่รวมค่า 7) → ผิด",
    },
    // ── 5. อุปมาอุปไมย ────────────────────────────────────────
    {
      id: 26,
      question: "กฎหมาย : ความยุติธรรม :: การศึกษา : ?",
      choices: ["ปัญญา", "โรงเรียน", "ครู", "หนังสือ"],
      correct: 0,
      explanation: "กฎหมายมีเป้าหมายเพื่อความยุติธรรม การศึกษามีเป้าหมายเพื่อปัญญา (ความสัมพันธ์: สิ่ง : เป้าหมายสูงสุด)",
    },
    {
      id: 27,
      question: "เมล็ดพันธุ์ : ต้นไม้ :: ไข่ : ?",
      choices: ["เปลือกไข่", "ลูกนก", "รัง", "แม่ไก่"],
      correct: 1,
      explanation: "เมล็ดพันธุ์เติบโตกลายเป็นต้นไม้ ไข่ฟักออกมาเป็นลูกนก (ความสัมพันธ์: ระยะเริ่มต้น : ระยะเติบโต)",
    },
    {
      id: 28,
      question: "งบประมาณ : กระทรวงการคลัง :: นโยบายต่างประเทศ : ?",
      choices: ["กระทรวงมหาดไทย", "กระทรวงกลาโหม", "กระทรวงการต่างประเทศ", "สำนักนายกรัฐมนตรี"],
      correct: 2,
      explanation: "งบประมาณเป็นความรับผิดชอบหลักของกระทรวงการคลัง นโยบายต่างประเทศเป็นความรับผิดชอบหลักของกระทรวงการต่างประเทศ",
    },
    {
      id: 29,
      question: "สาเหตุ : ผลลัพธ์ :: สมมติฐาน : ?",
      choices: ["ทฤษฎี", "การทดลอง", "ข้อสรุป", "ตัวแปร"],
      correct: 2,
      explanation: "สาเหตุนำไปสู่ผลลัพธ์ สมมติฐานเมื่อพิสูจน์แล้วนำไปสู่ข้อสรุป (ความสัมพันธ์เชิงเหตุ-ผลของกระบวนการ)",
    },
    {
      id: 30,
      question: "มาตรการป้องกัน : ก่อนเกิดเหตุ :: มาตรการเยียวยา : ?",
      choices: ["ก่อนเกิดเหตุ", "ระหว่างเกิดเหตุ", "หลังเกิดเหตุ", "ไม่มีช่วงเวลาที่แน่นอน"],
      correct: 2,
      explanation: "มาตรการป้องกันดำเนินการก่อนเกิดเหตุ มาตรการเยียวยาดำเนินการหลังเกิดเหตุ (ความสัมพันธ์: มาตรการ : ช่วงเวลาที่ใช้)",
    },
    // ── 6. เงื่อนไขภาษา ───────────────────────────────────────
    {
      id: 31,
      question: "บุคคล 6 คน P Q R S T U นั่งเรียงแถวเดียวจากซ้ายไปขวา (ที่ 1-6)\nเงื่อนไข: P นั่งที่ 3 / Q นั่งห่างจาก P สองที่นั่งทางขวา / R นั่งติดกับ Q ทางซ้าย / S นั่งซ้ายสุด / T นั่งขวาสุด\nใครนั่งที่ 2",
      choices: ["Q", "R", "S", "U"],
      correct: 3,
      explanation: "P=ที่3, Q=ที่5 (ห่างจาก P 2 ที่ทางขวา), R=ที่4 (ติดกับ Q ด้านซ้าย), S=ที่1, T=ที่6 → เหลือที่2ให้ U",
    },
    {
      id: 32,
      question: "งาน P Q R S T ต้องทำตามเงื่อนไข\nเงื่อนไข: P ต้องทำก่อน Q / Q ต้องทำก่อน T / T ต้องทำก่อน R / R ต้องทำก่อน S\nลำดับใดถูกต้อง",
      choices: ["P Q T R S", "P Q R T S", "Q P T R S", "P T Q R S"],
      correct: 0,
      explanation: "เรียงตามเงื่อนไข P→Q→T→R→S ได้ลำดับเดียวคือ P Q T R S",
    },
    {
      id: 33,
      question: "บุคคล 1 2 3 4 5 6 มีส่วนสูงต่างกัน\nเงื่อนไข: 1 สูงกว่า 3 แต่เตี้ยกว่า 5 / 2 สูงกว่า 4 แต่เตี้ยกว่า 6 / 5 สูงกว่า 6 / 3 สูงกว่า 4\nใครสูงที่สุด และใครเตี้ยที่สุด",
      choices: ["5 สูงสุด และ 3 เตี้ยสุด", "5 สูงสุด และ 4 เตี้ยสุด", "1 สูงสุด และ 4 เตี้ยสุด", "6 สูงสุด และ 4 เตี้ยสุด"],
      correct: 1,
      explanation: "จากเงื่อนไข 5>1>3>4 และ 5>6>2>4 → 5 สูงกว่าทุกคน (สูงสุด) และ 4 เตี้ยกว่าทุกคนที่เทียบได้ (เตี้ยสุด)",
    },
    {
      id: 34,
      question: "ตู้เก็บเอกสาร 6 ชั้น (ชั้น 1 ล่างสุด ถึง ชั้น 6 บนสุด) เก็บแฟ้ม A B C D E F\nเงื่อนไข: A อยู่สูงกว่า B 2 ชั้น / C อยู่ชั้นบนสุด / D อยู่ใต้ B โดยตรง / E อยู่ระหว่าง A กับ C\nแฟ้มใดอยู่ชั้นล่างสุด",
      choices: ["A", "B", "D", "F"],
      correct: 2,
      explanation: "กำหนด C=ชั้น6 ลองแทน B=ชั้น2 → A=ชั้น4 (สูงกว่า B 2 ชั้น), D=ชั้น1 (ใต้ B โดยตรง), E=ชั้น5 (ระหว่าง A กับ C), F=ชั้น3 (ที่เหลือ) เป็นคำตอบเดียวที่ลงตัว → ชั้นล่างสุดคือ D",
    },
    {
      id: 35,
      question: "โต๊ะประชุมกลม 8 ที่นั่ง (ที่ 1-8 ตามเข็มนาฬิกา)\nเงื่อนไข: นาย ก นั่งที่ 1 / นาย ข นั่งตรงข้าม ก / นาย ค นั่งห่างจาก ก 3 ที่ทางขวา (ตามเข็มนาฬิกา) / นาย ง นั่งติดกับ ค ทางซ้าย\nนาย ง นั่งที่เท่าใด",
      choices: ["ที่ 2", "ที่ 3", "ที่ 6", "ที่ 7"],
      correct: 1,
      explanation: "ก=ที่1, ข=ที่5 (ตรงข้าม ก, 8ที่นั่ง+4), ค=ที่4 (ห่างจาก ก 3 ที่ทางขวา), ง=ที่3 (ติดกับ ค ทางซ้าย คือ 4−1=3)",
    },
    // ── 7. เรียงประโยค ────────────────────────────────────────
    {
      id: 36,
      question: "จงเรียงประโยคต่อไปนี้ให้ถูกต้อง\nก. จึงส่งผลกระทบต่อความมั่นคงทางอาหารของประชาชน\nข. การเปลี่ยนแปลงสภาพภูมิอากาศทำให้ผลผลิตทางการเกษตรไม่แน่นอน\nค. เกษตรกรจึงหันมาใช้เทคโนโลยีเพื่อบริหารจัดการความเสี่ยง\nง. เช่น ภัยแล้งที่ยาวนานและฝนตกนอกฤดูกาล\nจ. ซึ่งรวมถึงระบบพยากรณ์อากาศและการให้น้ำอัตโนมัติ",
      choices: ["ข ง ก ค จ", "ข ก ง ค จ", "ง ข ก ค จ", "ข ง ค ก จ"],
      correct: 0,
      explanation: "ข(ปัญหาโลกร้อนกระทบผลผลิต)→ง(ตัวอย่างภัยแล้ง/ฝนนอกฤดู)→ก(ผลต่อความมั่นคงอาหาร)→ค(เกษตรกรปรับใช้เทคโนโลยี)→จ(รายละเอียดเทคโนโลยีที่ใช้)",
    },
    {
      id: 37,
      question: "จงเรียงประโยคต่อไปนี้ให้ถูกต้อง\nก. แต่ก็มีความเสี่ยงด้านความเป็นส่วนตัวและความปลอดภัยของข้อมูล\nข. ปัญญาประดิษฐ์เข้ามามีบทบาทในชีวิตประจำวันมากขึ้นเรื่อยๆ\nค. ดังนั้นการออกกฎหมายกำกับดูแลจึงมีความจำเป็นอย่างยิ่ง\nง. ช่วยอำนวยความสะดวกในหลายด้าน เช่น การแพทย์และการศึกษา\nจ. เพื่อสร้างสมดุลระหว่างนวัตกรรมและการคุ้มครองสิทธิประชาชน",
      choices: ["ข ง ก ค จ", "ข ก ง ค จ", "ง ข ก ค จ", "ข ง ค ก จ"],
      correct: 0,
      explanation: "ข(AIมีบทบาทมากขึ้น)→ง(ประโยชน์ด้านการแพทย์/การศึกษา)→ก(แต่มีความเสี่ยงข้อมูล)→ค(จึงต้องมีกฎหมาย)→จ(เพื่อสมดุลนวัตกรรมกับสิทธิ)",
    },
    {
      id: 38,
      question: "จงเรียงประโยคต่อไปนี้ให้ถูกต้อง\nก. โดยเฉพาะกลุ่มเปราะบาง เช่น ผู้สูงอายุและผู้มีรายได้น้อย\nข. ภาวะเงินเฟ้อทำให้ค่าครองชีพของประชาชนสูงขึ้น\nค. ภาครัฐจึงออกมาตรการช่วยเหลือค่าครองชีพในระยะสั้น\nง. ส่งผลกระทบโดยตรงต่อกำลังซื้อของประชาชนทุกกลุ่ม\nจ. พร้อมทั้งวางแผนควบคุมเงินเฟ้อในระยะยาวควบคู่กัน",
      choices: ["ข ง ก ค จ", "ข ก ง ค จ", "ง ข ก ค จ", "ข ง จ ค ก"],
      correct: 0,
      explanation: "ข(เงินเฟ้อทำให้ค่าครองชีพสูง)→ง(กระทบกำลังซื้อ)→ก(โดยเฉพาะกลุ่มเปราะบาง)→ค(รัฐออกมาตรการช่วยเหลือ)→จ(วางแผนระยะยาวควบคู่)",
    },
    {
      id: 39,
      question: "จงเรียงประโยคต่อไปนี้ให้ถูกต้อง\nก. เนื่องจากมีสารอาหารและใยอาหารสูง แต่มีแคลอรีต่ำ\nข. การรับประทานผักและผลไม้เป็นประจำมีประโยชน์ต่อสุขภาพ\nค. จึงควรบริโภคผักผลไม้อย่างน้อยวันละ 400 กรัม\nง. ช่วยลดความเสี่ยงของโรคไม่ติดต่อเรื้อรัง เช่น เบาหวานและความดันโลหิตสูง\nจ. ตามคำแนะนำขององค์การอนามัยโลก",
      choices: ["ข ก ง ค จ", "ข ง ก ค จ", "ก ข ง ค จ", "ข ก ค ง จ"],
      correct: 0,
      explanation: "ข(ประโยชน์ของผักผลไม้)→ก(เพราะมีสารอาหารสูงแคลอรีต่ำ)→ง(ลดความเสี่ยงโรคเรื้อรัง)→ค(จึงควรบริโภคตามปริมาณ)→จ(อ้างอิงคำแนะนำ WHO)",
    },
    {
      id: 40,
      question: "จงเรียงประโยคต่อไปนี้ให้ถูกต้อง\nก. ทำให้เกิดปัญหาการจราจรติดขัดอย่างรุนแรงในช่วงเวลาเร่งด่วน\nข. เมืองใหญ่หลายแห่งประสบปัญหาจำนวนรถยนต์ส่วนบุคคลเพิ่มขึ้นอย่างรวดเร็ว\nค. รวมถึงส่งเสริมการใช้จักรยานและการเดินในระยะสั้น\nง. หน่วยงานที่เกี่ยวข้องจึงเร่งพัฒนาระบบขนส่งมวลชนให้ครอบคลุมมากขึ้น\nจ. เพื่อจูงใจให้ประชาชนลดการใช้รถยนต์ส่วนตัว",
      choices: ["ข ก ง ค จ", "ก ข ง ค จ", "ข ง ก ค จ", "ข ก ค ง จ"],
      correct: 0,
      explanation: "ข(ปัญหารถยนต์เพิ่มขึ้น)→ก(ทำให้จราจรติดขัด)→ง(รัฐเร่งพัฒนาขนส่งมวลชน)→ค(รวมถึงส่งเสริมจักรยาน/เดิน)→จ(เพื่อจูงใจลดใช้รถส่วนตัว)",
    },
    // ── 8. เลือกใช้คำ ─────────────────────────────────────────
    {
      id: 41,
      question: "ข้อใดใช้คำ \"ทั้งนี้\" ได้ถูกต้องตามหลักภาษาราชการ",
      choices: [
        "ทั้งนี้ เนื่องจากงบประมาณมีจำกัด จึงขอชะลอโครงการไว้ก่อน",
        "ทั้งนี้ทั้งนั้น ให้ทำตามที่เห็นสมควร",
        "เขาทั้งนี้ต้องเดินทางไปราชการ",
        "ทั้งนี้คือเหตุผลที่แท้จริง",
      ],
      correct: 0,
      explanation: "\"ทั้งนี้\" ใช้เชื่อมความเพื่อขยายความหรือกำหนดเงื่อนไขเพิ่มเติมในภาษาราชการ เช่น \"ทั้งนี้ เนื่องจาก...จึง...\"",
    },
    {
      id: 42,
      question: "คำว่า \"ดำเนินการ\" กับ \"ดำเนินงาน\" ต่างกันอย่างไร",
      choices: [
        "ไม่มีความแตกต่าง ใช้แทนกันได้เสมอ",
        "ดำเนินการ ใช้กับกิจกรรมเฉพาะเรื่อง ส่วนดำเนินงาน ใช้กับภาพรวมของงานทั้งระบบ",
        "ดำเนินการ ใช้กับเอกชน ดำเนินงาน ใช้กับราชการ",
        "ดำเนินการ เป็นคำโบราณ ไม่ควรใช้",
      ],
      correct: 1,
      explanation: "\"ดำเนินการ\" มักใช้กับกิจกรรมหรือขั้นตอนเฉพาะเรื่อง เช่น ดำเนินการสอบสวน ส่วน \"ดำเนินงาน\" ใช้กับภาพรวมของงานทั้งระบบ เช่น แผนดำเนินงานประจำปี",
    },
    {
      id: 43,
      question: "คำใดเป็นคำพ้องความหมายกับ \"พิเคราะห์\"",
      choices: ["ละเลย", "ตรวจตราพิจารณาอย่างถี่ถ้วน", "ประกาศ", "ตัดสิน"],
      correct: 1,
      explanation: "\"พิเคราะห์\" หมายถึง ตรวจตราพิจารณาอย่างละเอียดถี่ถ้วนก่อนตัดสินใจ",
    },
    {
      id: 44,
      question: "ข้อใดสะกดถูกต้องทุกคำ",
      choices: [
        "พฤติกรรม, สัญญาณ, อนุญาต, กรรมสิทธิ์",
        "พฤติกรรม, สัญญาน, อนุญาติ, กรรมสิทธิ์",
        "พฤติกรรม, สัญญาณ, อนุญาติ, กรรมสิทธิ",
        "พฤกติกรรม, สัญญาณ, อนุญาต, กรรมสิทธิ์",
      ],
      correct: 0,
      explanation: "สะกดที่ถูกต้องคือ พฤติกรรม สัญญาณ อนุญาต กรรมสิทธิ์ (คำที่มักสะกดผิด: สัญญาณ ไม่ใช่ \"สัญญาน\", อนุญาต ไม่ใช่ \"อนุญาติ\")",
    },
    {
      id: 45,
      question: "สำนวน \"กระต่ายตื่นตูม\" หมายความว่าอย่างไร",
      choices: ["วิ่งเร็วมาก", "ตกใจง่ายโดยไม่ทันไตร่ตรองข้อเท็จจริง", "ระมัดระวังตัวมากเกินไป", "หลบหนีเมื่อพบอันตราย"],
      correct: 1,
      explanation: "สำนวนนี้หมายถึงคนที่ตื่นตระหนกตกใจง่ายต่อเรื่องที่ยังไม่ได้พิสูจน์ให้แน่ชัด",
    },
    // ── 9. อ่านจับใจความ ─────────────────────────────────────
    {
      id: 46,
      question: "อ่านข้อความต่อไปนี้แล้วตอบคำถาม\n\n\"การกระจายอำนาจสู่ท้องถิ่นถูกมองว่าเป็นกลไกสำคัญในการพัฒนาประชาธิปไตยฐานราก เนื่องจากทำให้ประชาชนในพื้นที่มีส่วนร่วมตัดสินใจในเรื่องที่ใกล้ตัวมากขึ้น อย่างไรก็ตาม การกระจายอำนาจที่ไม่มาพร้อมกับการกระจายทรัพยากรและบุคลากรที่มีศักยภาพเพียงพอ อาจนำไปสู่ความเหลื่อมล้ำระหว่างท้องถิ่นที่มีศักยภาพสูงกับท้องถิ่นที่ขาดแคลนทรัพยากร ดังนั้น การปฏิรูปโครงสร้างการคลังท้องถิ่นจึงต้องดำเนินควบคู่ไปกับการกระจายอำนาจเสมอ\"\n\nข้อใดคือใจความสำคัญที่สุดของบทความ",
      choices: [
        "การกระจายอำนาจเป็นสิ่งที่ไม่ควรทำ",
        "การกระจายอำนาจมีประโยชน์ แต่ต้องควบคู่กับการกระจายทรัพยากรเพื่อไม่ให้เกิดความเหลื่อมล้ำ",
        "ท้องถิ่นทุกแห่งมีศักยภาพเท่ากันอยู่แล้ว",
        "รัฐบาลกลางควรควบคุมท้องถิ่นอย่างเข้มงวด",
      ],
      correct: 1,
      explanation: "บทความชี้ว่าการกระจายอำนาจมีประโยชน์ต่อประชาธิปไตยฐานราก แต่ต้องมาพร้อมกับการกระจายทรัพยากรเพื่อป้องกันความเหลื่อมล้ำ",
    },
    {
      id: 47,
      question: "จากบทความเดิม (ข้อ 46) สิ่งที่อาจเกิดขึ้นหากกระจายอำนาจโดยไม่กระจายทรัพยากรคืออะไร",
      choices: [
        "ประชาธิปไตยฐานรากจะแข็งแกร่งขึ้น",
        "เกิดความเหลื่อมล้ำระหว่างท้องถิ่น",
        "ท้องถิ่นทุกแห่งจะพัฒนาเท่ากัน",
        "รัฐบาลกลางจะมีอำนาจเพิ่มขึ้น",
      ],
      correct: 1,
      explanation: "บทความระบุว่าอาจ \"นำไปสู่ความเหลื่อมล้ำระหว่างท้องถิ่นที่มีศักยภาพสูงกับท้องถิ่นที่ขาดแคลนทรัพยากร\"",
    },
    {
      id: 48,
      question: "จากบทความเดิม (ข้อ 46) ข้อใดคือข้อเสนอแนะของผู้เขียน",
      choices: [
        "ยกเลิกการกระจายอำนาจทั้งหมด",
        "ปฏิรูปโครงสร้างการคลังท้องถิ่นควบคู่กับการกระจายอำนาจ",
        "ให้รัฐบาลกลางบริหารท้องถิ่นโดยตรง",
        "ลดจำนวนองค์กรปกครองส่วนท้องถิ่น",
      ],
      correct: 1,
      explanation: "บทความสรุปว่า \"การปฏิรูปโครงสร้างการคลังท้องถิ่นจึงต้องดำเนินควบคู่ไปกับการกระจายอำนาจเสมอ\"",
    },
    {
      id: 49,
      question: "จากบทความเดิม (ข้อ 46) คำว่า \"ประชาธิปไตยฐานราก\" หมายถึงสิ่งใดใกล้เคียงที่สุด",
      choices: [
        "ประชาธิปไตยระดับชาติ",
        "การมีส่วนร่วมทางการเมืองของประชาชนในระดับท้องถิ่น",
        "ระบบการเลือกตั้งทั่วไป",
        "การกระจายอำนาจให้ข้าราชการ",
      ],
      correct: 1,
      explanation: "\"ประชาธิปไตยฐานราก\" หมายถึงการมีส่วนร่วมทางการเมืองและการตัดสินใจของประชาชนในระดับท้องถิ่นซึ่งใกล้ชิดกับชีวิตประจำวันที่สุด",
    },
    {
      id: 50,
      question: "จากบทความเดิม (ข้อ 46) ข้อใดเป็นการอนุมาน (inference) ที่สมเหตุสมผลที่สุด แม้ไม่ได้กล่าวไว้ตรงๆ",
      choices: [
        "ท้องถิ่นที่มีรายได้สูงจะได้ประโยชน์จากการกระจายอำนาจมากกว่าท้องถิ่นที่มีรายได้ต่ำหากไม่มีมาตรการเสริม",
        "การกระจายอำนาจจะทำให้ท้องถิ่นทุกแห่งมีรายได้เท่ากันโดยอัตโนมัติ",
        "ประชาชนไม่ต้องการมีส่วนร่วมในการตัดสินใจท้องถิ่น",
        "การปฏิรูปการคลังท้องถิ่นไม่มีความจำเป็นในทางปฏิบัติ",
      ],
      correct: 0,
      explanation: "จากที่บทความระบุว่าอาจเกิดความเหลื่อมล้ำระหว่างท้องถิ่นศักยภาพสูงกับต่ำ อนุมานได้ว่าท้องถิ่นที่มีรายได้/ทรัพยากรสูงอยู่แล้วจะได้ประโยชน์มากกว่าหากไม่มีมาตรการกระจายทรัพยากรเสริม",
    },
  ],
};

const section2: ExamSection = {
  id: "s2",
  title: "วิชาภาษาอังกฤษ",
  shortTitle: "วิชาที่ 2",
  questionCount: 25,
  totalScore: 50,
  passingPercent: 50,
  timeRecommended: 45,
  questions: [
    // ── Conversation (Q51–55) ────────────────────────────────
    {
      id: 51,
      question: "A: \"I was wondering if you could possibly spare a moment to go over the quarterly figures with me.\"\nB: \"______\"\n\nChoose the most appropriate response.",
      choices: [
        "No, I can't.",
        "Of course, let me just wrap up this email and I'll be right with you.",
        "Why are you asking me that?",
        "I don't have figures.",
      ],
      correct: 1,
      explanation: "การตอบรับคำขอที่สุภาพ (I was wondering if...) ควรตอบรับอย่างสุภาพและให้ข้อมูลที่เป็นประโยชน์",
    },
    {
      id: 52,
      question: "A: \"I hate to bring this up, but your report was submitted three days past the deadline.\"\nB: \"______\"\n\nWhich response best acknowledges responsibility while sounding professional?",
      choices: [
        "That's not really my problem.",
        "You're overreacting about a few days.",
        "You're right, I should have communicated the delay sooner. It won't happen again.",
        "Everyone submits reports late sometimes.",
      ],
      correct: 2,
      explanation: "การตอบรับคำตักเตือนอย่างมืออาชีพควรยอมรับผิดและแสดงความรับผิดชอบ ไม่ใช่ปฏิเสธหรือลดความสำคัญของปัญหา",
    },
    {
      id: 53,
      question: "A: \"Given the circumstances, would it be possible to push our meeting back to next week instead?\"\nB: \"______\"\n\nChoose the most diplomatic reply.",
      choices: [
        "I suppose that could work — let me check my calendar and confirm by tomorrow.",
        "Fine, whatever you want.",
        "That's inconvenient for me.",
        "Why do you need to change it?",
      ],
      correct: 0,
      explanation: "การตอบรับข้อเสนออย่างมีมารยาทและมืออาชีพ ควรแสดงความยืดหยุ่นพร้อมยืนยันในภายหลัง",
    },
    {
      id: 54,
      question: "A: \"I don't mean to be blunt, but I think the proposal needs significant revision before we present it.\"\nB: \"______\"\n\nWhich response shows constructive acceptance of criticism?",
      choices: [
        "I appreciate your honesty. Could you point out the specific areas you think need work?",
        "You're wrong, the proposal is perfect.",
        "That's a rude thing to say.",
        "I'll just cancel the presentation then.",
      ],
      correct: 0,
      explanation: "การรับฟังคำวิจารณ์อย่างสร้างสรรค์ ควรขอบคุณและขอรายละเอียดเพิ่มเติมเพื่อนำไปปรับปรุง",
    },
    {
      id: 55,
      question: "A: \"We really appreciate everything you've done, but we've decided to go with another vendor this time.\"\nB: \"______\"\n\nChoose the most professional response to being rejected.",
      choices: [
        "That's unfair, you should reconsider.",
        "Thank you for letting me know. I'd welcome any feedback for future opportunities.",
        "Fine, I won't work with you again.",
        "I don't understand why.",
      ],
      correct: 1,
      explanation: "การตอบรับการถูกปฏิเสธอย่างมืออาชีพ ควรขอบคุณและเปิดรับข้อเสนอแนะเพื่อโอกาสในอนาคต",
    },
    // ── Vocabulary (Q56–60) ──────────────────────────────────
    {
      id: 56,
      question: "Choose the word closest in meaning to \"MERITOCRACY\".",
      choices: [
        "A system based on family connections",
        "A system where advancement is based on ability and achievement",
        "A system based on random selection",
        "A system based on seniority alone",
      ],
      correct: 1,
      explanation: "MERITOCRACY หมายถึง ระบบคุณธรรมที่การเลื่อนตำแหน่งขึ้นอยู่กับความสามารถและผลงาน",
    },
    {
      id: 57,
      question: "The word \"EXPEDITE\" in official correspondence most nearly means:",
      choices: ["To delay a process", "To speed up or facilitate a process", "To cancel a process", "To complicate a process"],
      correct: 1,
      explanation: "EXPEDITE หมายถึง เร่งรัดหรือทำให้กระบวนการเสร็จเร็วขึ้น",
    },
    {
      id: 58,
      question: "\"The committee decided to ______ the project due to insufficient funding.\" Choose the best word.",
      choices: ["expedite", "suspend", "endorse", "commence"],
      correct: 1,
      explanation: "'Suspend' (ระงับ/ชะลอ) เหมาะสมที่สุดในบริบทของการหยุดโครงการชั่วคราวเพราะขาดงบประมาณ",
    },
    {
      id: 59,
      question: "Choose the word opposite in meaning to \"SCRUTINIZE\".",
      choices: ["Examine closely", "Overlook", "Investigate", "Inspect thoroughly"],
      correct: 1,
      explanation: "SCRUTINIZE แปลว่า ตรวจสอบอย่างละเอียด คำตรงข้ามคือ OVERLOOK (มองข้าม ไม่ตรวจสอบ)",
    },
    {
      id: 60,
      question: "The phrase \"vested interest\" most nearly means:",
      choices: [
        "A personal stake or benefit in a matter, often affecting objectivity",
        "A type of clothing worn by officials",
        "A legal document granting authority",
        "A neutral opinion with no bias",
      ],
      correct: 0,
      explanation: "'Vested interest' หมายถึง ผลประโยชน์ส่วนตัวที่เกี่ยวข้องกับเรื่องใดเรื่องหนึ่ง ซึ่งอาจส่งผลต่อความเป็นกลาง",
    },
    // ── Grammar (Q61–65) ─────────────────────────────────────
    {
      id: 61,
      question: "Choose the correct sentence:",
      choices: [
        "Not only did she finish the report, but she also submitted it early.",
        "Not only she did finish the report, but also she submitted it early.",
        "Not only did she finished the report, but also submitted it early.",
        "Not only she finished the report, but also she did submitted it early.",
      ],
      correct: 0,
      explanation: "'Not only...but also' ที่ขึ้นต้นประโยคต้องมีการกลับโครงสร้าง (inversion): Not only did she + V1",
    },
    {
      id: 62,
      question: "\"Had the minister been informed earlier, the crisis ______ prevented.\"",
      choices: ["would have been", "will be", "would be", "had been"],
      correct: 0,
      explanation: "Third Conditional แบบ inversion (Had + subject + V3) ใช้คู่กับ would have + V3 ใน main clause",
    },
    {
      id: 63,
      question: "Choose the sentence with the correct use of the subjunctive mood:",
      choices: [
        "The regulation requires that every officer submits the form.",
        "The regulation requires that every officer submit the form.",
        "The regulation requires that every officer will submit the form.",
        "The regulation requires that every officer is submitting the form.",
      ],
      correct: 1,
      explanation: "หลัง 'requires that' ใช้ subjunctive mood คือกริยารูปเดิม (base form) โดยไม่ผัน -s แม้ประธานเป็นเอกพจน์ → submit",
    },
    {
      id: 64,
      question: "Choose the sentence with the correct relative clause:",
      choices: [
        "The officer, whom was responsible for the audit, resigned.",
        "The officer, who was responsible for the audit, resigned.",
        "The officer, which was responsible for the audit, resigned.",
        "The officer, whose was responsible for the audit, resigned.",
      ],
      correct: 1,
      explanation: "'Who' ใช้เป็นประธาน (subject) ของอนุประโยค อ้างถึงคน ส่วน 'whom' ใช้เป็นกรรม (object)",
    },
    {
      id: 65,
      question: "Choose the sentence with correct parallel structure:",
      choices: [
        "The policy aims to reduce costs, improving efficiency, and increases transparency.",
        "The policy aims to reduce costs, improve efficiency, and increase transparency.",
        "The policy aims to reducing costs, improving efficiency, and increase transparency.",
        "The policy aims to reduce costs, to improving efficiency, and increased transparency.",
      ],
      correct: 1,
      explanation: "โครงสร้างขนาน (parallel structure) ต้องใช้รูปกริยาที่สอดคล้องกันทั้งหมด: reduce, improve, increase (base form ทั้งหมด)",
    },
    // ── Reading Comprehension — Passage 1 (Q66–70) ──────────
    {
      id: 66,
      question: "Read the following passage and answer Questions 66–70.\n\n\"Meritocratic recruitment in the civil service is often championed as a safeguard against nepotism and political patronage. By selecting candidates based on standardised examinations and objective criteria, governments aim to ensure that positions are filled by the most capable individuals rather than those with personal connections. Critics, however, argue that purely examination-based systems may inadvertently favour candidates from privileged backgrounds who have greater access to preparatory resources, thereby perpetuating a different form of inequality. Consequently, some scholars advocate for a hybrid approach that combines standardised testing with holistic assessments of candidates' backgrounds and potential.\"\n\nWhat is the main purpose of this passage?",
      choices: [
        "To argue that meritocratic recruitment should be abolished entirely.",
        "To examine both the benefits and potential drawbacks of meritocratic recruitment in the civil service.",
        "To prove that examination-based systems are always fair.",
        "To criticise candidates from privileged backgrounds.",
      ],
      correct: 1,
      explanation: "บทความนำเสนอทั้งข้อดี (ป้องกันระบบอุปถัมภ์) และข้อจำกัด (อาจเอื้อผู้มีทรัพยากรมากกว่า) ของระบบคัดเลือกตามคุณธรรม",
    },
    {
      id: 67,
      question: "According to the passage, what is one criticism of purely examination-based recruitment systems?",
      choices: [
        "They are too expensive to administer.",
        "They may favour candidates with greater access to preparatory resources.",
        "They take too long to complete.",
        "They are illegal in most countries.",
      ],
      correct: 1,
      explanation: "บทความระบุว่านักวิจารณ์มองว่าระบบนี้ 'may inadvertently favour candidates from privileged backgrounds who have greater access to preparatory resources'",
    },
    {
      id: 68,
      question: "The word \"nepotism\" in the passage most nearly means:",
      choices: [
        "The practice of hiring based on standardised tests",
        "The practice of favouring relatives or friends, especially in granting jobs",
        "The process of holistic assessment",
        "A type of government examination",
      ],
      correct: 1,
      explanation: "'Nepotism' หมายถึง การเล่นพรรคเล่นพวก การเอื้อประโยชน์ให้ญาติหรือคนใกล้ชิดในการแต่งตั้งตำแหน่ง",
    },
    {
      id: 69,
      question: "What solution do some scholars propose, according to the passage?",
      choices: [
        "Eliminating all forms of examination.",
        "A hybrid approach combining standardised testing with holistic assessment.",
        "Relying solely on personal connections.",
        "Increasing the difficulty of examinations.",
      ],
      correct: 1,
      explanation: "บทความระบุว่านักวิชาการบางส่วนสนับสนุน 'a hybrid approach that combines standardised testing with holistic assessments'",
    },
    {
      id: 70,
      question: "Which of the following best describes the structure of the passage?",
      choices: [
        "It presents a single viewpoint without any counterargument.",
        "It presents a concept, followed by a critique, and then a proposed compromise.",
        "It tells a chronological story.",
        "It compares two unrelated topics.",
      ],
      correct: 1,
      explanation: "บทความเริ่มด้วยการอธิบายแนวคิด (meritocratic recruitment) ตามด้วยข้อวิจารณ์ และปิดท้ายด้วยข้อเสนอทางออกแบบผสมผสาน",
    },
    // ── Reading Comprehension — Passage 2 (Q71–75) ──────────
    {
      id: 71,
      question: "Read the following passage and answer Questions 71–75.\n\n\"Whistleblower protection laws are designed to encourage individuals to report misconduct within organisations without fear of retaliation. In the public sector, such protections are particularly crucial, as officials who expose corruption or malfeasance often face significant professional and personal risks. However, the effectiveness of these laws hinges not only on their legal robustness but also on the extent to which they are enforced in practice. In many jurisdictions, whistleblowers who report wrongdoing still experience demotion, harassment, or termination, despite existing legal safeguards. This gap between legislation and enforcement undermines public trust and discourages future disclosures of wrongdoing.\"\n\nWhat is the central argument of this passage?",
      choices: [
        "Whistleblower protection laws are unnecessary.",
        "Legal protections for whistleblowers are only effective if properly enforced, and enforcement gaps undermine their purpose.",
        "Whistleblowers never face any risks.",
        "Public sector corruption does not exist.",
      ],
      correct: 1,
      explanation: "บทความเน้นว่ากฎหมายคุ้มครองผู้แจ้งเบาะแสจะได้ผลจริงต่อเมื่อมีการบังคับใช้อย่างจริงจัง หากไม่มีการบังคับใช้ ช่องว่างนี้จะบั่นทอนความไว้วางใจของประชาชน",
    },
    {
      id: 72,
      question: "According to the passage, what often happens to whistleblowers despite legal safeguards?",
      choices: [
        "They receive promotions and awards.",
        "They experience demotion, harassment, or termination.",
        "They are given additional legal training.",
        "They are transferred to better positions.",
      ],
      correct: 1,
      explanation: "บทความระบุว่า 'whistleblowers who report wrongdoing still experience demotion, harassment, or termination, despite existing legal safeguards'",
    },
    {
      id: 73,
      question: "The word \"malfeasance\" in the passage most nearly means:",
      choices: [
        "Excellent performance",
        "Wrongdoing or misconduct, especially by a public official",
        "A type of legal protection",
        "A financial bonus",
      ],
      correct: 1,
      explanation: "'Malfeasance' หมายถึง การประพฤติมิชอบหรือการกระทำผิดกฎหมาย โดยเฉพาะของเจ้าหน้าที่รัฐ",
    },
    {
      id: 74,
      question: "According to the passage, what undermines public trust?",
      choices: [
        "The existence of whistleblower protection laws.",
        "The gap between legislation and actual enforcement.",
        "Too many people reporting misconduct.",
        "The absence of corruption in government.",
      ],
      correct: 1,
      explanation: "บทความสรุปว่า 'This gap between legislation and enforcement undermines public trust and discourages future disclosures of wrongdoing'",
    },
    {
      id: 75,
      question: "The phrase \"hinges on\" in the passage means:",
      choices: ["Is completely unrelated to", "Depends critically on", "Is opposed to", "Occurs before"],
      correct: 1,
      explanation: "'Hinges on' เป็นสำนวน หมายถึง ขึ้นอยู่กับ หรือเป็นปัจจัยชี้ขาดที่สำคัญ",
    },
  ],
};

const section3: ExamSection = {
  id: "s3",
  title: "วิชาความรู้และลักษณะการเป็นข้าราชการที่ดี",
  shortTitle: "วิชาที่ 3",
  questionCount: 25,
  totalScore: 50,
  passingPercent: 60,
  timeRecommended: 45,
  questions: [
    // ── 1. พ.ร.บ.ระเบียบบริหารราชการแผ่นดิน ─────────────────
    {
      id: 76,
      question: "ตาม พ.ร.บ.ระเบียบบริหารราชการแผ่นดิน พ.ศ. 2534 หน่วยงานใดไม่จัดอยู่ในราชการบริหารส่วนกลาง",
      choices: ["กระทรวง", "ทบวง", "กรม", "องค์การบริหารส่วนจังหวัด"],
      correct: 3,
      explanation: "องค์การบริหารส่วนจังหวัด (อบจ.) เป็นราชการส่วนท้องถิ่น ไม่ใช่ราชการบริหารส่วนกลาง ซึ่งประกอบด้วยสำนักนายกรัฐมนตรี กระทรวง ทบวง และกรม",
    },
    {
      id: 77,
      question: "ในกรณีที่นายกรัฐมนตรีไม่อาจปฏิบัติราชการได้ ผู้ใดเป็นผู้รักษาราชการแทนตามลำดับที่กฎหมายกำหนด",
      choices: [
        "ปลัดสำนักนายกรัฐมนตรี",
        "รองนายกรัฐมนตรีหรือรัฐมนตรีตามลำดับที่คณะรัฐมนตรีกำหนด",
        "ประธานสภาผู้แทนราษฎร",
        "เลขาธิการคณะรัฐมนตรี",
      ],
      correct: 1,
      explanation: "คณะรัฐมนตรีจะมอบหมายให้รองนายกรัฐมนตรีหรือรัฐมนตรีคนใดคนหนึ่งเป็นผู้รักษาราชการแทนตามลำดับที่กำหนดไว้",
    },
    {
      id: 78,
      question: "\"การรักษาราชการแทน\" และ \"การปฏิบัติราชการแทน\" ตาม พ.ร.บ.ระเบียบบริหารราชการแผ่นดิน แตกต่างกันอย่างไร",
      choices: [
        "ไม่มีความแตกต่างกัน",
        "การรักษาราชการแทนใช้เมื่อตำแหน่งว่างหรือผู้ดำรงตำแหน่งไม่อาจปฏิบัติหน้าที่ได้ ส่วนการปฏิบัติราชการแทนเป็นการมอบอำนาจให้ผู้อื่นปฏิบัติหน้าที่แทนโดยผู้ดำรงตำแหน่งยังอยู่",
        "การรักษาราชการแทนใช้กับข้าราชการการเมืองเท่านั้น",
        "การปฏิบัติราชการแทนใช้เฉพาะกรณีฉุกเฉิน",
      ],
      correct: 1,
      explanation: "การรักษาราชการแทนเกิดเมื่อตำแหน่งว่างหรือผู้ดำรงตำแหน่งไม่อาจปฏิบัติหน้าที่ ส่วนการปฏิบัติราชการแทนคือการมอบอำนาจขณะที่ผู้ดำรงตำแหน่งยังปฏิบัติหน้าที่อยู่",
    },
    {
      id: 79,
      question: "จังหวัดหนึ่งมีการจัดตั้ง \"ส่วนราชการประจำจังหวัด\" ซึ่งเป็นหน่วยงานสังกัดกรมต่างๆ ในส่วนกลาง ผู้ใดเป็นผู้บังคับบัญชาสูงสุดของส่วนราชการประจำจังหวัดนั้นในทางปฏิบัติ",
      choices: [
        "อธิบดีกรมต้นสังกัดในส่วนกลางเท่านั้น",
        "ผู้ว่าราชการจังหวัด ในฐานะผู้บังคับบัญชาบรรดาข้าราชการฝ่ายบริหารในจังหวัด",
        "นายอำเภอในพื้นที่",
        "ปลัดกระทรวงมหาดไทย",
      ],
      correct: 1,
      explanation: "แม้ส่วนราชการประจำจังหวัดจะสังกัดกรมในส่วนกลาง แต่ผู้ว่าราชการจังหวัดมีอำนาจบังคับบัญชาบรรดาข้าราชการฝ่ายบริหารในจังหวัด ตาม พ.ร.บ.ระเบียบบริหารราชการแผ่นดิน",
    },
    {
      id: 80,
      question: "\"ทบวง\" ตาม พ.ร.บ.ระเบียบบริหารราชการแผ่นดิน มีฐานะเทียบเท่าหน่วยงานใด",
      choices: ["กรม", "กระทรวง", "สำนัก", "กอง"],
      correct: 1,
      explanation: "ทบวงมีฐานะเทียบเท่ากระทรวง แต่มีขนาดเล็กกว่าและอยู่ในสังกัดหรือขึ้นตรงต่อนายกรัฐมนตรีหรือกระทรวงใดกระทรวงหนึ่ง",
    },
    // ── 2. พ.ร.ฎ.ว่าด้วยหลักเกณฑ์และวิธีการบริหารกิจการบ้านเมืองที่ดี ──
    {
      id: 81,
      question: "ตาม พ.ร.ฎ.บริหารกิจการบ้านเมืองที่ดี ส่วนราชการต้องทบทวนภารกิจของตนทุกกี่ปี",
      choices: ["1 ปี", "3 ปี", "5 ปี", "ไม่มีกำหนด"],
      correct: 1,
      explanation: "ส่วนราชการต้องจัดให้มีการทบทวนภารกิจของตนทุก 3 ปี ว่ายังมีความจำเป็นหรือควรปรับปรุงเปลี่ยนแปลงหรือไม่",
    },
    {
      id: 82,
      question: "กรณีประชาชนยื่นคำร้องต่อส่วนราชการ หากเป็นเรื่องที่ไม่อยู่ในอำนาจหน้าที่ของหน่วยงานนั้น ส่วนราชการต้องดำเนินการอย่างไรตาม พ.ร.ฎ.บริหารกิจการบ้านเมืองที่ดี",
      choices: [
        "ปฏิเสธและคืนคำร้องให้ประชาชนไปยื่นเอง",
        "แนะนำให้ประชาชนไปยื่นต่อหน่วยงานที่ถูกต้อง หรือส่งเรื่องต่อให้หน่วยงานนั้นภายในเวลาที่กำหนด",
        "เก็บเรื่องไว้โดยไม่ต้องแจ้งประชาชน",
        "ยกเลิกคำร้องทันที",
      ],
      correct: 1,
      explanation: "หลักการอำนวยความสะดวกแก่ประชาชนกำหนดให้ส่วนราชการต้องแนะนำหรือส่งต่อเรื่องให้หน่วยงานที่ถูกต้องภายในระยะเวลาที่กำหนด ไม่ปล่อยให้ประชาชนต้องดำเนินการเอง",
    },
    {
      id: 83,
      question: "\"การบริหารกิจการบ้านเมืองที่ดี\" ตามนิยามใน พ.ร.ฎ. ฉบับนี้ ครอบคลุมการบริหารราชการขององค์กรใดบ้าง",
      choices: [
        "เฉพาะราชการส่วนกลางเท่านั้น",
        "ราชการส่วนกลาง ส่วนภูมิภาค และส่วนท้องถิ่น รวมถึงรัฐวิสาหกิจ",
        "เฉพาะรัฐวิสาหกิจ",
        "เฉพาะองค์กรอิสระตามรัฐธรรมนูญ",
      ],
      correct: 1,
      explanation: "พ.ร.ฎ.ฉบับนี้มีผลครอบคลุมการบริหารราชการทุกส่วน ทั้งส่วนกลาง ส่วนภูมิภาค ส่วนท้องถิ่น และรัฐวิสาหกิจ",
    },
    {
      id: 84,
      question: "เมื่อส่วนราชการใดดำเนินการปฏิบัติภารกิจใดสำเร็จตามเป้าหมาย ต้องดำเนินการอย่างไรตามหลักการประเมินผลใน พ.ร.ฎ.บริหารกิจการบ้านเมืองที่ดี",
      choices: [
        "ประกาศยกเลิกภารกิจนั้นทันที",
        "จัดให้มีการประเมินผลการปฏิบัติราชการอย่างสม่ำเสมอ และอาจให้บำเหน็จความชอบแก่ผู้เกี่ยวข้อง",
        "โอนงบประมาณไปยังหน่วยงานอื่นทันที",
        "ไม่ต้องดำเนินการใดๆ เพิ่มเติม",
      ],
      correct: 1,
      explanation: "พ.ร.ฎ.กำหนดให้มีการประเมินผลการปฏิบัติราชการอย่างสม่ำเสมอ และส่งเสริมให้มีบำเหน็จความชอบแก่ผู้ปฏิบัติงานที่ทำให้ภารกิจสำเร็จตามเป้าหมาย",
    },
    {
      id: 85,
      question: "หลักการ \"e-Government\" ที่ปรากฏในแนวทางการบริหารกิจการบ้านเมืองที่ดี มีเป้าหมายหลักเพื่ออะไร",
      choices: [
        "เพิ่มจำนวนเอกสารกระดาษ",
        "นำเทคโนโลยีสารสนเทศมาใช้เพื่อเพิ่มประสิทธิภาพและอำนวยความสะดวกแก่ประชาชน",
        "ลดจำนวนประชาชนที่มาติดต่อราชการโดยการปฏิเสธคำร้อง",
        "เพิ่มขั้นตอนการตรวจสอบเอกสาร",
      ],
      correct: 1,
      explanation: "e-Government มุ่งนำเทคโนโลยีสารสนเทศมาปรับปรุงกระบวนการทำงานให้มีประสิทธิภาพ รวดเร็ว และอำนวยความสะดวกแก่ประชาชนมากขึ้น",
    },
    // ── 3. พ.ร.บ.วิธีปฏิบัติราชการทางปกครอง ─────────────────
    {
      id: 86,
      question: "\"คำสั่งทางปกครอง\" ตาม พ.ร.บ.วิธีปฏิบัติราชการทางปกครอง หมายความรวมถึงข้อใด",
      choices: [
        "การออกกฎกระทรวงที่ใช้บังคับเป็นการทั่วไป",
        "การใช้อำนาจตามกฎหมายของเจ้าหน้าที่ที่มีผลเป็นการสร้างนิติสัมพันธ์กับบุคคลใดบุคคลหนึ่งเป็นการเฉพาะ",
        "การประชุมภายในของหน่วยงาน",
        "การเผยแพร่ข่าวสารทั่วไปของราชการ",
      ],
      correct: 1,
      explanation: "คำสั่งทางปกครองคือการใช้อำนาจของเจ้าหน้าที่ที่มีผลเฉพาะเจาะจงต่อบุคคลใดบุคคลหนึ่ง ต่างจากกฎซึ่งใช้บังคับเป็นการทั่วไป",
    },
    {
      id: 87,
      question: "กรณีเจ้าหน้าที่ออกคำสั่งทางปกครองโดยไม่ได้ให้คู่กรณีมีโอกาสชี้แจงข้อเท็จจริงก่อน คำสั่งนั้นมีผลอย่างไรตามหลักการที่กฎหมายกำหนด",
      choices: [
        "มีผลสมบูรณ์เสมอ",
        "อาจถือเป็นคำสั่งที่ไม่ชอบด้วยกฎหมายเนื่องจากขัดหลักการรับฟังคู่กรณี",
        "มีผลเฉพาะกรณีฉุกเฉิน",
        "ต้องรอให้ศาลปกครองพิจารณาก่อนจึงมีผล",
      ],
      correct: 1,
      explanation: "หลักการพื้นฐานของกฎหมายปกครองกำหนดให้คู่กรณีต้องมีโอกาสโต้แย้งและแสดงพยานหลักฐานก่อนมีคำสั่งที่กระทบสิทธิ หากไม่ปฏิบัติตามอาจถือเป็นคำสั่งที่ไม่ชอบด้วยกฎหมาย",
    },
    {
      id: 88,
      question: "การเพิกถอนคำสั่งทางปกครองที่ให้ประโยชน์แก่ผู้รับคำสั่งโดยชอบด้วยกฎหมาย เจ้าหน้าที่จะเพิกถอนได้ในกรณีใด",
      choices: [
        "เพิกถอนได้ทุกกรณีโดยไม่มีเงื่อนไข",
        "เพิกถอนได้ตามหลักเกณฑ์ที่กฎหมายกำหนด โดยต้องคำนึงถึงความเชื่อถือไว้วางใจของผู้รับประโยชน์โดยสุจริต",
        "ไม่สามารถเพิกถอนได้เลย",
        "เพิกถอนได้เฉพาะเมื่อมีคำสั่งศาลเท่านั้น",
      ],
      correct: 1,
      explanation: "การเพิกถอนคำสั่งทางปกครองที่ให้ประโยชน์ต้องพิจารณาถึงหลักความเชื่อถือไว้วางใจ (protection of legitimate expectation) ของผู้ได้รับประโยชน์โดยสุจริต ซึ่งกฎหมายวางหลักเกณฑ์ไว้เฉพาะ",
    },
    {
      id: 89,
      question: "ตาม พ.ร.บ.วิธีปฏิบัติราชการทางปกครอง คำสั่งทางปกครองที่ไม่ได้แจ้งสิทธิอุทธรณ์ไว้ ผลเป็นอย่างไรต่อระยะเวลาการอุทธรณ์",
      choices: [
        "ระยะเวลาอุทธรณ์ยังคงเป็น 15 วันตามปกติ",
        "ขยายระยะเวลาการอุทธรณ์เป็น 1 ปีนับแต่วันที่ได้รับคำสั่ง",
        "ผู้รับคำสั่งหมดสิทธิอุทธรณ์ทันที",
        "ต้องยื่นอุทธรณ์ภายใน 24 ชั่วโมง",
      ],
      correct: 1,
      explanation: "หากคำสั่งทางปกครองไม่แจ้งสิทธิและระยะเวลาอุทธรณ์ กฎหมายขยายระยะเวลาการใช้สิทธิอุทธรณ์ออกไปเป็น 1 ปีนับแต่วันที่ได้รับแจ้งคำสั่ง",
    },
    {
      id: 90,
      question: "หลักการ \"ความได้สัดส่วน\" (proportionality) ในกฎหมายวิธีปฏิบัติราชการทางปกครองหมายถึงข้อใด",
      choices: [
        "เจ้าหน้าที่สามารถใช้มาตรการใดก็ได้ตามที่ต้องการ",
        "มาตรการที่เจ้าหน้าที่เลือกใช้ต้องเหมาะสมและไม่เกินความจำเป็นเมื่อเทียบกับวัตถุประสงค์ที่ต้องการบรรลุ",
        "เจ้าหน้าที่ต้องใช้มาตรการที่รุนแรงที่สุดเสมอเพื่อความรวดเร็ว",
        "ไม่มีความเกี่ยวข้องกับการออกคำสั่งทางปกครอง",
      ],
      correct: 1,
      explanation: "หลักความได้สัดส่วนกำหนดให้มาตรการที่ใช้ต้องเหมาะสม จำเป็น และได้สัดส่วนกับวัตถุประสงค์ ไม่สร้างภาระเกินสมควรแก่ประชาชน",
    },
    // ── 4. ประมวลจริยธรรมข้าราชการ ────────────────────────────
    {
      id: 91,
      question: "ตามประมวลจริยธรรมข้าราชการพลเรือน พ.ศ. 2564 หากข้าราชการพบเห็นการกระทำที่อาจฝ่าฝืนจริยธรรมของผู้อื่น ควรปฏิบัติอย่างไร",
      choices: [
        "เพิกเฉยเพราะไม่ใช่หน้าที่โดยตรงของตน",
        "รายงานหรือแจ้งเบาะแสต่อผู้บังคับบัญชาหรือหน่วยงานที่เกี่ยวข้องตามช่องทางที่กำหนด",
        "เปิดเผยต่อสื่อมวลชนทันทีโดยไม่แจ้งหน่วยงานก่อน",
        "จัดการด้วยตนเองโดยไม่ต้องแจ้งใคร",
      ],
      correct: 1,
      explanation: "ประมวลจริยธรรมส่งเสริมให้ข้าราชการรายงานหรือแจ้งเบาะแสการกระทำที่ฝ่าฝืนจริยธรรมผ่านช่องทางที่หน่วยงานกำหนดไว้ เพื่อให้มีการตรวจสอบอย่างเป็นระบบ",
    },
    {
      id: 92,
      question: "\"จิตอาสาและมีจิตสำนึกที่ดี\" เป็นหนึ่งในมาตรฐานทางจริยธรรม 9 ประการ ข้อใดสะท้อนพฤติกรรมนี้ได้ชัดเจนที่สุด",
      choices: [
        "ปฏิเสธการทำงานนอกเวลาราชการทุกกรณี",
        "ให้บริการประชาชนด้วยความเต็มใจ อดทน และคำนึงถึงประโยชน์ของผู้รับบริการเป็นสำคัญ",
        "ทำงานเฉพาะที่ได้รับมอบหมายเป็นลายลักษณ์อักษรเท่านั้น",
        "เลือกให้บริการเฉพาะผู้ที่รู้จักเป็นการส่วนตัว",
      ],
      correct: 1,
      explanation: "จิตอาสาและจิตสำนึกที่ดีสะท้อนผ่านการให้บริการประชาชนด้วยความเต็มใจ อดทน และคำนึงถึงประโยชน์ของผู้รับบริการเป็นสำคัญ",
    },
    {
      id: 93,
      question: "กรณีข้าราชการมีคู่สมรสประกอบธุรกิจที่มีความเกี่ยวข้องโดยตรงกับหน้าที่ราชการของตน ควรปฏิบัติตามหลักจริยธรรมข้อใด",
      choices: [
        "ไม่ต้องเปิดเผยเพราะเป็นเรื่องส่วนตัวของคู่สมรส",
        "เปิดเผยความเกี่ยวข้องดังกล่าวต่อผู้บังคับบัญชาและถอนตัวจากการพิจารณาเรื่องที่อาจมีผลประโยชน์ทับซ้อน",
        "ให้คู่สมรสเปลี่ยนชื่อธุรกิจเพื่อหลีกเลี่ยงการตรวจสอบ",
        "ดำเนินการตามปกติโดยไม่ต้องแจ้งใคร",
      ],
      correct: 1,
      explanation: "หลักการป้องกันผลประโยชน์ทับซ้อนกำหนดให้ต้องเปิดเผยความเกี่ยวข้องและถอนตัวจากการพิจารณาเรื่องที่อาจเกิดผลประโยชน์ทับซ้อน",
    },
    {
      id: 94,
      question: "หากคณะกรรมการจริยธรรมประจำส่วนราชการวินิจฉัยว่าข้าราชการผู้หนึ่งฝ่าฝืนจริยธรรมอย่างร้ายแรง ผลที่ตามมาโดยหลักการคืออะไร",
      choices: [
        "ไม่มีผลใดๆ เพราะจริยธรรมไม่ใช่กฎหมาย",
        "อาจนำไปสู่กระบวนการทางวินัยตามกฎหมายว่าด้วยระเบียบข้าราชการพลเรือนต่อไป",
        "ต้องลาออกจากราชการทันทีโดยไม่มีกระบวนการใดๆ",
        "ถูกเพิกถอนสัญชาติไทย",
      ],
      correct: 1,
      explanation: "การฝ่าฝืนจริยธรรมอย่างร้ายแรงอาจเชื่อมโยงไปสู่การดำเนินการทางวินัยตามกฎหมายว่าด้วยระเบียบข้าราชการพลเรือนที่เกี่ยวข้องต่อไป",
    },
    {
      id: 95,
      question: "เหตุใดประมวลจริยธรรมข้าราชการพลเรือนจึงกำหนดให้มี \"คณะกรรมการจริยธรรมประจำส่วนราชการ\" แยกจากฝ่ายวินัยปกติ",
      choices: [
        "เพื่อให้มีองค์กรเฉพาะที่ส่งเสริม กำกับดูแล และให้คำปรึกษาด้านจริยธรรมโดยตรง แยกจากกระบวนการทางวินัยทั่วไป",
        "เพราะกฎหมายวินัยไม่มีผลบังคับใช้อีกต่อไป",
        "เพื่อลดภาระงานของฝ่ายบุคคล",
        "เพราะจริยธรรมมีความสำคัญน้อยกว่าวินัย",
      ],
      correct: 0,
      explanation: "คณะกรรมการจริยธรรมมีบทบาทเฉพาะด้านการส่งเสริม กำกับดูแล และให้คำปรึกษาเรื่องจริยธรรม ซึ่งต่างจากกระบวนการทางวินัยที่เน้นการลงโทษ",
    },
    // ── 5. กฎหมายอาญาความผิดต่อตำแหน่งหน้าที่ ───────────────
    {
      id: 96,
      question: "เจ้าพนักงานผู้มีหน้าที่ซื้อ ทำ จัดการ หรือรักษาทรัพย์ใด เบียดบังทรัพย์นั้นเป็นของตนโดยทุจริต มีความผิดตามประมวลกฎหมายอาญามาตราใด",
      choices: [
        "มาตรา 147 ฐานยักยอกทรัพย์โดยเจ้าพนักงาน",
        "มาตรา 149 ฐานรับสินบน",
        "มาตรา 151 ฐานเบียดบังที่ราชพัสดุ",
        "มาตรา 157 ฐานปฏิบัติหน้าที่โดยมิชอบ",
      ],
      correct: 0,
      explanation: "มาตรา 147 บัญญัติความผิดฐานเจ้าพนักงานเบียดบังทรัพย์ที่ตนมีหน้าที่ดูแลรักษาเป็นของตนหรือผู้อื่นโดยทุจริต เรียกว่าความผิดฐานยักยอกทรัพย์โดยเจ้าพนักงาน",
    },
    {
      id: 97,
      question: "ความผิดตามมาตรา 157 (ปฏิบัติหรือละเว้นการปฏิบัติหน้าที่โดยมิชอบ) กับมาตรา 149 (รับสินบน) แตกต่างกันในสาระสำคัญอย่างไร",
      choices: [
        "ไม่มีความแตกต่างกันเลย",
        "มาตรา 157 ไม่จำเป็นต้องมีการรับทรัพย์สินหรือประโยชน์ ขณะที่มาตรา 149 ต้องมีการเรียก รับ หรือยอมจะรับทรัพย์สินหรือประโยชน์เป็นองค์ประกอบ",
        "มาตรา 149 ใช้กับข้าราชการการเมืองเท่านั้น",
        "มาตรา 157 มีโทษเบากว่ามาตรา 149 เสมอ",
      ],
      correct: 1,
      explanation: "มาตรา 157 เอาผิดการปฏิบัติหรือละเว้นการปฏิบัติหน้าที่โดยมิชอบเพื่อให้เกิดความเสียหาย โดยไม่จำเป็นต้องมีการรับทรัพย์สิน ต่างจากมาตรา 149 ที่ต้องมีองค์ประกอบการเรียกรับทรัพย์สินหรือประโยชน์",
    },
    {
      id: 98,
      question: "ผู้ใดเสนอทรัพย์สินให้แก่เจ้าพนักงานเพื่อจูงใจให้กระทำการอันมิชอบด้วยหน้าที่ แม้เจ้าพนักงานจะปฏิเสธไม่รับ ผู้เสนอมีความผิดหรือไม่ตามประมวลกฎหมายอาญา",
      choices: [
        "ไม่มีความผิด เพราะเจ้าพนักงานไม่ได้รับ",
        "มีความผิดฐานให้สินบนตามมาตรา 144 แม้เจ้าพนักงานจะปฏิเสธไม่รับก็ตาม",
        "มีความผิดเฉพาะกรณีที่เจ้าพนักงานรับสินบนแล้วเท่านั้น",
        "เป็นเพียงความผิดทางแพ่งเท่านั้น",
      ],
      correct: 1,
      explanation: "มาตรา 144 บัญญัติให้ผู้ที่ให้ ขอให้ หรือรับว่าจะให้ทรัพย์สินหรือประโยชน์แก่เจ้าพนักงานเพื่อจูงใจให้กระทำการมิชอบ มีความผิดสำเร็จแล้ว แม้เจ้าพนักงานจะไม่รับก็ตาม",
    },
    {
      id: 99,
      question: "\"เจ้าพนักงานเรียกรับทรัพย์สินเพื่อไม่ดำเนินคดีกับผู้กระทำผิด\" เข้าข่ายความผิดฐานใดตามประมวลกฎหมายอาญา",
      choices: [
        "ฐานยักยอกทรัพย์ (มาตรา 147)",
        "ฐานรับสินบนเพื่อกระทำการหรือไม่กระทำการในตำแหน่ง (มาตรา 149)",
        "ฐานฉ้อโกงประชาชน",
        "ฐานทำร้ายร่างกาย",
      ],
      correct: 1,
      explanation: "การเรียกรับทรัพย์สินเพื่อแลกกับการไม่ดำเนินคดี ถือเป็นการไม่กระทำการในตำแหน่งเพื่อประโยชน์ตอบแทน เข้าข่ายความผิดฐานรับสินบนตามมาตรา 149",
    },
    {
      id: 100,
      question: "เหตุใดกฎหมายจึงกำหนดโทษความผิดต่อตำแหน่งหน้าที่ราชการไว้สูงกว่าความผิดลักษณะเดียวกันที่กระทำโดยบุคคลทั่วไป",
      choices: [
        "เพราะเจ้าพนักงานมีรายได้สูงกว่าบุคคลทั่วไป",
        "เพราะเจ้าพนักงานได้รับความไว้วางใจให้ใช้อำนาจรัฐ การกระทำผิดจึงกระทบต่อความเชื่อมั่นในระบบราชการและประโยชน์สาธารณะมากกว่า",
        "เพราะกฎหมายต้องการเก็บภาษีเพิ่มจากเจ้าพนักงาน",
        "ไม่มีเหตุผลพิเศษ เป็นเพียงธรรมเนียมปฏิบัติ",
      ],
      correct: 1,
      explanation: "เจ้าพนักงานได้รับมอบอำนาจและความไว้วางใจจากรัฐและประชาชนให้ปฏิบัติหน้าที่ การกระทำผิดจึงกระทบต่อความเชื่อมั่นในระบบราชการและผลประโยชน์สาธารณะในวงกว้างกว่าบุคคลทั่วไป กฎหมายจึงกำหนดโทษไว้สูงกว่า",
    },
  ],
};

export const KP_MOCK_2: MockExam = {
  id: "kp-mock-2",
  title: "ข้อสอบจำลอง ก.พ. ชุดที่ 2",
  totalTime: 180,
  xpReward: 2000,
  rankReward: "ผู้ผ่านด่าน ก.พ. ระดับ 2",
  sections: [section1, section2, section3],
};
