export type Course = {
  id: string;
  title: string;
  description: string;
  icon: string;
  icon3d?: string;
  color: string;
  totalLessons: number;
  xpReward: number;
  tag: string;
  category?: string;
  intro?: string;
};

export type Lesson = {
  id: string;
  courseId: string;
  title: string;
  order: number;
  xpReward: number;
  steps: Step[];
};

export type Step =
  | { type: "info"; content: string; title: string }
  | { type: "quiz"; question: string; choices: string[]; correct: number; explanation: string }
  | { type: "fill"; question: string; answer: string; hint: string };

export const COURSES: Course[] = [
  {
    id: "kp-general",
    title: "ความรู้ทั่วไป (ก.พ.)",
    description: "วิชาความสามารถทั่วไป ตรรกะ คณิตศาสตร์ และภาษาไทย สำหรับสอบ ก.พ.",
    icon: "📝",
    icon3d: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f4dd.png",
    color: "#0891b2",
    totalLessons: 8,
    xpReward: 720,
    tag: "ก.พ.",
    category: "สอบ ก.พ.",
    intro: `ระดับปริญญาตรี (ป.ตรี)
สำหรับผู้ที่ใช้วุฒิปริญญาตรีสมัครสอบ จะต้องทดสอบทั้งหมด 3 หมวดวิชาหลัก (รวม 100 ข้อ 200 คะแนน) โดยมีโครงสร้างและเกณฑ์การสอบผ่าน ดังนี้ครับ

1. วิชาความรู้ความสามารถทั่วไป (คณิตศาสตร์ & ภาษาไทย) | 50 ข้อ 100 คะแนน
คณิตศาสตร์ (การคิดคำนวณและเหตุผล): ข้อสอบจะเน้นการวิเคราะห์ที่ซับซ้อน เช่น อนุกรม, เงื่อนไขสัญลักษณ์, เงื่อนไขภาษา, คณิตศาสตร์ทั่วไป (ร้อยละ, สมการ, ข้อมูลตารางและกราฟ)
ภาษาไทย: การเรียงประโยค, การเลือกใช้คำ/กลุ่มคำให้ถูกต้อง, และการอ่านจับใจความสำคัญจากบทความสั้นและบทความยาว
เกณฑ์การสอบผ่าน: ต้องได้คะแนน 60% ขึ้นไป (คิดเป็น 60 คะแนนขึ้นไป)

2. วิชาภาษาอังกฤษ | 25 ข้อ 50 คะแนน
เนื้อหา: Conversation (บทสนทนา), Vocabulary (คำศัพท์ระดับทางการ-กึ่งทางการ), Grammar (หลักไวยากรณ์), และ Reading (การอ่านจับใจความบทความอังกฤษ)
เกณฑ์การสอบผ่าน: ต้องได้คะแนน 50% ขึ้นไป (คิดเป็น 25 คะแนนขึ้นไป)

3. วิชาความรู้และลักษณะการเป็นข้าราชการที่ดี (กฎหมาย) | 25 ข้อ 50 คะแนน
เนื้อหา: กฎหมายพื้นฐานของข้าราชการ ได้แก่ พ.ร.บ.ระเบียบบริหารราชการแผ่นดิน, พ.ร.ฎ.บ้านเมืองที่ดี, พ.ร.บ.วิธีปฏิบัติราชการทางปกครอง, ประมวลจริยธรรมข้าราชการ, และกฎหมายอาญาความผิดต่อตำแหน่งหน้าที่
เกณฑ์การสอบผ่าน: ต้องได้คะแนน 60% ขึ้นไป (คิดเป็น 30 คะแนนขึ้นไป)`,
  },
  {
    id: "kp-english",
    title: "ภาษาอังกฤษ (ก.พ.)",
    description: "ข้อสอบภาษาอังกฤษระดับ ก.พ. ไวยากรณ์ คำศัพท์ และการอ่านจับใจความ",
    icon: "🌐",
    icon3d: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f310.png",
    color: "#0e7490",
    totalLessons: 4,
    xpReward: 360,
    tag: "ก.พ.",
    category: "สอบ ก.พ.",
  },
  {
    id: "kp-law",
    title: "ความรู้และลักษณะการเป็นข้าราชการที่ดี",
    description: "กฎหมายพื้นฐานของข้าราชการ: ระเบียบบริหารราชการแผ่นดิน, บ้านเมืองที่ดี, วิธีปฏิบัติราชการทางปกครอง, จริยธรรม และความผิดต่อตำแหน่งหน้าที่",
    icon: "⚖️",
    icon3d: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/2696-fe0f.png",
    color: "#7c3aed",
    totalLessons: 5,
    xpReward: 450,
    tag: "ก.พ.",
    category: "สอบ ก.พ.",
  },
  {
    id: "dsi-2547",
    title: "การสอบสวนคดีพิเศษ",
    description: "พ.ร.บ. การสอบสวนคดีพิเศษ พ.ศ. 2547 อำนาจ หน้าที่ และกระบวนการ DSI",
    icon: "🔎",
    icon3d: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f50e.png",
    color: "#dc2626",
    totalLessons: 8,
    xpReward: 800,
    tag: "กฎหมายพิเศษ",
    category: "เจ้าหน้าที่คดีพิเศษ (DSI)",
  },
  {
    id: "dsi-criminal",
    title: "คดีพิเศษและกฎหมายที่เกี่ยวข้อง",
    description: "ประเภทคดีพิเศษ เขตอำนาจ และกฎหมายที่ DSI ใช้บังคับ",
    icon: "⚖️",
    icon3d: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/2696-fe0f.png",
    color: "#b91c1c",
    totalLessons: 6,
    xpReward: 600,
    tag: "กฎหมายพิเศษ",
    category: "เจ้าหน้าที่คดีพิเศษ (DSI)",
  },
  // ===== ภาษาอังกฤษ ม.ปลาย =====
  {
    id: "eng-grammar",
    title: "ไวยากรณ์และโครงสร้างประโยค",
    description: "Tenses, Conditionals, Passive Voice และ Reported Speech สำหรับระดับ ม.4–ม.6",
    icon: "📐",
    icon3d: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f4d0.png",
    color: "#2563eb",
    totalLessons: 4,
    xpReward: 360,
    tag: "ม.ปลาย",
    category: "ภาษาอังกฤษ ม.ปลาย",
    intro: `ไวยากรณ์และโครงสร้างประโยค (Grammar & Structures)\nระดับมัธยมปลาย ม.4 – ม.6\n\nเนื้อหาครอบคลุม\n• Tenses: Present Perfect, Past Perfect, Future forms\n• Conditionals (If-clauses): Type 1, 2, 3\n• Passive Voice: การเปลี่ยนประโยคจาก Active เป็น Passive\n• Reported Speech: การรายงานคำพูดทางตรงและทางอ้อม\n\nเหมาะสำหรับผู้ที่ต้องการเตรียมสอบ O-NET, PAT1 และสอบเข้ามหาวิทยาลัย`,
  },
  {
    id: "eng-reading",
    title: "การอ่านและการวิเคราะห์",
    description: "Reading Comprehension: Main Idea, Inference, Vocabulary in Context สำหรับระดับ ม.4–ม.6",
    icon: "📖",
    icon3d: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f4d6.png",
    color: "#059669",
    totalLessons: 4,
    xpReward: 360,
    tag: "ม.ปลาย",
    category: "ภาษาอังกฤษ ม.ปลาย",
    intro: `การอ่านและการวิเคราะห์ (Reading Comprehension)\nระดับมัธยมปลาย ม.4 – ม.6\n\nเนื้อหาครอบคลุม\n• การหาใจความหลัก (Main Idea & Topic Sentence)\n• การอ่านเพื่อตีความและอนุมาน (Inference)\n• การเดาความหมายคำศัพท์จากบริบท (Vocabulary in Context)\n• เทคนิค Skimming & Scanning`,
  },
  {
    id: "eng-vocab",
    title: "คำศัพท์และสำนวน",
    description: "Vocabulary & Idioms: Phrasal Verbs, สำนวนภาษาอังกฤษ และ Word Formation ระดับ ม.ปลาย",
    icon: "💬",
    icon3d: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f4ac.png",
    color: "#d97706",
    totalLessons: 4,
    xpReward: 360,
    tag: "ม.ปลาย",
    category: "ภาษาอังกฤษ ม.ปลาย",
    intro: `คำศัพท์และสำนวน (Vocabulary & Idioms)\nระดับมัธยมปลาย ม.4 – ม.6\n\nเนื้อหาครอบคลุม\n• Idioms ที่ใช้บ่อยในชีวิตประจำวันและในข้อสอบ\n• Phrasal Verbs (กริยาวลี) ที่ต้องรู้\n• Word Formation: prefix, suffix, การสร้างคำ\n• Academic Vocabulary สำหรับการสอบ`,
  },
  {
    id: "eng-conversation",
    title: "การสื่อสารและบทสนทนา",
    description: "Conversation & Speaking: สถานการณ์จริง การแสดงความคิดเห็น และภาษาทางการ-ไม่ทางการ ระดับ ม.ปลาย",
    icon: "🗣️",
    icon3d: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/1f5e3-fe0f.png",
    color: "#7c3aed",
    totalLessons: 4,
    xpReward: 360,
    tag: "ม.ปลาย",
    category: "ภาษาอังกฤษ ม.ปลาย",
    intro: `การสื่อสารและบทสนทนา (Conversation & Speaking)\nระดับมัธยมปลาย ม.4 – ม.6\n\nเนื้อหาครอบคลุม\n• การโต้ตอบในสถานการณ์ต่างๆ (Social Situations)\n• การขอร้อง เสนอ ปฏิเสธอย่างสุภาพ\n• การแสดงความคิดเห็นและโต้เถียง\n• ความแตกต่างระหว่างภาษาทางการและไม่ทางการ`,
  },
  {
    id: "eng-writing",
    title: "การเขียน",
    description: "Writing: Paragraph, Essay, Formal Letter และ Narrative Writing ระดับ ม.ปลาย",
    icon: "✏️",
    icon3d: "https://cdn.jsdelivr.net/npm/emoji-datasource-apple/img/apple/64/270f-fe0f.png",
    color: "#db2777",
    totalLessons: 4,
    xpReward: 360,
    tag: "ม.ปลาย",
    category: "ภาษาอังกฤษ ม.ปลาย",
    intro: `การเขียน (Writing)\nระดับมัธยมปลาย ม.4 – ม.6\n\nเนื้อหาครอบคลุม\n• การเขียนย่อหน้า (Paragraph Writing): Topic Sentence, Supporting Details, Conclusion\n• โครงสร้าง Essay (Introduction, Body, Conclusion)\n• จดหมายทางการ (Formal Letter)\n• การเขียนเรื่องเล่า (Narrative Writing)`,
  },
];

export const LESSONS: Lesson[] = [
  // ===== ความรู้ทั่วไป ก.พ. =====
  {
    id: "kpg-1",
    courseId: "kp-general",
    title: "อนุกรม (Number Series)",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "อนุกรมคืออะไร?",
        content: "อนุกรม คือ ชุดตัวเลขที่เรียงตามกฎเกณฑ์อย่างใดอย่างหนึ่ง หน้าที่ของเราคือหา 'ความสัมพันธ์' แล้วเติมตัวเลขถัดไป\n\n🔑 กฎที่พบบ่อย\n• บวก/ลบ ค่าคงที่ — เช่น 2, 5, 8, 11 (+3)\n• คูณ/หาร — เช่น 3, 6, 12, 24 (×2)\n• ผลต่างเพิ่มขึ้น — เช่น 1, 2, 4, 7, 11 (+1, +2, +3, +4)\n• สลับสองชุด — เช่น 1, 10, 2, 20, 3, 30\n\n💡 เทคนิค: ลองหาผลต่างของแต่ละคู่ก่อนเสมอ",
      },
      {
        type: "quiz",
        question: "2, 5, 8, 11, __ ตัวเลขถัดไปคือ?",
        choices: ["12", "13", "14", "15"],
        correct: 2,
        explanation: "เพิ่มทีละ 3 ทุกครั้ง (2→5→8→11) ดังนั้น 11 + 3 = 14",
      },
      {
        type: "quiz",
        question: "3, 6, 12, 24, __ ตัวเลขถัดไปคือ?",
        choices: ["36", "42", "48", "60"],
        correct: 2,
        explanation: "คูณ 2 ทุกครั้ง (3×2=6, 6×2=12, 12×2=24) ดังนั้น 24 × 2 = 48",
      },
      {
        type: "quiz",
        question: "1, 2, 4, 7, 11, __ ตัวเลขถัดไปคือ?",
        choices: ["14", "15", "16", "18"],
        correct: 2,
        explanation: "ผลต่างเพิ่มขึ้นทีละ 1 (+1, +2, +3, +4, +5) ดังนั้น 11 + 5 = 16",
      },
      {
        type: "fill",
        question: "1, 4, 9, 16, __ (กำลังสองของจำนวนนับ) ตัวเลขถัดไปคือ ___",
        answer: "25",
        hint: "1², 2², 3², 4², ... ตัวถัดไปคือ 5²",
      },
    ],
  },
  {
    id: "kpg-2",
    courseId: "kp-general",
    title: "เงื่อนไขสัญลักษณ์ (Symbol Logic)",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "เงื่อนไขสัญลักษณ์คืออะไร?",
        content: "โจทย์จะให้เงื่อนไขด้วยเครื่องหมาย เช่น A > B, B = C แล้วถามว่าข้อสรุปถูกหรือไม่\n\n🔑 ความหมายเครื่องหมาย\n• A > B = A มากกว่า B\n• A < B = A น้อยกว่า B\n• A ≥ B = A มากกว่าหรือเท่ากับ B\n• A = B = A เท่ากับ B\n\n💡 เทคนิค: เรียงทุกตัวให้อยู่ในแถวเดียว เช่น A > B = C ≥ D แล้วค่อยอ่านข้อสรุป ถ้าข้อสรุป 'แน่นอนเสมอ' = เป็นจริง ถ้า 'อาจจะ/บางครั้ง' = สรุปไม่ได้",
      },
      {
        type: "quiz",
        question: "ถ้า A > B และ B > C แล้วข้อใดถูกต้อง?",
        choices: ["A < C", "A = C", "A > C", "สรุปไม่ได้"],
        correct: 2,
        explanation: "A มากกว่า B และ B มากกว่า C ดังนั้น A ต้องมากกว่า C เสมอ (A > B > C)",
      },
      {
        type: "quiz",
        question: "ถ้า A = B, B ≥ C แล้ว 'A ≥ C' เป็นจริงหรือไม่?",
        choices: ["จริงเสมอ", "เท็จเสมอ", "สรุปไม่ได้", "A < C"],
        correct: 0,
        explanation: "A = B และ B ≥ C ดังนั้น A ≥ C เป็นจริงเสมอ (แทน A ด้วย B ได้)",
      },
      {
        type: "quiz",
        question: "ถ้า A > B, C > B แล้วเปรียบเทียบ A กับ C ได้หรือไม่?",
        choices: ["A > C", "A < C", "A = C", "สรุปไม่ได้"],
        correct: 3,
        explanation: "ทั้ง A และ C ต่างมากกว่า B แต่ไม่รู้ว่า A กับ C ตัวไหนมากกว่ากัน จึงสรุปไม่ได้",
      },
    ],
  },
  {
    id: "kpg-3",
    courseId: "kp-general",
    title: "เงื่อนไขภาษา (Verbal Logic)",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "เงื่อนไขภาษาคืออะไร?",
        content: "โจทย์ให้เงื่อนไขเป็นประโยค แล้วให้หาข้อสรุปที่ 'ต้องเป็นจริงเสมอ' ตามหลักตรรกะ\n\n🔑 หลักสำคัญ\n• 'ทุกคน...' → ใช้ได้กับสมาชิกทุกตัวในกลุ่ม\n• 'บางคน...' → อย่างน้อย 1 คน (ไม่ใช่ทั้งหมด)\n• ถ้า A เป็น B และ B เป็น C → A เป็น C\n\n⚠️ ระวังคำว่า 'ทุก' กับ 'บาง' — สรุปเกินจริงไม่ได้\n💡 อย่าเอาความรู้นอกโจทย์มาตัดสิน ใช้เฉพาะข้อมูลที่ให้",
      },
      {
        type: "quiz",
        question: "นกทุกตัวบินได้ · เพนกวินเป็นนก · ตามตรรกะของโจทย์ ข้อใดถูก?",
        choices: ["เพนกวินบินไม่ได้", "เพนกวินบินได้", "สรุปไม่ได้", "เพนกวินไม่ใช่นก"],
        correct: 1,
        explanation: "ตามเงื่อนไขที่ให้ (นกทุกตัวบินได้ + เพนกวินเป็นนก) ต้องสรุปว่าเพนกวินบินได้ — แม้ความจริงจะต่าง แต่ข้อสอบตรรกะใช้เฉพาะเงื่อนไขที่กำหนด",
      },
      {
        type: "quiz",
        question: "นักเรียนบางคนเล่นกีฬา · ข้อใดสรุปได้แน่นอน?",
        choices: ["นักเรียนทุกคนเล่นกีฬา", "มีนักเรียนอย่างน้อย 1 คนเล่นกีฬา", "ไม่มีนักเรียนเล่นกีฬา", "นักเรียนครึ่งหนึ่งเล่นกีฬา"],
        correct: 1,
        explanation: "'บางคน' หมายถึงอย่างน้อย 1 คน จะสรุปว่า 'ทุกคน' หรือ 'ครึ่งหนึ่ง' ไม่ได้",
      },
      {
        type: "quiz",
        question: "ถ้า A เป็นสมาชิกชมรม และสมาชิกชมรมทุกคนต้องจ่ายค่าสมาชิก ข้อใดถูก?",
        choices: ["A ไม่ต้องจ่าย", "A ต้องจ่ายค่าสมาชิก", "สรุปไม่ได้", "A เป็นประธาน"],
        correct: 1,
        explanation: "A เป็นสมาชิก และสมาชิกทุกคนต้องจ่าย ดังนั้น A ต้องจ่ายค่าสมาชิก",
      },
    ],
  },
  {
    id: "kpg-4",
    courseId: "kp-general",
    title: "ร้อยละและสมการ",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "ร้อยละ (เปอร์เซ็นต์)",
        content: "ร้อยละ คือ การเทียบเป็นส่วนของ 100\n\n🔑 สูตรสำคัญ\n• X% ของ N = (X ÷ 100) × N\n• หาว่า A เป็นกี่ % ของ B = (A ÷ B) × 100\n\n📌 ตัวอย่าง\n• 20% ของ 150 = (20÷100) × 150 = 30\n• 30 เป็นกี่ % ของ 120 = (30÷120) × 100 = 25%\n\n💡 กำไร/ขาดทุน คิดจาก 'ราคาทุน' เสมอ",
      },
      {
        type: "quiz",
        question: "25% ของ 80 เท่ากับเท่าไร?",
        choices: ["15", "20", "25", "32"],
        correct: 1,
        explanation: "(25 ÷ 100) × 80 = 0.25 × 80 = 20",
      },
      {
        type: "quiz",
        question: "ของราคาทุน 200 บาท ขาย 250 บาท ได้กำไรกี่เปอร์เซ็นต์?",
        choices: ["20%", "25%", "50%", "10%"],
        correct: 1,
        explanation: "กำไร = 250 − 200 = 50 บาท คิดเป็น (50 ÷ 200) × 100 = 25% (คิดจากราคาทุน)",
      },
      {
        type: "fill",
        question: "ถ้า 3x = 21 แล้ว x = ___",
        answer: "7",
        hint: "เอา 21 หารด้วย 3",
      },
      {
        type: "quiz",
        question: "ถ้า x + 8 = 20 แล้ว x มีค่าเท่าไร?",
        choices: ["10", "12", "14", "28"],
        correct: 1,
        explanation: "ย้าย 8 ไปอีกข้าง: x = 20 − 8 = 12",
      },
    ],
  },
  {
    id: "kpg-5",
    courseId: "kp-general",
    title: "การอ่านตารางข้อมูลและกราฟ",
    order: 5,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การวิเคราะห์ตารางและกราฟ",
        content: "ข้อสอบจะให้ตาราง/กราฟ แล้วถามให้คำนวณหรือเปรียบเทียบ\n\n🔑 ขั้นตอน\n1. อ่านหัวตาราง/แกนกราฟให้เข้าใจก่อนว่าหน่วยคืออะไร\n2. ดูว่าโจทย์ถามค่าไหน — ผลรวม, ผลต่าง, ค่าเฉลี่ย, หรือ %\n3. ค่อยๆ ดึงตัวเลขมาคำนวณ อย่ารีบ\n\n💡 ค่าเฉลี่ย = ผลรวมทั้งหมด ÷ จำนวนข้อมูล",
      },
      {
        type: "quiz",
        question: "ยอดขาย 4 เดือน: 100, 150, 200, 150 (พันบาท) ยอดขายเฉลี่ยต่อเดือนเท่าไร?",
        choices: ["140", "150", "160", "175"],
        correct: 1,
        explanation: "ผลรวม = 100+150+200+150 = 600 ÷ 4 เดือน = 150 (พันบาท)",
      },
      {
        type: "quiz",
        question: "จากข้อมูลข้างต้น เดือนที่ยอดขายสูงสุดมากกว่าเดือนต่ำสุดอยู่เท่าไร?",
        choices: ["50", "100", "150", "200"],
        correct: 1,
        explanation: "สูงสุด = 200, ต่ำสุด = 100 ผลต่าง = 200 − 100 = 100 (พันบาท)",
      },
      {
        type: "quiz",
        question: "ถ้าค่าใช้จ่ายรวม 500 บาท แบ่งเป็นอาหาร 40% เป็นเงินเท่าไร?",
        choices: ["150", "180", "200", "250"],
        correct: 2,
        explanation: "40% ของ 500 = (40÷100) × 500 = 200 บาท",
      },
    ],
  },
  {
    id: "kpg-6",
    courseId: "kp-general",
    title: "ภาษาไทย: การเรียงประโยค",
    order: 6,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "หลักการเรียงประโยค",
        content: "โจทย์ให้ข้อความสลับกันมา ให้เรียงเป็นประโยค/ย่อหน้าที่ถูกต้อง\n\n🔑 หลักสังเกต\n• ประโยคแรกมักเป็น 'ประธาน' หรือเกริ่นนำหัวเรื่อง\n• คำเชื่อม เช่น 'จึง, ดังนั้น, เพราะ, แต่' บอกลำดับเหตุ-ผล\n• คำสรรพนาม 'มัน, เขา, สิ่งนี้' ต้องมีคำที่อ้างถึงมาก่อน\n• ลงท้ายด้วยบทสรุป/ผลลัพธ์\n\n💡 อ่านทุกชิ้นก่อน แล้วหา 'จุดเริ่ม' ที่ไม่ต้องพึ่งข้อความอื่น",
      },
      {
        type: "quiz",
        question: "เรียงประโยค: (1) จึงควรออกกำลังกาย (2) การมีสุขภาพดีเป็นสิ่งสำคัญ (3) เพราะช่วยให้ร่างกายแข็งแรง ลำดับที่ถูกคือ?",
        choices: ["1-2-3", "2-1-3", "2-3-1", "3-2-1"],
        correct: 1,
        explanation: "เริ่มที่ประเด็นหลัก (2) การมีสุขภาพดีสำคัญ → (1) จึงควรออกกำลังกาย → (3) เพราะช่วยให้แข็งแรง อ่านได้ลื่นที่สุด",
      },
      {
        type: "quiz",
        question: "คำใดมักเป็นตัวบอกว่าเป็น 'ผลลัพธ์/ข้อสรุป' ของประโยค?",
        choices: ["เพราะ", "ดังนั้น", "เนื่องจาก", "ถ้า"],
        correct: 1,
        explanation: "'ดังนั้น' นำหน้าข้อสรุป/ผลที่ตามมา ส่วน 'เพราะ/เนื่องจาก/ถ้า' นำหน้าเหตุหรือเงื่อนไข",
      },
      {
        type: "quiz",
        question: "ประโยคที่ขึ้นต้นด้วย 'มันจึงพังลง' มีปัญหาอะไรถ้าวางเป็นประโยคแรก?",
        choices: ["ยาวเกินไป", "ไม่มีคำที่ 'มัน' อ้างถึง", "ใช้คำผิด", "ไม่มีปัญหา"],
        correct: 1,
        explanation: "'มัน' เป็นสรรพนามต้องมีคำนามที่อ้างถึงมาก่อน จึงวางเป็นประโยคแรกไม่ได้",
      },
    ],
  },
  {
    id: "kpg-7",
    courseId: "kp-general",
    title: "ภาษาไทย: การเลือกใช้คำ",
    order: 7,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การเลือกใช้คำให้ถูกต้อง",
        content: "ข้อสอบวัดการเลือกคำ/กลุ่มคำที่เหมาะกับบริบทและถูกหลักภาษา\n\n🔑 จุดที่ออกบ่อย\n• คำที่สะกดคล้ายกันแต่ความหมายต่าง เช่น สังเกต/สังเกตุ (ที่ถูกคือ 'สังเกต')\n• การใช้ลักษณนามให้ตรง เช่น ปากกา 1 'ด้าม', พระ 1 'รูป'\n• คำราชาศัพท์\n• คำเชื่อมที่เหมาะกับบริบท\n\n💡 อ่านทั้งประโยค แล้วลองแทนแต่ละตัวเลือกดูว่าอันไหนกลมกลืนที่สุด",
      },
      {
        type: "quiz",
        question: "ข้อใดสะกดถูกต้อง?",
        choices: ["สังเกตุ", "สังเกต", "สังเกร", "สังเกตร"],
        correct: 1,
        explanation: "คำที่ถูกต้องคือ 'สังเกต' (ไม่มีสระอุ)",
      },
      {
        type: "quiz",
        question: "ลักษณนามของ 'พระสงฆ์' คือข้อใด?",
        choices: ["องค์", "รูป", "ตน", "คน"],
        correct: 1,
        explanation: "พระสงฆ์ใช้ลักษณนามว่า 'รูป' เช่น พระ 5 รูป",
      },
      {
        type: "quiz",
        question: "เลือกคำเติมช่องว่าง: 'เขาขยันมาก ___ สอบได้ที่หนึ่ง'",
        choices: ["แต่", "จึง", "หรือ", "ถ้า"],
        correct: 1,
        explanation: "เป็นเหตุ-ผล (ขยัน → สอบได้ที่หนึ่ง) จึงใช้คำเชื่อม 'จึง'",
      },
      {
        type: "fill",
        question: "ลักษณนามของ 'ปากกา' คือ ___",
        answer: "ด้าม",
        hint: "ปากกา 2 ___",
      },
    ],
  },
  {
    id: "kpg-8",
    courseId: "kp-general",
    title: "ภาษาไทย: การอ่านจับใจความ",
    order: 8,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การอ่านจับใจความสำคัญ",
        content: "วัดความสามารถสรุป 'ใจความหลัก' ของบทความ และตีความเจตนาผู้เขียน\n\n🔑 เทคนิค\n• ใจความหลัก = เรื่องที่ผู้เขียนต้องการสื่อมากที่สุด มักอยู่ประโยคแรกหรือสุดท้ายของย่อหน้า\n• อ่านคำถามก่อน แล้วค่อยกวาดหาคำตอบในบทความ\n• ระวังตัวเลือกที่ 'จริงแต่เป็นรายละเอียดย่อย' ไม่ใช่ใจความหลัก\n\n💡 ถามตัวเองว่า 'ถ้าให้ตั้งชื่อเรื่องนี้ จะตั้งว่าอะไร'",
      },
      {
        type: "info",
        title: "บทความตัวอย่าง",
        content: "อ่านบทความนี้แล้วตอบคำถามถัดไป:\n\n\"การนอนหลับให้เพียงพอมีความสำคัญต่อสุขภาพอย่างมาก ผู้ที่นอนน้อยกว่า 6 ชั่วโมงต่อคืนเป็นประจำ มีความเสี่ยงต่อโรคหัวใจและความจำเสื่อมสูงขึ้น นอกจากนี้ยังส่งผลต่ออารมณ์และประสิทธิภาพการทำงานในแต่ละวันอีกด้วย\"",
      },
      {
        type: "quiz",
        question: "ใจความหลักของบทความข้างต้นคือข้อใด?",
        choices: ["โรคหัวใจรักษาไม่ได้", "การนอนหลับเพียงพอสำคัญต่อสุขภาพ", "คนทำงานต้องตื่นเช้า", "ความจำเสื่อมเกิดในผู้สูงอายุ"],
        correct: 1,
        explanation: "ทั้งบทความพูดถึงความสำคัญของการนอนหลับต่อสุขภาพ ตัวเลือกอื่นเป็นรายละเอียดย่อยหรือไม่ได้กล่าวถึง",
      },
      {
        type: "quiz",
        question: "ตามบทความ การนอนน้อยส่งผลต่อข้อใด 'ไม่ถูกต้อง'?",
        choices: ["เสี่ยงโรคหัวใจ", "ความจำเสื่อม", "อารมณ์และการทำงาน", "ทำให้ตัวสูงขึ้น"],
        correct: 3,
        explanation: "บทความไม่ได้กล่าวถึงความสูงเลย ส่วนข้ออื่นมีระบุไว้ในบทความ",
      },
    ],
  },
  // ===== ภาษาอังกฤษ ก.พ. =====
  {
    id: "kpe-1",
    courseId: "kp-english",
    title: "Conversation (บทสนทนา)",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การสนทนาในข้อสอบ ก.พ.",
        content: "ข้อสอบจะให้บทสนทนาแล้วเติมคำพูดที่เหมาะกับสถานการณ์ เน้นความสุภาพและบริบท\n\n🔑 สำนวนที่ออกบ่อย\n• การทักทาย: How do you do? / Nice to meet you\n• การขอร้องสุภาพ: Could you...? / Would you mind...?\n• การเสนอความช่วยเหลือ: May I help you? / Shall I...?\n• การตอบรับ/ปฏิเสธ: I'd love to / I'm afraid I can't\n\n💡 เลือกคำตอบที่ 'สุภาพและเข้ากับบริบท' ที่สุด",
      },
      {
        type: "quiz",
        question: "A: \"Thank you for your help.\"  B: \"______\"",
        choices: ["No problem, you're welcome.", "Yes, I am.", "Here you are.", "I don't think so."],
        correct: 0,
        explanation: "เมื่อมีคนขอบคุณ การตอบที่เหมาะคือ \"You're welcome / No problem\"",
      },
      {
        type: "quiz",
        question: "เลือกคำขอร้องที่สุภาพที่สุด: \"______ open the window?\"",
        choices: ["Open you", "Could you please", "You open", "Do open"],
        correct: 1,
        explanation: "\"Could you please...\" เป็นรูปขอร้องที่สุภาพ ส่วนตัวเลือกอื่นไม่ถูกหลักหรือไม่สุภาพ",
      },
      {
        type: "quiz",
        question: "A: \"Would you like some coffee?\"  B: \"______\"",
        choices: ["Yes, I would. Thank you.", "Yes, I do.", "No, I am not.", "Here it is."],
        correct: 0,
        explanation: "คำถาม \"Would you like...?\" ตอบรับด้วย \"Yes, I would\" (ไม่ใช่ Yes, I do)",
      },
    ],
  },
  {
    id: "kpe-2",
    courseId: "kp-english",
    title: "Vocabulary (คำศัพท์)",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "คำศัพท์ระดับทางการ",
        content: "ข้อสอบวัดคำศัพท์ระดับทางการ-กึ่งทางการ และคำที่มีความหมายเหมือน/ตรงข้าม\n\n🔑 เทคนิค\n• ดู 'รากศัพท์' (prefix/suffix) ช่วยเดาความหมาย เช่น un- = ไม่, -able = สามารถ\n• อ่านทั้งประโยคหา 'บริบท' ช่วยเดาคำที่ไม่รู้\n• ระวังคำที่หน้าตาคล้ายแต่ความหมายต่าง\n\n💡 จำคำศัพท์เป็น 'กลุ่มความหมาย' จะจำง่ายกว่าจำทีละคำ",
      },
      {
        type: "quiz",
        question: "คำใดมีความหมายใกล้เคียงกับ 'increase' มากที่สุด?",
        choices: ["reduce", "rise", "stop", "keep"],
        correct: 1,
        explanation: "'increase' = เพิ่มขึ้น มีความหมายใกล้กับ 'rise' (ขึ้น) ส่วน reduce = ลด",
      },
      {
        type: "quiz",
        question: "คำตรงข้ามของ 'ancient' คือข้อใด?",
        choices: ["old", "modern", "large", "famous"],
        correct: 1,
        explanation: "'ancient' = โบราณ ตรงข้ามกับ 'modern' = ทันสมัย",
      },
      {
        type: "quiz",
        question: "เลือกคำเติมประโยค: \"The manager will ______ the new policy next week.\"",
        choices: ["announce", "announcement", "announced", "announcing"],
        correct: 0,
        explanation: "หลัง will ต้องเป็นกริยาช่อง 1 (announce) แปลว่า ประกาศ",
      },
      {
        type: "fill",
        question: "เติมคำตรงข้ามของ 'success' (ความสำเร็จ): f______ (ความล้มเหลว)",
        answer: "failure",
        hint: "ขึ้นต้นด้วย fai-",
      },
    ],
  },
  {
    id: "kpe-3",
    courseId: "kp-english",
    title: "Grammar (หลักไวยากรณ์)",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "ไวยากรณ์ที่ออกสอบบ่อย",
        content: "เน้น Tenses, Subject-Verb Agreement, Parts of Speech และคำเชื่อม\n\n🔑 จุดสำคัญ\n• ประธานเอกพจน์ + กริยาเติม s (He works)\n• Present Perfect: have/has + V3 (ใช้กับ already, yet, since, for)\n• Past Simple: V2 ใช้กับเวลาในอดีตที่ชัดเจน (yesterday, ago)\n• คำเชื่อม: because (เหตุ), although (แม้ว่า), so (ดังนั้น)\n\n💡 ดู 'คำบอกเวลา' ในประโยคช่วยเลือก Tense",
      },
      {
        type: "quiz",
        question: "เลือกข้อที่ถูกต้อง: \"She ______ to school every day.\"",
        choices: ["go", "goes", "going", "gone"],
        correct: 1,
        explanation: "ประธาน She (เอกพจน์) + every day (ปัจจุบัน) → กริยาเติม s = goes",
      },
      {
        type: "quiz",
        question: "\"I ______ my homework yesterday.\"",
        choices: ["finish", "finishes", "finished", "finishing"],
        correct: 2,
        explanation: "yesterday = อดีต ต้องใช้ Past Simple (V2) = finished",
      },
      {
        type: "quiz",
        question: "\"They have ______ in Bangkok since 2010.\"",
        choices: ["live", "lived", "living", "lives"],
        correct: 1,
        explanation: "have + V3 (Present Perfect) ใช้กับ since = have lived",
      },
      {
        type: "quiz",
        question: "เลือกคำเชื่อม: \"He passed the exam ______ he studied hard.\"",
        choices: ["although", "because", "but", "or"],
        correct: 1,
        explanation: "เป็นเหตุ-ผล (สอบผ่านเพราะตั้งใจเรียน) ใช้ 'because'",
      },
    ],
  },
  {
    id: "kpe-4",
    courseId: "kp-english",
    title: "Reading (การอ่านจับใจความ)",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "เทคนิคการอ่านจับใจความ",
        content: "ข้อสอบให้บทความ/อีเมลภาษาอังกฤษ แล้วถามใจความหลักและรายละเอียด\n\n🔑 เทคนิค\n• อ่านคำถามก่อน แล้วค่อยกวาดหาคำตอบในบทความ (scanning)\n• ใจความหลัก (main idea) มักอยู่ประโยคแรกหรือสุดท้าย\n• คำถาม detail ให้หาคำที่ตรงกับโจทย์ในบทความ\n• ไม่ต้องแปลทุกคำ จับ keyword พอ\n\n💡 ตัวเลือกที่ 'จริงแต่เป็นรายละเอียดย่อย' ไม่ใช่ใจความหลัก",
      },
      {
        type: "info",
        title: "Reading Passage",
        content: "อ่านบทความนี้แล้วตอบคำถามถัดไป:\n\n\"Regular exercise is essential for good health. It strengthens the heart, improves mood, and helps control weight. Experts recommend at least 30 minutes of physical activity each day. Even a short walk can make a big difference.\"",
      },
      {
        type: "quiz",
        question: "What is the main idea of the passage?",
        choices: ["Walking is boring", "Exercise is important for health", "Doctors are expensive", "Weight is not important"],
        correct: 1,
        explanation: "ทั้งบทความพูดถึงความสำคัญของการออกกำลังกายต่อสุขภาพ (Exercise is essential for good health)",
      },
      {
        type: "quiz",
        question: "How many minutes of activity do experts recommend per day?",
        choices: ["10 minutes", "20 minutes", "30 minutes", "60 minutes"],
        correct: 2,
        explanation: "บทความระบุชัดว่า \"at least 30 minutes of physical activity each day\"",
      },
      {
        type: "quiz",
        question: "According to the passage, exercise does NOT do which of the following?",
        choices: ["Strengthen the heart", "Improve mood", "Control weight", "Increase height"],
        correct: 3,
        explanation: "บทความกล่าวถึงหัวใจ อารมณ์ และน้ำหนัก แต่ไม่ได้พูดถึงความสูง",
      },
    ],
  },
  // ===== ความรู้และลักษณะการเป็นข้าราชการที่ดี (ก.พ.) =====
  {
    id: "kpl-1",
    courseId: "kp-law",
    title: "พ.ร.บ. ระเบียบบริหารราชการแผ่นดิน",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "ระเบียบบริหารราชการแผ่นดิน",
        content: "พ.ร.บ. ระเบียบบริหารราชการแผ่นดิน พ.ศ. 2534 วางโครงสร้างการบริหารราชการของไทย\n\n🔑 แบ่งการบริหารเป็น 3 ส่วน\n• ส่วนกลาง — กระทรวง ทบวง กรม\n• ส่วนภูมิภาค — จังหวัด อำเภอ\n• ส่วนท้องถิ่น — ตามมาตรา 70 (ดูบทถัดไป)\n\n📌 หลักการสำคัญ: การแบ่งอำนาจหน้าที่ การกระจายอำนาจ และการรักษาประโยชน์ของประชาชน",
      },
      {
        type: "info",
        title: "มาตรา 70 — ราชการส่วนท้องถิ่น",
        content: "มาตรา 70 ให้จัดระเบียบบริหารราชการส่วนท้องถิ่น ดังนี้\n\n(1) องค์การบริหารส่วนจังหวัด (อบจ.)\n(2) เทศบาล\n(3) สุขาภิบาล\n(4) ราชการส่วนท้องถิ่นอื่นตามที่มีกฎหมายกำหนด\n\n⚠️ ข้อควรจำ (สำหรับสอบ): ให้ตอบตามตัวบทมาตรา 70 ข้างต้น — ตามมาตรานี้ 'ไม่มี' องค์การบริหารส่วนตำบล (อบต.) ระบุไว้โดยตรง (อบต. จัดตั้งตามกฎหมายอื่น จึงนับเป็นข้อ (4) ราชการส่วนท้องถิ่นอื่นตามที่มีกฎหมายกำหนด)\n\n📝 หมายเหตุ (ความจริงปัจจุบัน): 'สุขาภิบาล' ถูกยกเลิกและเปลี่ยนฐานะเป็นเทศบาลตำบลทั้งหมดตั้งแต่ พ.ศ. 2542 จึงไม่มีสุขาภิบาลเหลืออยู่จริงในปัจจุบัน — แต่ในข้อสอบที่ถามตามตัวบท ยังต้องตอบตามที่มาตรา 70 เขียนไว้",
      },
      {
        type: "quiz",
        question: "การบริหารราชการแผ่นดินของไทยแบ่งออกเป็นกี่ส่วน?",
        choices: ["2 ส่วน", "3 ส่วน", "4 ส่วน", "5 ส่วน"],
        correct: 1,
        explanation: "แบ่งเป็น 3 ส่วน คือ ส่วนกลาง ส่วนภูมิภาค และส่วนท้องถิ่น",
      },
      {
        type: "quiz",
        question: "ข้อใดเป็นราชการบริหารส่วนภูมิภาค?",
        choices: ["กระทรวง", "กรม", "จังหวัดและอำเภอ", "เทศบาล"],
        correct: 2,
        explanation: "ส่วนภูมิภาคคือ จังหวัดและอำเภอ ส่วนกระทรวง/กรมเป็นส่วนกลาง และเทศบาลเป็นส่วนท้องถิ่น",
      },
      {
        type: "quiz",
        question: "ตามมาตรา 70 ข้อใด 'ไม่' ได้ระบุเป็นราชการส่วนท้องถิ่นไว้โดยตรง?",
        choices: ["องค์การบริหารส่วนจังหวัด", "เทศบาล", "สุขาภิบาล", "องค์การบริหารส่วนตำบล (อบต.)"],
        correct: 3,
        explanation: "มาตรา 70 ระบุ (1) อบจ. (2) เทศบาล (3) สุขาภิบาล (4) ราชการส่วนท้องถิ่นอื่นตามกฎหมาย — ไม่มี อบต. ระบุไว้โดยตรง (อบต. มาจากกฎหมายอื่น จึงอยู่ในข้อ 4)",
      },
      {
        type: "quiz",
        question: "ราชการส่วนท้องถิ่นตามมาตรา 70 ข้อ (4) หมายถึงข้อใด?",
        choices: ["กรมการปกครอง", "ราชการส่วนท้องถิ่นอื่นตามที่มีกฎหมายกำหนด", "อำเภอ", "กระทรวงมหาดไทย"],
        correct: 1,
        explanation: "ข้อ (4) คือ 'ราชการส่วนท้องถิ่นอื่นตามที่มีกฎหมายกำหนด' ซึ่งครอบคลุม อบต. กทม. และเมืองพัทยา",
      },
    ],
  },
  {
    id: "kpl-2",
    courseId: "kp-law",
    title: "พ.ร.ฎ. การบริหารกิจการบ้านเมืองที่ดี",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การบริหารกิจการบ้านเมืองที่ดี",
        content: "พระราชกฤษฎีกาว่าด้วยหลักเกณฑ์และวิธีการบริหารกิจการบ้านเมืองที่ดี พ.ศ. 2546 (Good Governance)\n\n🔑 เป้าหมาย 7 ข้อ เช่น\n• เกิดประโยชน์สุขของประชาชน\n• เกิดผลสัมฤทธิ์ต่อภารกิจของรัฐ\n• มีประสิทธิภาพและคุ้มค่า\n• ลดขั้นตอนการปฏิบัติงาน\n• ประชาชนได้รับความสะดวกและตอบสนองความต้องการ\n\n📌 หัวใจ: ราชการต้องทำเพื่อประชาชน โปร่งใส คุ้มค่า และรวดเร็ว",
      },
      {
        type: "quiz",
        question: "พ.ร.ฎ. บ้านเมืองที่ดี ประกาศใช้เมื่อ พ.ศ. ใด?",
        choices: ["พ.ศ. 2534", "พ.ศ. 2540", "พ.ศ. 2546", "พ.ศ. 2550"],
        correct: 2,
        explanation: "พระราชกฤษฎีกาว่าด้วยหลักเกณฑ์และวิธีการบริหารกิจการบ้านเมืองที่ดี ประกาศใช้ พ.ศ. 2546",
      },
      {
        type: "quiz",
        question: "ข้อใด 'ไม่ใช่' เป้าหมายของการบริหารกิจการบ้านเมืองที่ดี?",
        choices: ["เกิดประโยชน์สุขของประชาชน", "มีประสิทธิภาพและคุ้มค่า", "เพิ่มขั้นตอนการทำงานให้มากขึ้น", "ลดขั้นตอนการปฏิบัติงาน"],
        correct: 2,
        explanation: "เป้าหมายคือ 'ลด' ขั้นตอน ไม่ใช่เพิ่ม — เพื่อให้ประชาชนสะดวกและรวดเร็ว",
      },
      {
        type: "fill",
        question: "หลักการบริหารกิจการบ้านเมืองที่ดี ภาษาอังกฤษเรียกว่า Good ___",
        answer: "Governance",
        hint: "Good G_________ (ธรรมาภิบาล)",
      },
    ],
  },
  {
    id: "kpl-3",
    courseId: "kp-law",
    title: "พ.ร.บ. วิธีปฏิบัติราชการทางปกครอง",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "วิธีปฏิบัติราชการทางปกครอง",
        content: "พ.ร.บ. วิธีปฏิบัติราชการทางปกครอง พ.ศ. 2539 กำหนดขั้นตอนการออกคำสั่งทางปกครองให้เป็นธรรม\n\n🔑 หลักสำคัญ\n• คำสั่งทางปกครอง = การใช้อำนาจของเจ้าหน้าที่ที่มีผลต่อสิทธิ/หน้าที่ของบุคคล\n• ต้องให้คู่กรณีมีโอกาสโต้แย้งและชี้แจง\n• คำสั่งที่เป็นลายลักษณ์อักษรต้องระบุ 'เหตุผล'\n• ผู้ได้รับผลกระทบมีสิทธิอุทธรณ์\n\n📌 หัวใจ: ความเป็นธรรมและความโปร่งใสในการใช้อำนาจรัฐ",
      },
      {
        type: "quiz",
        question: "พ.ร.บ. วิธีปฏิบัติราชการทางปกครอง ประกาศใช้ พ.ศ. ใด?",
        choices: ["พ.ศ. 2534", "พ.ศ. 2539", "พ.ศ. 2546", "พ.ศ. 2540"],
        correct: 1,
        explanation: "พ.ร.บ. วิธีปฏิบัติราชการทางปกครอง ประกาศใช้ พ.ศ. 2539",
      },
      {
        type: "quiz",
        question: "ก่อนออกคำสั่งทางปกครองที่กระทบสิทธิ เจ้าหน้าที่ควรทำสิ่งใด?",
        choices: ["ออกคำสั่งทันทีโดยไม่ต้องแจ้ง", "ให้คู่กรณีมีโอกาสโต้แย้งและชี้แจง", "ปรึกษาเฉพาะหัวหน้า", "รอครบ 1 ปีก่อน"],
        correct: 1,
        explanation: "หลักความเป็นธรรม คู่กรณีต้องมีโอกาสโต้แย้งและแสดงพยานหลักฐานก่อน",
      },
      {
        type: "quiz",
        question: "คำสั่งทางปกครองที่เป็นหนังสือ ต้องระบุสิ่งใด?",
        choices: ["ชื่อเล่นของเจ้าหน้าที่", "เหตุผลของคำสั่ง", "เบอร์โทรส่วนตัว", "ไม่ต้องระบุอะไร"],
        correct: 1,
        explanation: "คำสั่งทางปกครองที่ทำเป็นหนังสือต้องระบุเหตุผล (ข้อเท็จจริง ข้อกฎหมาย และข้อพิจารณา)",
      },
    ],
  },
  {
    id: "kpl-4",
    courseId: "kp-law",
    title: "ประมวลจริยธรรมข้าราชการ",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "มาตรฐานทางจริยธรรมของข้าราชการ",
        content: "พ.ร.บ. มาตรฐานทางจริยธรรม พ.ศ. 2562 และประมวลจริยธรรม กำหนดหลักความประพฤติของข้าราชการ\n\n🔑 มาตรฐานทางจริยธรรม 7 ประการ\n1. ยึดมั่นในสถาบันหลักของประเทศ\n2. ซื่อสัตย์สุจริต มีจิตสำนึกที่ดี รับผิดชอบต่อหน้าที่\n3. กล้าตัดสินใจและกระทำในสิ่งที่ถูกต้อง\n4. คิดถึงประโยชน์ส่วนรวมมากกว่าส่วนตน\n5. มุ่งผลสัมฤทธิ์ของงาน\n6. ปฏิบัติหน้าที่อย่างเป็นธรรมและไม่เลือกปฏิบัติ\n7. ดำรงตนเป็นแบบอย่างที่ดี",
      },
      {
        type: "quiz",
        question: "พ.ร.บ. มาตรฐานทางจริยธรรม ประกาศใช้ พ.ศ. ใด?",
        choices: ["พ.ศ. 2546", "พ.ศ. 2558", "พ.ศ. 2562", "พ.ศ. 2560"],
        correct: 2,
        explanation: "พ.ร.บ. มาตรฐานทางจริยธรรม ประกาศใช้ พ.ศ. 2562",
      },
      {
        type: "quiz",
        question: "ข้อใดเป็นมาตรฐานทางจริยธรรมของข้าราชการ?",
        choices: ["เห็นแก่ประโยชน์ส่วนตนก่อน", "ซื่อสัตย์สุจริตและรับผิดชอบต่อหน้าที่", "เลือกปฏิบัติกับพวกพ้อง", "หลีกเลี่ยงการตัดสินใจ"],
        correct: 1,
        explanation: "ความซื่อสัตย์สุจริตและรับผิดชอบต่อหน้าที่เป็นมาตรฐานข้อสำคัญ ส่วนข้ออื่นขัดจริยธรรม",
      },
      {
        type: "quiz",
        question: "ข้าราชการที่ดีควรคำนึงถึงสิ่งใดเป็นหลัก?",
        choices: ["ประโยชน์ส่วนตน", "ประโยชน์ส่วนรวม", "ความสะดวกของตนเอง", "ผลประโยชน์ของพวกพ้อง"],
        correct: 1,
        explanation: "ต้องยึดประโยชน์ส่วนรวมมากกว่าประโยชน์ส่วนตน",
      },
    ],
  },
  {
    id: "kpl-5",
    courseId: "kp-law",
    title: "ความผิดต่อตำแหน่งหน้าที่ราชการ",
    order: 5,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "กฎหมายอาญา: ความผิดต่อตำแหน่งหน้าที่",
        content: "ประมวลกฎหมายอาญา หมวดความผิดต่อตำแหน่งหน้าที่ราชการ ลงโทษเจ้าพนักงานที่ทุจริต\n\n🔑 ความผิดสำคัญ\n• มาตรา 147 — เจ้าพนักงานยักยอกทรัพย์ที่อยู่ในหน้าที่\n• มาตรา 149 — เรียก/รับสินบน (ติดสินบนเจ้าพนักงาน)\n• มาตรา 157 — เจ้าพนักงานปฏิบัติ/ละเว้นหน้าที่โดยมิชอบ เพื่อให้เกิดความเสียหายหรือทุจริต\n\n📌 ม.157 เป็นมาตราที่ออกสอบบ่อยที่สุด — ครอบคลุมการใช้อำนาจโดยมิชอบทุกรูปแบบ",
      },
      {
        type: "quiz",
        question: "มาตราใดเกี่ยวกับเจ้าพนักงานปฏิบัติหรือละเว้นหน้าที่โดยมิชอบ?",
        choices: ["มาตรา 147", "มาตรา 149", "มาตรา 157", "มาตรา 112"],
        correct: 2,
        explanation: "มาตรา 157 ว่าด้วยเจ้าพนักงานปฏิบัติหรือละเว้นการปฏิบัติหน้าที่โดยมิชอบ เพื่อให้เกิดความเสียหายหรือโดยทุจริต",
      },
      {
        type: "quiz",
        question: "เจ้าพนักงานเรียกรับเงินเพื่อช่วยเหลือในการปฏิบัติหน้าที่ ผิดฐานใด?",
        choices: ["ลักทรัพย์", "รับสินบน", "หมิ่นประมาท", "ไม่ผิด"],
        correct: 1,
        explanation: "การเรียก/รับทรัพย์สินเพื่อกระทำหรือไม่กระทำการในหน้าที่ คือความผิดฐานรับสินบน (มาตรา 149)",
      },
      {
        type: "quiz",
        question: "มาตราใดที่ออกสอบ ก.พ. บ่อยที่สุดในหมวดความผิดต่อตำแหน่งหน้าที่?",
        choices: ["มาตรา 147", "มาตรา 157", "มาตรา 326", "มาตรา 288"],
        correct: 1,
        explanation: "มาตรา 157 ออกสอบบ่อยสุด เพราะครอบคลุมการใช้อำนาจหน้าที่โดยมิชอบทุกรูปแบบ",
      },
    ],
  },
  // ===== ภาษาอังกฤษ ม.ปลาย: ไวยากรณ์ =====
  {
    id: "engg-1",
    courseId: "eng-grammar",
    title: "Tenses ที่ต้องรู้ (ม.ปลาย)",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "Tenses หลักระดับ ม.ปลาย",
        content: "ระดับ ม.ปลาย เน้น Tenses ที่ซับซ้อนขึ้น\n\n🔑 Tenses สำคัญ\n• Present Perfect: have/has + V3 — ใช้กับ already, yet, just, since, for\n  → She has already finished her homework.\n• Past Perfect: had + V3 — เหตุการณ์ที่เกิดก่อนอีกเหตุการณ์หนึ่งในอดีต\n  → He had left before she arrived.\n• Future Perfect: will have + V3 — จะสำเร็จภายในเวลาที่กำหนดในอนาคต\n  → By noon, I will have completed the report.\n\n💡 คำบอกเวลาช่วยเลือก Tense ได้เสมอ",
      },
      {
        type: "quiz",
        question: "\"I ______ this book three times already.\" เลือก Tense ที่ถูกต้อง",
        choices: ["read", "reads", "have read", "had read"],
        correct: 2,
        explanation: "'already' บ่งบอก Present Perfect → have read (อ่านไปแล้ว ณ ปัจจุบัน)",
      },
      {
        type: "quiz",
        question: "\"By the time she arrived, he ______ dinner.\" เลือกกริยาที่ถูกต้อง",
        choices: ["already finishes", "has already finished", "had already finished", "will finish"],
        correct: 2,
        explanation: "เหตุการณ์ที่เสร็จก่อน (finish dinner) ก่อนเหตุการณ์อีกอย่าง (she arrived) ใช้ Past Perfect = had already finished",
      },
      {
        type: "quiz",
        question: "\"By 9 PM tonight, I ______ this project.\" ควรใช้ Tense ใด?",
        choices: ["finish", "finished", "have finished", "will have finished"],
        correct: 3,
        explanation: "\"By 9 PM tonight\" = เวลาในอนาคต + งานจะสำเร็จก่อนเวลานั้น → Future Perfect = will have finished",
      },
      {
        type: "fill",
        question: "เติม Tense: \"She ______ (live) in Chiang Mai since 2018.\" (Present Perfect)",
        answer: "has lived",
        hint: "has/have + V3 ใช้กับ 'since'",
      },
    ],
  },
  {
    id: "engg-2",
    courseId: "eng-grammar",
    title: "Conditionals (If-Clauses)",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "Conditionals 3 ประเภท",
        content: "ประโยคเงื่อนไข (If-Clauses) แบ่งเป็น 3 ประเภทหลัก\n\n🔑 Type 1 — Real/Possible (เป็นไปได้จริง)\nIf + Present Simple, will + V1\n→ If it rains, I will stay home.\n\n🔑 Type 2 — Unreal Present (สมมติ ไม่เป็นจริงในปัจจุบัน)\nIf + Past Simple, would + V1\n→ If I were rich, I would travel the world.\n\n🔑 Type 3 — Unreal Past (สมมติ ไม่ได้เกิดในอดีต)\nIf + Past Perfect, would have + V3\n→ If she had studied harder, she would have passed.\n\n💡 จำง่าย: Type 1 = จริง, Type 2 = สมมติปัจจุบัน, Type 3 = สมมติอดีต",
      },
      {
        type: "quiz",
        question: "\"If he ______ harder, he will pass the exam.\" ควรใช้คำใด?",
        choices: ["studied", "studies", "would study", "had studied"],
        correct: 1,
        explanation: "Type 1 Conditional (เป็นไปได้จริง): If + Present Simple (studies) + will",
      },
      {
        type: "quiz",
        question: "\"If I ______ a bird, I would fly to Paris.\" ควรใช้คำใด?",
        choices: ["am", "was", "were", "have been"],
        correct: 2,
        explanation: "Type 2 Conditional: If + Past Simple — ประธานทุกตัวใช้ 'were' ในภาษาเป็นทางการ → If I were...",
      },
      {
        type: "quiz",
        question: "\"If she had come to the party, she ______ him there.\" ควรใช้คำใด?",
        choices: ["would meet", "would have met", "will meet", "had met"],
        correct: 1,
        explanation: "Type 3 Conditional (สมมติอดีต): would have + V3 = would have met",
      },
      {
        type: "quiz",
        question: "ประโยคใดเป็น Type 2 Conditional?",
        choices: [
          "If it rains, we will cancel the trip.",
          "If I were taller, I would play basketball.",
          "If you had told me, I would have helped.",
          "If she studies, she passes.",
        ],
        correct: 1,
        explanation: "Type 2: If + Past Simple (were) + would + V1 สมมติสถานการณ์ที่ไม่เป็นจริงในปัจจุบัน",
      },
    ],
  },
  {
    id: "engg-3",
    courseId: "eng-grammar",
    title: "Passive Voice",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "Passive Voice คืออะไร?",
        content: "Passive Voice ใช้เมื่อต้องการเน้นที่ผู้รับการกระทำ ไม่ใช่ผู้กระทำ\n\n🔑 โครงสร้าง: to be + V3 (past participle)\n\n📌 ตัวอย่างตาม Tense\n• Present Simple: The cake is eaten. (กินอยู่เป็นประจำ)\n• Past Simple: The letter was written by him.\n• Present Perfect: The work has been completed.\n• Future: The report will be sent tomorrow.\n• Continuous: The house is being built.\n\n💡 Active → Passive\nActive: She wrote the letter.\nPassive: The letter was written by her.",
      },
      {
        type: "quiz",
        question: "เปลี่ยนเป็น Passive: \"They clean the office every day.\"",
        choices: [
          "The office cleaned every day.",
          "The office is cleaned every day.",
          "The office was cleaned every day.",
          "The office has been cleaned every day.",
        ],
        correct: 1,
        explanation: "Present Simple Passive: is/are + V3 → The office is cleaned every day.",
      },
      {
        type: "quiz",
        question: "\"The new bridge ______ by the government last year.\"",
        choices: ["built", "is built", "was built", "has been built"],
        correct: 2,
        explanation: "'last year' = อดีต → Past Simple Passive = was built",
      },
      {
        type: "quiz",
        question: "\"The report ______ before the meeting tomorrow.\"",
        choices: ["will finish", "will be finished", "is finished", "was finished"],
        correct: 1,
        explanation: "'tomorrow' = อนาคต + Passive → will be + V3 = will be finished",
      },
      {
        type: "fill",
        question: "เปลี่ยนเป็น Passive: \"They have repaired the road.\" → \"The road ______ ______ repaired.\"",
        answer: "has been",
        hint: "Present Perfect Passive: has/have + been + V3",
      },
    ],
  },
  {
    id: "engg-4",
    courseId: "eng-grammar",
    title: "Reported Speech",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "Reported Speech (คำพูดทางอ้อม)",
        content: "Reported Speech คือการรายงานสิ่งที่คนอื่นพูด โดยไม่ใช้เครื่องหมาย \" \"\n\n🔑 กฎการเลื่อน Tense (Backshift)\nDirect → Reported\n• is/am/are → was/were\n• was/were → had been\n• will → would\n• can → could\n• have/has + V3 → had + V3\n\n📌 ตัวอย่าง\nDirect: \"I am happy,\" she said.\nReported: She said that she was happy.\n\nDirect: \"I will call you,\" he said.\nReported: He said that he would call me.\n\n💡 คำบอกสถานที่/เวลาก็เปลี่ยนด้วย: now→then, today→that day, here→there",
      },
      {
        type: "quiz",
        question: "Direct: \"I am studying,\" Tom said. → Reported: Tom said that he ______",
        choices: ["is studying", "was studying", "studied", "has studied"],
        correct: 1,
        explanation: "'am studying' (Present Continuous) เลื่อนเป็น 'was studying' (Past Continuous)",
      },
      {
        type: "quiz",
        question: "Direct: \"I will help you,\" she said. → Reported: She said that she ______",
        choices: ["will help me", "would help me", "helped me", "has helped me"],
        correct: 1,
        explanation: "'will' เลื่อนเป็น 'would' ในประโยค Reported Speech",
      },
      {
        type: "quiz",
        question: "Direct: \"We have finished the project.\" → Reported: They said that they ______",
        choices: ["have finished the project", "had finished the project", "finished the project", "will finish the project"],
        correct: 1,
        explanation: "Present Perfect (have finished) เลื่อนเป็น Past Perfect (had finished)",
      },
      {
        type: "quiz",
        question: "Direct: \"I can swim,\" Amy said. → Reported: Amy said that she ______",
        choices: ["can swim", "could swim", "will swim", "swam"],
        correct: 1,
        explanation: "'can' เลื่อนเป็น 'could' ใน Reported Speech",
      },
    ],
  },
  // ===== ภาษาอังกฤษ ม.ปลาย: การอ่าน =====
  {
    id: "engr-1",
    courseId: "eng-reading",
    title: "Main Idea & Topic Sentence",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การหาใจความหลัก",
        content: "Main Idea = สิ่งที่ผู้เขียนต้องการสื่อมากที่สุดในย่อหน้าหรือบทความ\n\n🔑 เทคนิค\n• Topic Sentence มักอยู่ประโยคแรกของย่อหน้า\n• Supporting Details = ข้อมูลสนับสนุน ไม่ใช่ใจความหลัก\n• ถามตัวเองว่า 'บทความนี้พูดถึงอะไรเป็นหลัก?'\n• ตัวเลือกที่กว้างเกินไปหรือแคบเกินไป ไม่ใช่คำตอบ\n\n💡 Main Idea ต้องครอบคลุมทั้งบทความ ไม่ใช่แค่บางส่วน",
      },
      {
        type: "info",
        title: "Passage 1",
        content: "อ่านบทความนี้:\n\n\"Thailand is famous for its rich cultural heritage. The country has numerous ancient temples, traditional festivals, and unique cuisine that attract millions of tourists every year. Bangkok, the capital city, blends modern skyscrapers with historic landmarks, while northern regions offer lush mountains and hill tribe villages. This diversity makes Thailand one of the most visited destinations in Southeast Asia.\"",
      },
      {
        type: "quiz",
        question: "What is the main idea of the passage?",
        choices: [
          "Bangkok has many skyscrapers.",
          "Thailand's cultural diversity makes it a popular tourist destination.",
          "Hill tribe villages are found in northern Thailand.",
          "Thai food is unique and delicious.",
        ],
        correct: 1,
        explanation: "บทความกล่าวถึงความหลากหลายทางวัฒนธรรมของไทยที่ดึงดูดนักท่องเที่ยว — ตัวเลือกอื่นเป็นรายละเอียดย่อย",
      },
      {
        type: "quiz",
        question: "Which sentence best serves as the topic sentence of the passage?",
        choices: [
          "Bangkok blends modern and historic landmarks.",
          "Thailand is famous for its rich cultural heritage.",
          "Tourists visit hill tribe villages in the north.",
          "Southeast Asia has many beautiful countries.",
        ],
        correct: 1,
        explanation: "ประโยคแรก 'Thailand is famous for its rich cultural heritage' เป็น Topic Sentence ที่ครอบคลุมทั้งบทความ",
      },
      {
        type: "quiz",
        question: "Which detail SUPPORTS the main idea?",
        choices: [
          "Thailand's population is growing.",
          "Ancient temples and festivals attract tourists.",
          "Thai people speak Thai language.",
          "Thailand borders Myanmar and Laos.",
        ],
        correct: 1,
        explanation: "วัดโบราณและเทศกาลสนับสนุนใจความหลักเรื่องความหลากหลายทางวัฒนธรรมที่ดึงดูดนักท่องเที่ยว",
      },
    ],
  },
  {
    id: "engr-2",
    courseId: "eng-reading",
    title: "Inference (การตีความ)",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "Inference คืออะไร?",
        content: "Inference = การตีความหรืออนุมานสิ่งที่ผู้เขียนไม่ได้บอกตรงๆ แต่บอกเป็นนัย\n\n🔑 เทคนิค\n• คำตอบต้องมีหลักฐานในบทความ (ไม่ใช่เดาสุ่ม)\n• ระวังตัวเลือกที่ 'อาจเป็นจริงในชีวิตจริง' แต่ไม่มีหลักฐานในบทความ\n• มองหา 'นัย' ของคำที่ผู้เขียนเลือกใช้\n• ถามตัวเองว่า 'เราสามารถสรุปอะไรจากข้อมูลนี้ได้?'\n\n💡 Inference ≠ ข้อเท็จจริงใหม่ มันคือสิ่งที่ 'น่าจะจริง' จากสิ่งที่อ่าน",
      },
      {
        type: "info",
        title: "Passage 2",
        content: "อ่านบทความนี้:\n\n\"Maria arrived at the restaurant 20 minutes early and kept checking her phone. She had changed her outfit three times before leaving home and had rehearsed what she planned to say. When the door opened, she immediately stood up and smoothed her jacket.\"",
      },
      {
        type: "quiz",
        question: "What can we INFER about Maria?",
        choices: [
          "She is very hungry.",
          "She is nervous about meeting someone important.",
          "She works at the restaurant.",
          "She is late for her appointment.",
        ],
        correct: 1,
        explanation: "พฤติกรรมของ Maria (มาก่อน, เช็คโทรศัพท์, เปลี่ยนเสื้อ, ซ้อมพูด) บ่งบอกว่าเธอตื่นเต้นหรือประหม่ากับการพบใครบางคน",
      },
      {
        type: "quiz",
        question: "From the passage, we can infer that the person Maria is meeting is probably ______",
        choices: [
          "her close friend",
          "someone she meets every day",
          "someone important to her",
          "a stranger she is not interested in",
        ],
        correct: 2,
        explanation: "การเตรียมตัวอย่างพิถีพิถันแสดงว่าบุคคลที่มาพบมีความสำคัญกับเธอมาก",
      },
      {
        type: "quiz",
        question: "ข้อใด 'ไม่สามารถ' อนุมานได้จากบทความ?",
        choices: [
          "Maria arrived before the scheduled time.",
          "Maria was well-prepared for the meeting.",
          "The restaurant was full of people.",
          "Maria cared about making a good impression.",
        ],
        correct: 2,
        explanation: "บทความไม่ได้กล่าวถึงว่าร้านอาหารเต็มหรือไม่ จึงไม่สามารถอนุมานได้",
      },
    ],
  },
  {
    id: "engr-3",
    courseId: "eng-reading",
    title: "Vocabulary in Context",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การเดาความหมายจากบริบท",
        content: "Vocabulary in Context = การเดาความหมายคำศัพท์จากประโยคและบทความรอบข้าง โดยไม่ต้องรู้คำนั้นมาก่อน\n\n🔑 เทคนิค\n1. อ่านประโยคก่อนและหลังคำนั้น\n2. หา 'คำบอกใบ้' (context clues) เช่น\n   • Definition clue: คำอธิบายต่อจาก 'is' หรือ 'means'\n   • Contrast clue: 'but, however, although' บ่งบอกความตรงข้าม\n   • Example clue: 'such as, for example, like' บ่งบอกตัวอย่าง\n3. แทนคำตอบลงไปในประโยคแล้วอ่านดูว่าสมเหตุสมผลไหม",
      },
      {
        type: "info",
        title: "Passage 3",
        content: "อ่านบทความนี้:\n\n\"The scientist was known for her meticulous approach to research. She never rushed an experiment; instead, she carefully recorded every detail, double-checked each measurement, and repeated tests multiple times before drawing any conclusions. Her colleagues often joked that she was the most thorough person in the lab.\"",
      },
      {
        type: "quiz",
        question: "The word 'meticulous' most likely means ______",
        choices: ["careless and quick", "very careful and precise", "creative and imaginative", "loud and confident"],
        correct: 1,
        explanation: "บริบทบอกว่าเธอบันทึกทุกรายละเอียด ตรวจสอบซ้ำ และทดสอบหลายรอบ — ล้วนชี้ไปที่ความหมาย 'รอบคอบมาก'",
      },
      {
        type: "quiz",
        question: "The word 'thorough' in the last sentence is closest in meaning to ______",
        choices: ["fast", "creative", "complete and careful", "famous"],
        correct: 2,
        explanation: "'thorough' = ละเอียดถี่ถ้วน บริบทในบทความสนับสนุนด้วยพฤติกรรมตรวจสอบซ้ำและทดลองหลายรอบ",
      },
      {
        type: "quiz",
        question: "ข้อใดเป็น 'contrast clue' ที่ช่วยเดาความหมายคำในบทความ?",
        choices: [
          "such as, for example",
          "She never rushed; instead, she carefully recorded",
          "Her colleagues often joked",
          "drawing any conclusions",
        ],
        correct: 1,
        explanation: "'never rushed; instead, she carefully recorded' ใช้ contrast (แทน) บอกว่าเธอทำตรงข้ามกับ 'รีบ' คือ 'ละเอียดรอบคอบ'",
      },
    ],
  },
  {
    id: "engr-4",
    courseId: "eng-reading",
    title: "Skimming & Scanning",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "Skimming vs Scanning",
        content: "สองเทคนิคอ่านเร็วที่ขาดไม่ได้ในข้อสอบ\n\n📌 Skimming = อ่านเพื่อจับใจความหลักอย่างรวดเร็ว\n• อ่านประโยคแรก-สุดท้ายของแต่ละย่อหน้า\n• มองภาพรวม ไม่ต้องอ่านทุกคำ\n• ใช้ตอบคำถาม 'Main Idea' หรือ 'Purpose'\n\n📌 Scanning = ค้นหาข้อมูลเฉพาะอย่างรวดเร็ว\n• กวาดตาหาตัวเลข, ชื่อ, วันที่, คำหลัก\n• ไม่ต้องอ่านทุกคำ หาจุดที่ตรงกับคำถาม\n• ใช้ตอบคำถาม detail เช่น 'When did...', 'How many...'\n\n💡 อ่านคำถามก่อน แล้ว scan หาคำตอบในบทความ — ประหยัดเวลามาก",
      },
      {
        type: "quiz",
        question: "ควรใช้เทคนิคใดเมื่อต้องการรู้ว่าบทความพูดถึงอะไรโดยรวม?",
        choices: ["Scanning", "Skimming", "Translating word by word", "Memorizing"],
        correct: 1,
        explanation: "Skimming ใช้จับใจความหลักและภาพรวมของบทความอย่างรวดเร็ว",
      },
      {
        type: "quiz",
        question: "ควรใช้เทคนิคใดเมื่อโจทย์ถามว่า 'In what year was the museum founded?'",
        choices: ["Skimming", "Scanning", "Reading aloud", "Summarizing"],
        correct: 1,
        explanation: "คำถามถามหาข้อมูลเฉพาะ (ปี) ใช้ Scanning กวาดตาหาตัวเลขปีในบทความ",
      },
      {
        type: "quiz",
        question: "ข้อใดเป็นสัญญาณที่ช่วยในการ Scan หาข้อมูล?",
        choices: [
          "อ่านทุกคำในบทความ",
          "มองหาตัวเลข, ชื่อเฉพาะ, และคำหลักที่ตรงกับโจทย์",
          "แปลบทความเป็นภาษาไทยทั้งหมด",
          "ท่องจำบทความ",
        ],
        correct: 1,
        explanation: "การ Scan ที่มีประสิทธิภาพคือการมองหา keyword, ตัวเลข, หรือชื่อเฉพาะที่เกี่ยวข้องกับคำถาม",
      },
      {
        type: "fill",
        question: "การอ่านเพื่อจับใจความหลักอย่างรวดเร็วเรียกว่า _______",
        answer: "skimming",
        hint: "Sk_____ing (6 ตัวอักษรหลัง sk)",
      },
    ],
  },
  // ===== ภาษาอังกฤษ ม.ปลาย: คำศัพท์ =====
  {
    id: "engv-1",
    courseId: "eng-vocab",
    title: "Idioms ที่ต้องรู้",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "Idioms คืออะไร?",
        content: "Idioms = สำนวนที่ความหมายไม่ตรงตัวอักษร ต้องจำเป็นชุด\n\n🔑 Idioms ที่ออกสอบบ่อย\n• hit the books = เริ่มอ่านหนังสือ/ตั้งใจเรียน\n• break a leg = ขอให้โชคดี (ไม่ใช่หักขา!)\n• under the weather = รู้สึกไม่สบาย\n• bite the bullet = อดทนฝ่าฟันสิ่งที่ยาก\n• once in a blue moon = นานๆ ครั้ง\n• cost an arm and a leg = แพงมาก\n• let the cat out of the bag = เผลอบอกความลับ\n• it's raining cats and dogs = ฝนตกหนักมาก",
      },
      {
        type: "quiz",
        question: "\"You look under the weather today. Are you okay?\" ประโยคนี้หมายความว่าอะไร?",
        choices: ["คุณดูดีมากวันนี้", "คุณดูไม่ค่อยสบาย", "คุณดูเหนื่อยจากการทำงาน", "คุณดูเป็นกังวล"],
        correct: 1,
        explanation: "'under the weather' = รู้สึกไม่สบายหรือไม่ค่อยดี",
      },
      {
        type: "quiz",
        question: "\"It cost me an arm and a leg!\" Idiom นี้หมายถึงอะไร?",
        choices: ["มีอุบัติเหตุ", "แพงมาก", "ใช้เวลานาน", "ต้องออกแรงมาก"],
        correct: 1,
        explanation: "'cost an arm and a leg' = แพงมาก (ไม่เกี่ยวกับแขนขา)",
      },
      {
        type: "quiz",
        question: "\"She only visits her hometown once in a blue moon.\" หมายความว่าอย่างไร?",
        choices: ["เธอชอบดูพระจันทร์", "เธอกลับบ้านทุกเดือน", "เธอกลับบ้านนานๆ ครั้ง", "เธอไม่เคยกลับบ้านเลย"],
        correct: 2,
        explanation: "'once in a blue moon' = นานๆ ครั้ง (ไม่ค่อยเกิดขึ้น)",
      },
      {
        type: "fill",
        question: "\"I accidentally let the cat out of the ___\" หมายถึงเผลอบอกความลับ",
        answer: "bag",
        hint: "let the cat out of the ___",
      },
    ],
  },
  {
    id: "engv-2",
    courseId: "eng-vocab",
    title: "Phrasal Verbs",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "Phrasal Verbs คืออะไร?",
        content: "Phrasal Verbs = กริยา + คำบุพบท/คำวิเศษณ์ที่มีความหมายใหม่\n\n🔑 Phrasal Verbs ที่ต้องรู้\n• give up = ยอมแพ้, เลิก\n• look up = ค้นหา (ในพจนานุกรม)\n• put off = เลื่อน, ผัดผ่อน\n• run out of = หมด (สิ่งของ)\n• take off = ถอด / (เครื่องบิน) ขึ้น\n• come across = บังเอิญพบ\n• bring up = เลี้ยงดู / หยิบยกประเด็น\n• turn down = ปฏิเสธ\n• figure out = หาคำตอบ, ทำความเข้าใจ\n• get along with = สนิทสนมกับ",
      },
      {
        type: "quiz",
        question: "\"She turned down the job offer.\" หมายความว่าอะไร?",
        choices: ["เธอรับงานนั้น", "เธอปฏิเสธข้อเสนองาน", "เธอลดเงินเดือน", "เธอลาออก"],
        correct: 1,
        explanation: "'turn down' = ปฏิเสธ, ไม่รับข้อเสนอ",
      },
      {
        type: "quiz",
        question: "\"We ran out of sugar while baking.\" หมายความว่าอะไร?",
        choices: ["พวกเราวิ่งออกไปซื้อน้ำตาล", "น้ำตาลหมด", "พวกเราทำน้ำตาลหก", "น้ำตาลเหลือมาก"],
        correct: 1,
        explanation: "'run out of' = หมด (ของที่ใช้อยู่หมดลง)",
      },
      {
        type: "quiz",
        question: "เลือก Phrasal Verb ที่เติมประโยคได้ถูก: \"Don't ______ your homework. Do it now!\"",
        choices: ["put off", "put up", "put on", "put away"],
        correct: 0,
        explanation: "'put off' = เลื่อน/ผัดผ่อน — Don't put off your homework = อย่าเลื่อนการบ้าน",
      },
      {
        type: "quiz",
        question: "\"I came across an old photo while cleaning.\" 'came across' หมายถึงอะไร?",
        choices: ["ฉันข้ามผ่าน", "ฉันบังเอิญพบ", "ฉันนำมา", "ฉันโยนทิ้ง"],
        correct: 1,
        explanation: "'come across' = บังเอิญพบหรือเจอโดยไม่ได้ตั้งใจ",
      },
    ],
  },
  {
    id: "engv-3",
    courseId: "eng-vocab",
    title: "Word Formation",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การสร้างคำ (Word Formation)",
        content: "การรู้ prefix และ suffix ช่วยเดาความหมายคำใหม่ได้แม้ไม่เคยเห็น\n\n🔑 Prefix (คำนำหน้า)\n• un- = ไม่ → unhappy, unknown\n• dis- = ไม่/ตรงข้าม → disagree, disappear\n• re- = ทำซ้ำ → rewrite, rebuild\n• pre- = ก่อน → preview, predict\n• over- = มากเกินไป → overwork, overeat\n\n🔑 Suffix (คำลงท้าย)\n• -tion/-sion = คำนาม → education, decision\n• -ful = มี... → careful, beautiful\n• -less = ไม่มี... → careless, hopeless\n• -ment = คำนาม → government, achievement\n• -ly = คำกริยาวิเศษณ์ → quickly, easily",
      },
      {
        type: "quiz",
        question: "คำว่า 'disagree' มาจาก prefix 'dis-' + 'agree' ความหมายคือ?",
        choices: ["เห็นด้วยอย่างยิ่ง", "ไม่เห็นด้วย", "เห็นด้วยก่อน", "เห็นด้วยอีกครั้ง"],
        correct: 1,
        explanation: "'dis-' = ไม่/ตรงข้าม + agree = เห็นด้วย → disagree = ไม่เห็นด้วย",
      },
      {
        type: "quiz",
        question: "คำว่า 'careless' มาจาก 'care' + suffix '-less' ความหมายคือ?",
        choices: ["ระมัดระวัง", "ไม่ระมัดระวัง", "ระมัดระวังมาก", "เต็มใจ"],
        correct: 1,
        explanation: "'-less' = ไม่มี + care = ความระมัดระวัง → careless = ไม่ระมัดระวัง",
      },
      {
        type: "quiz",
        question: "สร้างคำนามจาก 'achieve' โดยใช้ suffix ที่ถูกต้อง",
        choices: ["achieveful", "achieveless", "achievement", "achievely"],
        correct: 2,
        explanation: "'-ment' สร้างคำนามจากกริยา → achievement (ความสำเร็จ)",
      },
      {
        type: "fill",
        question: "เติม prefix เพื่อให้ได้คำแปลว่า 'เขียนใหม่': ___write",
        answer: "re",
        hint: "prefix ที่แปลว่า 'ทำซ้ำ' คือ re-",
      },
    ],
  },
  {
    id: "engv-4",
    courseId: "eng-vocab",
    title: "Academic Vocabulary",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "คำศัพท์ระดับวิชาการที่ต้องรู้",
        content: "Academic Vocabulary ออกสอบ O-NET และสอบเข้ามหาวิทยาลัย บ่อย\n\n🔑 คำศัพท์สำคัญ\n• analyze = วิเคราะห์\n• significant = สำคัญ, มีนัยสำคัญ\n• contribute = มีส่วนร่วม, ก่อให้เกิด\n• evaluate = ประเมิน\n• indicate = บ่งชี้\n• demonstrate = แสดงให้เห็น\n• interpret = ตีความ\n• establish = ก่อตั้ง, สร้าง\n• identify = ระบุ, ชี้ให้เห็น\n• define = ให้คำนิยาม",
      },
      {
        type: "quiz",
        question: "\"The data indicates a significant increase in temperature.\" คำว่า 'indicates' หมายความว่าอะไร?",
        choices: ["ซ่อน", "บ่งชี้/แสดงให้เห็น", "ลด", "ยกเลิก"],
        correct: 1,
        explanation: "'indicate' = บ่งชี้, แสดงให้เห็น — ข้อมูลบ่งชี้ว่าอุณหภูมิเพิ่มขึ้น",
      },
      {
        type: "quiz",
        question: "\"Please evaluate the advantages and disadvantages.\" 'evaluate' หมายถึงอะไร?",
        choices: ["อ่าน", "ประเมิน/วัด", "คัดลอก", "ลบ"],
        correct: 1,
        explanation: "'evaluate' = ประเมิน, ตัดสิน — ให้ประเมินข้อดีและข้อเสีย",
      },
      {
        type: "quiz",
        question: "คำใดมีความหมายใกล้เคียงกับ 'significant'?",
        choices: ["tiny", "important", "simple", "fast"],
        correct: 1,
        explanation: "'significant' = สำคัญ, มีนัยสำคัญ ใกล้เคียงกับ 'important'",
      },
      {
        type: "fill",
        question: "คำที่แปลว่า 'วิเคราะห์' ในภาษาอังกฤษคือ ________",
        answer: "analyze",
        hint: "ana_______ (7 ตัวอักษร)",
      },
    ],
  },
  // ===== ภาษาอังกฤษ ม.ปลาย: บทสนทนา =====
  {
    id: "engc-1",
    courseId: "eng-conversation",
    title: "Making Requests & Offers",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การขอร้องและเสนอความช่วยเหลือ",
        content: "การขอร้อง (Requests) และเสนอ (Offers) อย่างสุภาพเป็นทักษะสำคัญ\n\n🔑 การขอร้อง (จากสุภาพน้อยไปมาก)\n• Can you...? (ทั่วไป)\n• Could you...? (สุภาพกว่า)\n• Would you mind...? + V-ing (สุภาพมาก)\n• I was wondering if you could... (ทางการมาก)\n\n🔑 การเสนอความช่วยเหลือ\n• Shall I...?\n• Would you like me to...?\n• Can I help you with...?\n• Let me...\n\n🔑 การตอบรับ/ปฏิเสธ\n• Yes, please. / That would be great.\n• No, thank you. / That's alright.",
      },
      {
        type: "quiz",
        question: "เลือกการขอร้องที่สุภาพที่สุด: ขอให้เพื่อนช่วยยกกระเป๋า",
        choices: [
          "Lift my bag!",
          "You must lift my bag.",
          "Could you help me with my bag, please?",
          "Bag, now!",
        ],
        correct: 2,
        explanation: "'Could you...please?' เป็นรูปแบบขอร้องที่สุภาพและเหมาะสมที่สุด",
      },
      {
        type: "quiz",
        question: "A: \"Would you mind closing the window?\" B ตอบรับควรพูดว่าอะไร?",
        choices: [
          "Yes, I mind.",
          "Not at all. I'll close it right away.",
          "No, I won't.",
          "I don't think so.",
        ],
        correct: 1,
        explanation: "Would you mind...? ตอบรับ = 'Not at all' หรือ 'Of course not' (แปลว่าไม่รังเกียจ = ยินดีช่วย)",
      },
      {
        type: "quiz",
        question: "A: \"Shall I carry that for you?\" B ปฏิเสธอย่างสุภาพควรพูดว่าอะไร?",
        choices: [
          "No!",
          "I don't want your help.",
          "No, thank you. I can manage.",
          "Go away.",
        ],
        correct: 2,
        explanation: "การปฏิเสธอย่างสุภาพ: 'No, thank you.' พร้อมอธิบายสั้นๆ",
      },
      {
        type: "fill",
        question: "เติมคำ: \"I was ________ if you could help me with this.\" (การขอร้องอย่างสุภาพมาก)",
        answer: "wondering",
        hint: "I was won_______ if...",
      },
    ],
  },
  {
    id: "engc-2",
    courseId: "eng-conversation",
    title: "Expressing Opinions",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การแสดงความคิดเห็น",
        content: "การแสดงความเห็น เห็นด้วย และไม่เห็นด้วยอย่างสุภาพ\n\n🔑 การแสดงความเห็น\n• In my opinion, ...\n• I think / I believe / I feel that...\n• As far as I'm concerned,...\n• From my point of view,...\n\n🔑 การเห็นด้วย\n• I agree with you.\n• That's a good point.\n• Exactly! / Absolutely!\n• You're right.\n\n🔑 การไม่เห็นด้วยอย่างสุภาพ\n• I'm not sure about that.\n• I see your point, but...\n• I disagree because...\n• Actually, I think...\n\n💡 ไม่เห็นด้วยอย่างสุภาพ = เริ่มด้วยการยอมรับมุมมองของอีกฝ่ายก่อน",
      },
      {
        type: "quiz",
        question: "คุณต้องการแสดงความเห็นว่า 'ฉันคิดว่าการอ่านหนังสือดีกว่าดูโทรทัศน์' ประโยคใดเหมาะที่สุด?",
        choices: [
          "Reading is better. Period.",
          "In my opinion, reading is more beneficial than watching TV.",
          "Everyone must read books.",
          "TV is bad.",
        ],
        correct: 1,
        explanation: "'In my opinion,...' เป็นการแสดงความเห็นส่วนตัวที่สุภาพและเหมาะสม",
      },
      {
        type: "quiz",
        question: "A: \"I think we should study abroad.\" B ไม่เห็นด้วยอย่างสุภาพ ควรพูดว่าอะไร?",
        choices: [
          "That's completely wrong!",
          "No!",
          "I see your point, but studying locally can be equally good.",
          "You don't know anything.",
        ],
        correct: 2,
        explanation: "'I see your point, but...' เป็นการไม่เห็นด้วยอย่างสุภาพโดยยอมรับมุมมองของอีกฝ่ายก่อน",
      },
      {
        type: "quiz",
        question: "ข้อใด 'ไม่ใช่' วิธีแสดงความเห็นด้วยอย่างสุภาพ?",
        choices: [
          "I agree with you.",
          "That's a good point.",
          "I'm not sure about that.",
          "Absolutely!",
        ],
        correct: 2,
        explanation: "'I'm not sure about that' แสดงถึงการลังเลหรือไม่เห็นด้วย ไม่ใช่การเห็นด้วย",
      },
    ],
  },
  {
    id: "engc-3",
    courseId: "eng-conversation",
    title: "Social Situations",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "บทสนทนาในสถานการณ์ต่างๆ",
        content: "สถานการณ์ที่ออกสอบบ่อยในภาษาอังกฤษ ม.ปลาย\n\n📌 ร้านอาหาร\n• May I take your order? — สั่งอาหารได้เลยครับ\n• I'd like to have... — ฉันขอ...\n• Could I have the bill, please? — ขอบิลได้ไหม\n\n📌 การแนะนำตัว\n• Nice to meet you. — ยินดีที่ได้รู้จัก\n• How do you do? (ทางการ)\n• Let me introduce myself. — ขอแนะนำตัว\n\n📌 การขอโทษ\n• I'm sorry. / I apologize.\n• I beg your pardon? — ขอโทษ พูดซ้ำได้ไหม (ไม่ได้ยิน)\n\n📌 การลา\n• It was nice talking to you.\n• Take care! / See you later!",
      },
      {
        type: "quiz",
        question: "พนักงานในร้านอาหารพูดว่า 'May I take your order?' หมายความว่าอะไร?",
        choices: [
          "คุณต้องการอะไรไหม?",
          "พร้อมสั่งอาหารได้เลยไหมครับ/ค่ะ?",
          "คุณชอบอาหารอะไร?",
          "จะจ่ายเงินได้ไหม?",
        ],
        correct: 1,
        explanation: "'May I take your order?' = พนักงานถามว่าพร้อมสั่งอาหารหรือยัง",
      },
      {
        type: "quiz",
        question: "A: \"I beg your pardon?\" ประโยคนี้ใช้ในสถานการณ์ใด?",
        choices: [
          "เมื่อต้องการขอโทษสำหรับความผิดพลาด",
          "เมื่อไม่ได้ยินหรือไม่เข้าใจสิ่งที่อีกฝ่ายพูด",
          "เมื่อต้องการลา",
          "เมื่อต้องการสั่งอาหาร",
        ],
        correct: 1,
        explanation: "'I beg your pardon?' ใช้เมื่อไม่ได้ยินหรือต้องการให้พูดซ้ำ เป็นการขอโทษที่สุภาพก่อนขอให้พูดใหม่",
      },
      {
        type: "quiz",
        question: "A: \"Nice to meet you.\" B ควรตอบว่าอะไร?",
        choices: [
          "Yes, I am.",
          "Nice to meet you too.",
          "How are you?",
          "I don't know you.",
        ],
        correct: 1,
        explanation: "ตอบรับการทักทาย 'Nice to meet you' ด้วย 'Nice to meet you too.'",
      },
      {
        type: "fill",
        question: "เมื่อต้องการเรียกบิลในร้านอาหาร: \"Could I have the ______, please?\"",
        answer: "bill",
        hint: "ใบเรียกเก็บเงิน = b___",
      },
    ],
  },
  {
    id: "engc-4",
    courseId: "eng-conversation",
    title: "Formal vs Informal Language",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "ภาษาทางการและไม่ทางการ",
        content: "ภาษาอังกฤษมี 2 ระดับหลัก เลือกให้เหมาะกับสถานการณ์\n\n📌 ภาษาทางการ (Formal) — ใช้ในงาน, จดหมาย, การนำเสนอ\n• I would like to... (ไม่ใช่ I wanna)\n• Could you please... (ไม่ใช่ Can ya)\n• I am writing to inform you... \n• With regard to...\n\n📌 ภาษาไม่ทางการ (Informal) — ใช้กับเพื่อน, แชท\n• Wanna, gonna, gotta (want to, going to, got to)\n• Hey! / Hi! / What's up?\n• Cool / Awesome / No worries\n• Contractions: I'm, you're, don't\n\n💡 ในข้อสอบ ถ้าสถานการณ์เป็นทางการ ให้เลือกภาษาทางการเสมอ",
      },
      {
        type: "quiz",
        question: "คุณกำลังเขียนอีเมลหาอาจารย์เพื่อขอนัด ประโยคใดเหมาะที่สุด?",
        choices: [
          "Hey! Wanna meet up?",
          "I would like to request an appointment at your convenience.",
          "Can we meet? I need to talk.",
          "Gonna see you soon!",
        ],
        correct: 1,
        explanation: "อีเมลหาอาจารย์ = สถานการณ์ทางการ ต้องใช้ภาษาทางการ 'I would like to request...'",
      },
      {
        type: "quiz",
        question: "ข้อใดเป็นประโยคไม่ทางการ (Informal)?",
        choices: [
          "I am unable to attend the meeting.",
          "With regard to your inquiry...",
          "No worries, I'll sort it out!",
          "Please find attached the required documents.",
        ],
        correct: 2,
        explanation: "'No worries, I'll sort it out!' ใช้ภาษาสบายๆ ไม่ทางการ เหมาะกับเพื่อน ไม่เหมาะในบริบทวิชาชีพ",
      },
      {
        type: "quiz",
        question: "รูปแบบทางการของ 'I wanna go' คือข้อใด?",
        choices: [
          "I gonna go",
          "I want to go",
          "I gotta go",
          "I'd wanna go",
        ],
        correct: 1,
        explanation: "'wanna' = want to (ภาษาพูดไม่ทางการ) รูปแบบทางการคือ 'I want to go'",
      },
    ],
  },
  // ===== ภาษาอังกฤษ ม.ปลาย: การเขียน =====
  {
    id: "engw-1",
    courseId: "eng-writing",
    title: "Paragraph Writing",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "โครงสร้างย่อหน้าที่ดี",
        content: "ย่อหน้า (Paragraph) ที่ดีประกอบด้วย 3 ส่วนหลัก\n\n1️⃣ Topic Sentence — ประโยคหัวเรื่อง บอกใจความหลักของย่อหน้า\n2️⃣ Supporting Details — รายละเอียดสนับสนุน (ตัวอย่าง, เหตุผล, ข้อมูล)\n3️⃣ Concluding Sentence — สรุปหรือเชื่อมโยงไปย่อหน้าถัดไป\n\n📌 ตัวอย่าง\nTopic: \"Regular exercise has many health benefits.\"\nSupport: \"It strengthens the heart, reduces stress, and helps maintain healthy weight.\"\nConclusion: \"Therefore, making time for exercise should be a priority for everyone.\"\n\n💡 ย่อหน้าที่ดี = หนึ่งใจความ ไม่กระโดดไปเรื่องอื่น",
      },
      {
        type: "quiz",
        question: "ส่วนใดของย่อหน้าทำหน้าที่บอกใจความหลัก?",
        choices: ["Supporting Details", "Concluding Sentence", "Topic Sentence", "Examples"],
        correct: 2,
        explanation: "Topic Sentence = ประโยคหัวเรื่องที่บอกใจความหลักของย่อหน้า มักอยู่ประโยคแรก",
      },
      {
        type: "quiz",
        question: "ย่อหน้าหนึ่งควรมีกี่ใจความหลัก?",
        choices: ["ยิ่งมากยิ่งดี", "อย่างน้อย 3 ใจความ", "หนึ่งใจความ", "ไม่จำกัด"],
        correct: 2,
        explanation: "ย่อหน้าที่ดีควรมีหนึ่งใจความหลัก (one main idea) เพื่อให้ชัดเจนและเป็นระเบียบ",
      },
      {
        type: "quiz",
        question: "ข้อใดเป็น Topic Sentence ที่ดีสำหรับย่อหน้าเกี่ยวกับการใช้โทรศัพท์มือถือ?",
        choices: [
          "I have a smartphone.",
          "Smartphones have both positive and negative effects on teenagers.",
          "Teenagers use phones a lot.",
          "Phones are expensive.",
        ],
        correct: 1,
        explanation: "Topic Sentence ที่ดีต้องบอกประเด็นหลักชัดเจน — 'Smartphones have both positive and negative effects' ครอบคลุมทั้งย่อหน้า",
      },
      {
        type: "fill",
        question: "ส่วนสุดท้ายของย่อหน้าที่สรุปหรือเชื่อมโยงใจความเรียกว่า ________ Sentence",
        answer: "Concluding",
        hint: "Con________ (9 ตัวอักษรหลัง Con)",
      },
    ],
  },
  {
    id: "engw-2",
    courseId: "eng-writing",
    title: "Essay Structure",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "โครงสร้าง Essay",
        content: "Essay ประกอบด้วย 3 ส่วนหลัก\n\n1️⃣ Introduction (บทนำ)\n• Hook — ดึงดูดความสนใจ (คำถาม, สถิติ, คำพูด)\n• Background Information — ข้อมูลพื้นฐาน\n• Thesis Statement — ประเด็นหลักของ Essay\n\n2️⃣ Body Paragraphs (เนื้อหา)\n• แต่ละย่อหน้า = หนึ่งประเด็น + หลักฐานสนับสนุน\n• ใช้คำเชื่อม: First, Furthermore, However, In addition\n\n3️⃣ Conclusion (บทสรุป)\n• สรุปประเด็นหลักอีกครั้ง (ไม่ต้องใส่ข้อมูลใหม่)\n• ปิดด้วยข้อความที่น่าจดจำ\n\n💡 Thesis Statement = หัวใจของ Essay บอกว่าจะพูดถึงอะไร",
      },
      {
        type: "quiz",
        question: "Thesis Statement คืออะไร?",
        choices: [
          "ประโยคแรกสุดของ Essay",
          "ประเด็นหลักที่ Essay จะพูดถึง มักอยู่ท้าย Introduction",
          "บทสรุปของ Essay",
          "รายการหัวข้อทั้งหมด",
        ],
        correct: 1,
        explanation: "Thesis Statement = ประโยคที่บอกประเด็นหลักของ Essay มักอยู่ท้าย Introduction",
      },
      {
        type: "quiz",
        question: "ส่วน Conclusion ของ Essay ควรทำอะไร?",
        choices: [
          "แนะนำข้อมูลใหม่ที่ไม่เคยกล่าวถึง",
          "สรุปประเด็นหลักและปิดบทความอย่างมีประสิทธิภาพ",
          "คัดลอกประโยคจาก Introduction ทั้งหมด",
          "เขียนคำถามทิ้งไว้โดยไม่ตอบ",
        ],
        correct: 1,
        explanation: "Conclusion สรุปประเด็นที่กล่าวถึงแล้ว ไม่ควรใส่ข้อมูลใหม่",
      },
      {
        type: "quiz",
        question: "คำเชื่อมข้อใดใช้เพิ่มประเด็นในย่อหน้า Body?",
        choices: ["However", "In conclusion", "Furthermore", "For example only"],
        correct: 2,
        explanation: "'Furthermore' = นอกจากนี้ ใช้เพิ่มประเด็นหรือข้อมูล ส่วน 'However' ใช้แสดงความตรงข้าม",
      },
    ],
  },
  {
    id: "engw-3",
    courseId: "eng-writing",
    title: "Formal Letter Writing",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "โครงสร้างจดหมายทางการ",
        content: "Formal Letter มีโครงสร้างที่ชัดเจน\n\n📌 ส่วนประกอบ\n1. Sender's Address — ที่อยู่ผู้ส่ง (มุมขวาบน)\n2. Date — วันที่\n3. Recipient's Address — ที่อยู่ผู้รับ\n4. Salutation — คำขึ้นต้น\n   • Dear Sir/Madam, (ไม่รู้ชื่อ)\n   • Dear Mr./Ms. [Name], (รู้ชื่อ)\n5. Body — เนื้อหา (Introduction, Main Point, Request)\n6. Complimentary Close — คำลงท้าย\n   • Yours faithfully, (ไม่รู้ชื่อ)\n   • Yours sincerely, (รู้ชื่อ)\n7. Signature & Name\n\n💡 กฎทองคำ: Dear Sir/Madam → Yours faithfully | Dear Mr./Ms. Name → Yours sincerely",
      },
      {
        type: "quiz",
        question: "ถ้าขึ้นต้นจดหมายด้วย 'Dear Sir/Madam,' ควรลงท้ายด้วยอะไร?",
        choices: ["Yours sincerely,", "Yours faithfully,", "Best wishes,", "Love,"],
        correct: 1,
        explanation: "กฎ: Dear Sir/Madam (ไม่รู้ชื่อ) → Yours faithfully | Dear Mr./Ms. Name (รู้ชื่อ) → Yours sincerely",
      },
      {
        type: "quiz",
        question: "ประโยคเปิดจดหมายทางการที่เหมาะสมคือข้อใด?",
        choices: [
          "Hey! How's it going?",
          "I am writing to apply for the position of...",
          "Wanna know something cool?",
          "So, here's the thing...",
        ],
        correct: 1,
        explanation: "'I am writing to...' เป็นรูปแบบเปิดจดหมายทางการที่ใช้บ่อยที่สุด",
      },
      {
        type: "quiz",
        question: "ถ้าส่งจดหมายถึง 'Mr. Somchai' ควรลงท้ายด้วยอะไร?",
        choices: ["Yours faithfully,", "Yours sincerely,", "See you soon,", "Cheers,"],
        correct: 1,
        explanation: "รู้ชื่อผู้รับ (Mr. Somchai) → Dear Mr. Somchai → Yours sincerely",
      },
      {
        type: "fill",
        question: "คำขึ้นต้นจดหมายที่ใช้เมื่อไม่รู้ชื่อผู้รับคือ Dear Sir/______",
        answer: "Madam",
        hint: "Dear Sir/M_____",
      },
    ],
  },
  {
    id: "engw-4",
    courseId: "eng-writing",
    title: "Narrative Writing",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การเขียนเรื่องเล่า (Narrative Writing)",
        content: "Narrative Writing คือการเล่าเรื่องที่มีโครงสร้างและดึงดูดผู้อ่าน\n\n📌 โครงสร้าง\n1. Setting — สถานที่และเวลา\n2. Characters — ตัวละคร\n3. Rising Action — เหตุการณ์นำไปสู่ปัญหา\n4. Climax — จุดสูงสุดของความตึงเครียด\n5. Resolution — การแก้ปัญหา/ตอนจบ\n\n🔑 เทคนิคเขียนให้น่าสนใจ\n• เริ่มต้นด้วย action หรือ dialogue แทนการอธิบาย\n• ใช้ Descriptive Words (adjectives, adverbs) ทำให้ภาพชัด\n• ใช้ Sequence words: First, Then, After that, Finally\n• เขียนใน Past Tense\n\n💡 Show, don't tell — แทนที่จะเขียน 'She was scared' ให้เขียน 'Her hands trembled and her heart pounded.'",
      },
      {
        type: "quiz",
        question: "ส่วน Climax ในการเขียนเรื่องเล่าคืออะไร?",
        choices: [
          "การแนะนำตัวละคร",
          "จุดสูงสุดของความตึงเครียดหรือความขัดแย้งในเรื่อง",
          "การแก้ปัญหาในตอนจบ",
          "การบรรยายสถานที่",
        ],
        correct: 1,
        explanation: "Climax = จุดสูงสุดของความตึงเครียด ก่อนที่เรื่องจะคลี่คลาย",
      },
      {
        type: "quiz",
        question: "ข้อใดเป็นการเริ่มต้นเรื่องเล่าที่ดึงดูดผู้อ่านมากที่สุด?",
        choices: [
          "This story is about a boy named Tom.",
          "In this essay, I will tell you about my adventure.",
          "\"Run!\" Tom shouted as the flood rushed toward the village.",
          "The setting is a small village.",
        ],
        correct: 2,
        explanation: "การเริ่มด้วย dialogue และ action ดึงดูดผู้อ่านได้มากกว่าการอธิบายแบบตรงๆ",
      },
      {
        type: "quiz",
        question: "คำเชื่อมลำดับเหตุการณ์ในการเล่าเรื่อง ข้อใดไม่ใช่ Sequence Word?",
        choices: ["First", "Then", "However", "Finally"],
        correct: 2,
        explanation: "'However' ใช้แสดงความตรงข้าม ส่วน First, Then, Finally ใช้เรียงลำดับเหตุการณ์",
      },
      {
        type: "fill",
        question: "การเขียนเรื่องเล่าควรใช้ ___ Tense เป็นหลัก",
        answer: "Past",
        hint: "อดีตกาล = P___ Tense",
      },
    ],
  },
];

export function getCourse(id: string): Course | undefined {
  return COURSES.find((c) => c.id === id);
}

export function getLessonsForCourse(courseId: string): Lesson[] {
  return LESSONS.filter((l) => l.courseId === courseId).sort((a, b) => a.order - b.order);
}

export function getLesson(id: string): Lesson | undefined {
  return LESSONS.find((l) => l.id === id);
}
