import type { Lesson } from "@/lib/data";

// Unreleased "ชุดที่ 2" lesson content — must never be imported from a
// "use client" file. Only serve it through a session-verified admin API route.
if (typeof window !== "undefined") {
  throw new Error("lib/lesson-data/set2-lessons must only be imported on the server");
}

export const SET2_LESSONS: Lesson[] = [
  // ===== ก.พ. ชุดที่ 2 — ความรู้ทั่วไป =====
  {
    id: "kpg2-1",
    courseId: "kp-general-2",
    title: "อนุกรม (Number Series)",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "อนุกรมคืออะไร?",
        content: "อนุกรม คือชุดตัวเลขที่มีความสัมพันธ์กันตามกฎบางอย่าง โจทย์จะให้หาตัวถัดไปหรือตัวที่หายไป\n\n► ประเภทอนุกรมที่ออกสอบบ่อย\n• อนุกรมบวก/ลบ: 2, 5, 8, 11, __ (+3 ทุกครั้ง)\n• อนุกรมคูณ/หาร: 3, 6, 12, 24, __ (×2 ทุกครั้ง)\n• อนุกรมผสม: 1, 2, 4, 7, 11, __ (+1, +2, +3, +4...)\n• อนุกรมยกกำลัง: 1, 4, 9, 16, 25, __ (1², 2², 3²...)\n• อนุกรมสลับ: 2, 5, 3, 6, 4, 7, __ (สองลำดับสลับกัน)\n\n→ เทคนิค: หาผลต่างระหว่างตัวเลขติดกัน แล้วดูว่าผลต่างมีรูปแบบอะไร",
      },
      {
        type: "quiz",
        question: "2, 5, 10, 17, 26, ___\nตัวถัดไปคือ?",
        choices: ["35", "36", "38", "37"],
        correct: 3,
        explanation: "ผลต่าง: +3, +5, +7, +9, +11 (เพิ่มทีละ 2) → 26 + 11 = 37",
      },
      {
        type: "quiz",
        question: "3, 6, 12, 24, 48, ___\nตัวถัดไปคือ?",
        choices: ["96", "72", "84", "96"],
        correct: 0,
        explanation: "×2 ทุกครั้ง: 48 × 2 = 96",
      },
      {
        type: "quiz",
        question: "1, 1, 2, 3, 5, 8, 13, ___\nตัวถัดไปคือ? (อนุกรม Fibonacci)",
        choices: ["18", "21", "19", "20"],
        correct: 1,
        explanation: "แต่ละตัว = ผลบวกสองตัวก่อนหน้า: 8 + 13 = 21",
      },
      {
        type: "quiz",
        question: "2, 6, 3, 9, 4, 12, 5, ___\nตัวถัดไปคือ? (อนุกรมสลับ)",
        choices: ["13", "14", "15", "16"],
        correct: 2,
        explanation: "ลำดับคี่: 2, 3, 4, 5 (+1) / ลำดับคู่: 6, 9, 12, __ (+3) → 12+3 = 15",
      },
      {
        type: "fill",
        question: "100, 95, 85, 70, 50, ___\nตัวถัดไปคือ ___",
        answer: "25",
        hint: "ผลต่าง: -5, -10, -15, -20, -25 (ผลต่างเพิ่มขึ้นทีละ 5)",
      },
    ],
  },
  {
    id: "kpg2-analogy",
    courseId: "kp-general-2",
    title: "อุปมาอุปไมย (Analogy)",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "อุปมาอุปไมยคืออะไร?",
        content: "อุปมาอุปไมย คือ การหา 'ความสัมพันธ์' ระหว่างคำคู่แรกที่โจทย์ให้มา แล้วนำไปเทียบกับคำคู่ตัวเลือก เพื่อหาคู่ที่มีความสัมพันธ์แบบเดียวกัน\n\n► รูปแบบความสัมพันธ์ที่พบบ่อย\n• ส่วนย่อย-ส่วนรวม เช่น ใบไม้ : ต้นไม้\n• เครื่องมือ-ผู้ใช้ เช่น ปากกา : นักเขียน\n• สาเหตุ-ผล เช่น ไฟ : ความร้อน\n• คำตรงข้าม เช่น สูง : เตี้ย\n• วัตถุดิบ-ผลิตภัณฑ์ เช่น แป้ง : ขนมปัง\n\n→ เทคนิค: แต่งประโยคเชื่อมคำคู่แรกให้ชัดเจนก่อน แล้วลองแทนคำคู่ตัวเลือกในประโยคเดียวกัน คู่ไหนเข้าประโยคได้พอดี คือคำตอบ",
      },
      {
        type: "quiz",
        question: "ปลา : น้ำ มีความสัมพันธ์แบบเดียวกับข้อใด?",
        choices: ["นก : ท้องฟ้า", "หมา : กระดูก", "แมว : หนู", "วัว : หญ้า"],
        correct: 0,
        explanation: "'ปลาอาศัยอยู่ในน้ำ' เหมือนกับ 'นกอาศัย/บินอยู่บนท้องฟ้า' — ความสัมพันธ์แบบสัตว์กับถิ่นที่อยู่",
      },
      {
        type: "quiz",
        question: "ครู : โรงเรียน มีความสัมพันธ์แบบเดียวกับข้อใด?",
        choices: ["หมอ : โรงพยาบาล", "รถ : ถนน", "นักเรียน : หนังสือ", "อาหาร : ครัว"],
        correct: 0,
        explanation: "'ครูทำงานที่โรงเรียน' เหมือนกับ 'หมอทำงานที่โรงพยาบาล' — ความสัมพันธ์แบบอาชีพกับสถานที่ทำงาน",
      },
      {
        type: "quiz",
        question: "องุ่น : ไวน์ มีความสัมพันธ์แบบเดียวกับข้อใด?",
        choices: ["นม : เนย", "น้ำ : แก้ว", "ข้าว : จาน", "ไข่ : ไก่"],
        correct: 0,
        explanation: "'องุ่นนำไปแปรรูปเป็นไวน์' เหมือนกับ 'นมนำไปแปรรูปเป็นเนย' — ความสัมพันธ์แบบวัตถุดิบกับผลิตภัณฑ์",
      },
      {
        type: "fill",
        question: "สูง : เตี้ย เหมือนกับ กว้าง : ___ (คำตรงข้ามของ 'กว้าง')",
        answer: "แคบ",
        hint: "ตรงข้ามกับ 'กว้าง' ใช้บรรยายพื้นที่หรือถนน",
      },
    ],
  },
  {
    id: "kpg2-2",
    courseId: "kp-general-2",
    title: "เงื่อนไขสัญลักษณ์",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "เงื่อนไขสัญลักษณ์คืออะไร?",
        content: "โจทย์กำหนดให้สัญลักษณ์แทนค่าตัวเลขหรือการดำเนินการ แล้วให้คำนวณตามกฎที่กำหนด\n\n► ตัวอย่างรูปแบบ\n• a ★ b = a² + b → 3 ★ 4 = 9 + 4 = 13\n• a ◆ b = (a + b) × 2 → 5 ◆ 3 = 8 × 2 = 16\n\n▸ วิธีทำ\n1. อ่านนิยามสัญลักษณ์ให้เข้าใจก่อน\n2. แทนค่าตัวเลขลงในสูตร\n3. คำนวณตามลำดับจากในวงเล็บออกมา\n4. ตรวจสอบอีกครั้งก่อนตอบ\n\n[!] ระวัง: อย่าสับสนสัญลักษณ์ที่กำหนดกับเครื่องหมายทางคณิตศาสตร์ทั่วไป",
      },
      {
        type: "quiz",
        question: "กำหนดให้ a ★ b = 2a − b\nถ้า 5 ★ 3 = ?\nคำตอบคือ?",
        choices: ["4", "8", "13", "7"],
        correct: 3,
        explanation: "5 ★ 3 = 2(5) − 3 = 10 − 3 = 7",
      },
      {
        type: "quiz",
        question: "กำหนดให้ a ◆ b = a² − b²\nถ้า 4 ◆ 3 = ?\nคำตอบคือ?",
        choices: ["7", "1", "5", "9"],
        correct: 0,
        explanation: "4 ◆ 3 = 4² − 3² = 16 − 9 = 7",
      },
      {
        type: "quiz",
        question: "กำหนดให้ a ▲ b = (a + b) ÷ (a − b)\nถ้า 9 ▲ 3 = ?\nคำตอบคือ?",
        choices: ["3", "2", "4", "6"],
        correct: 1,
        explanation: "9 ▲ 3 = (9 + 3) ÷ (9 − 3) = 12 ÷ 6 = 2",
      },
      {
        type: "quiz",
        question: "กำหนดให้ a ● b = 3a + 2b\nถ้า x ● 4 = 23 แล้ว x = ?\nคำตอบคือ?",
        choices: ["3", "4", "5", "6"],
        correct: 2,
        explanation: "3x + 2(4) = 23 → 3x + 8 = 23 → 3x = 15 → x = 5",
      },
      {
        type: "fill",
        question: "กำหนดให้ a □ b = a × b − (a + b)\nถ้า 6 □ 4 = ___",
        answer: "14",
        hint: "6 × 4 − (6 + 4) = 24 − 10 = ?",
      },
    ],
  },
  {
    id: "kpg2-3",
    courseId: "kp-general-2",
    title: "เงื่อนไขภาษา",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "เงื่อนไขภาษาคืออะไร?",
        content: "โจทย์กำหนดข้อเท็จจริง (เงื่อนไข) แล้วให้สรุปว่าข้อสรุปที่กำหนดถูกหรือผิด\n\n► ประเภทคำตอบ\n• \"สรุปได้\" = เงื่อนไขสนับสนุนข้อสรุปแน่นอน\n• \"สรุปไม่ได้\" = ข้อมูลไม่เพียงพอหรือขัดแย้ง\n\n▸ รูปแบบที่พบบ่อย\n• ถ้า A แล้ว B + A → สรุปว่า B ได้\n• ถ้า A แล้ว B + ไม่ B → สรุปว่า ไม่ A ได้\n• ถ้า A แล้ว B + ไม่ A → สรุปว่า ไม่ B ไม่ได้ (ผิดหลักตรรกะ)\n\n[!] อย่าใช้ความรู้เดิมในการตอบ — ตอบจากเงื่อนไขที่กำหนดเท่านั้น",
      },
      {
        type: "quiz",
        question: "เงื่อนไข: นักเรียนทุกคนที่สอบผ่านจะได้รับใบประกาศ / ด.ช.ก. สอบผ่าน\nข้อสรุป: ด.ช.ก. จะได้รับใบประกาศ",
        choices: ["สรุปได้", "สรุปไม่ได้"],
        correct: 0,
        explanation: "ถ้า [สอบผ่าน] → [ได้ใบประกาศ] + ด.ช.ก. สอบผ่าน → สรุปได้ว่า ด.ช.ก. ได้ใบประกาศ",
      },
      {
        type: "quiz",
        question: "เงื่อนไข: สัตว์ที่มีปีกทุกชนิดบินได้ / นกเพนกวินบินไม่ได้\nข้อสรุป: นกเพนกวินไม่มีปีก",
        choices: ["สรุปได้", "สรุปไม่ได้"],
        correct: 0,
        explanation: "ถ้า [มีปีก] → [บินได้] / บินไม่ได้ → ไม่มีปีก (กลับทาง Contrapositive) จึงสรุปได้ว่าเพนกวินไม่มีปีก",
      },
      {
        type: "quiz",
        question: "เงื่อนไข: พนักงานที่ขยันทุกคนได้รับโบนัส / นาย ข. ไม่ขยัน\nข้อสรุป: นาย ข. ไม่ได้รับโบนัส",
        choices: ["สรุปได้", "สรุปไม่ได้"],
        correct: 1,
        explanation: "เงื่อนไขบอกว่า 'ขยัน → ได้โบนัส' แต่ไม่ได้บอกว่า 'ไม่ขยัน → ไม่ได้โบนัส' เพราะอาจมีเหตุผลอื่นให้โบนัส",
      },
      {
        type: "quiz",
        question: "เงื่อนไข: ถ้าฝนตก ถนนจะเปียก / ถนนเปียก\nข้อสรุป: ฝนตก",
        choices: ["สรุปได้", "สรุปไม่ได้"],
        correct: 1,
        explanation: "ถนนเปียกอาจเกิดจากสาเหตุอื่น เช่น รดน้ำ ล้างถนน จึงสรุปไม่ได้ว่าฝนตก",
      },
      {
        type: "fill",
        question: "เงื่อนไข: ถ้าอุณหภูมิเกิน 35°C แอร์จะทำงาน / วันนี้แอร์ไม่ทำงาน\nข้อสรุปที่ถูกต้องคือ อุณหภูมิ ___ 35°C",
        answer: "ไม่เกิน",
        hint: "แอร์ไม่ทำงาน → อุณหภูมิ ___ 35°C (กลับทางเงื่อนไข)",
      },
    ],
  },
  {
    id: "kpg2-4",
    courseId: "kp-general-2",
    title: "คณิตศาสตร์ทั่วไป (ร้อยละ สมการ กราฟ)",
    order: 5,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "คณิตศาสตร์ทั่วไปที่ออกสอบ ก.พ.",
        content: "ข้อสอบ ก.พ. ด้านคณิตศาสตร์เน้น 3 เรื่องหลัก\n\n► 1. ร้อยละ (Percentage)\n• ร้อยละ = (ส่วน ÷ ทั้งหมด) × 100\n• เพิ่มขึ้น x% = คูณด้วย (1 + x/100)\n• ลดลง x% = คูณด้วย (1 − x/100)\n\n► 2. สมการและอสมการ\n• แก้สมการ: ย้ายตัวเลขข้ามเครื่องหมาย\n• สมการสองตัวแปร: แทนค่าหรือบวกลบสมการ\n\n► 3. ตารางและกราฟ\n• อ่านหน่วยให้ถูกต้อง (ล้าน/พัน)\n• คำนวณร้อยละการเปลี่ยนแปลง = (ใหม่−เดิม)/เดิม × 100",
      },
      {
        type: "quiz",
        question: "พนักงานเงินเดือน 25,000 บาท ได้รับการปรับขึ้น 12%\nเงินเดือนใหม่คือ?",
        choices: ["27,000", "27,500", "28,500", "28,000"],
        correct: 3,
        explanation: "25,000 × 1.12 = 28,000 บาท",
      },
      {
        type: "quiz",
        question: "สินค้าราคา 1,200 บาท ลดราคา 15% แล้วลดอีก 10%\nราคาสุดท้ายคือ?",
        choices: ["918", "840", "900", "960"],
        correct: 0,
        explanation: "1,200 × 0.85 = 1,020 → 1,020 × 0.90 = 918 บาท (ลดต่อเนื่องไม่ใช่ 25% รวม)",
      },
      {
        type: "quiz",
        question: "ยอดขาย 4 ไตรมาส: Q1=120, Q2=150, Q3=90, Q4=180 (ล้านบาท)\nไตรมาสใดมียอดต่ำกว่าค่าเฉลี่ย?",
        choices: ["Q2 และ Q4", "Q1 และ Q3", "Q3 เท่านั้น", "Q1 และ Q2"],
        correct: 1,
        explanation: "ค่าเฉลี่ย = (120+150+90+180)/4 = 135 → Q1(120) และ Q3(90) ต่ำกว่า 135",
      },
      {
        type: "fill",
        question: "2x + 3y = 16 และ x − y = 2\nค่าของ x = ___",
        answer: "4",
        hint: "จาก x = y + 2 แทนใน 2(y+2) + 3y = 16 → 5y = 12... หรือแก้อีกทาง",
      },
    ],
  },
  {
    id: "kpg2-5",
    courseId: "kp-general-2",
    title: "ภาษาไทย (เรียงประโยค เลือกใช้คำ อ่านจับใจความ)",
    order: 6,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "ภาษาไทยในข้อสอบ ก.พ.",
        content: "ข้อสอบวิชาภาษาไทยแบ่งเป็น 3 ส่วนหลัก\n\n► 1. การเรียงประโยค\nให้ประโยคที่ปะปนกัน แล้วเรียงใหม่ให้สละสลวยและมีเหตุผล\nเทคนิค: หาประโยคนำ (มักแนะนำหัวข้อ) และประโยคสรุป\n\n► 2. การเลือกใช้คำ\n• คำพ้องความหมาย: เลือกคำที่เหมาะกับบริบท\n• คำที่มักใช้ผิด: อาทิ ใช้/ทำ, ประกอบด้วย/ได้แก่\n• คำสันธาน: แต่/และ/หรือ/เพราะ\n\n► 3. การอ่านจับใจความ\n• ใจความสำคัญมักอยู่ต้นหรือท้ายย่อหน้า\n• ตอบจากบทความเท่านั้น ไม่ใช่ความรู้ทั่วไป",
      },
      {
        type: "quiz",
        question: "เรียงประโยคต่อไปนี้ให้ถูกต้อง\nก. ผลที่ได้คือชุมชนแข็งแกร่งและยั่งยืน\nข. การพัฒนาชุมชนต้องเริ่มจากการมีส่วนร่วมของคนในพื้นที่\nค. เมื่อทุกคนร่วมมือกัน ปัญหาต่างๆ ก็ถูกแก้ไขได้อย่างมีประสิทธิภาพ",
        choices: ["ก-ข-ค", "ค-ข-ก", "ข-ค-ก", "ข-ก-ค"],
        correct: 2,
        explanation: "ข (แนะนำหัวข้อ) → ค (ขยายความ) → ก (สรุปผล) เป็นลำดับที่สมเหตุสมผล",
      },
      {
        type: "quiz",
        question: "ข้อใดใช้คำได้ถูกต้อง?",
        choices: ["คณะกรรมการประกอบไปด้วยสมาชิก 10 คน", "คณะกรรมการประกอบมีสมาชิก 10 คน", "คณะกรรมการประกอบสมาชิก 10 คน", "คณะกรรมการประกอบด้วยสมาชิก 10 คน"],
        correct: 3,
        explanation: "'ประกอบด้วย' ถูกต้อง — 'ประกอบไปด้วย' เป็นภาษาปาก ไม่นิยมในภาษาเขียนทางการ",
      },
      {
        type: "quiz",
        question: "บทความ: 'การศึกษาไทยต้องปฏิรูปอย่างเร่งด่วน เพราะนักเรียนไทยมีผลสัมฤทธิ์ต่ำกว่ามาตรฐานสากล และครูขาดการพัฒนาทักษะอย่างต่อเนื่อง'\n\nใจความสำคัญของบทความนี้คืออะไร?",
        choices: ["ควรปฏิรูปการศึกษาไทยโดยเร็ว", "นักเรียนไทยไม่ตั้งใจเรียน", "ครูไทยขาดทักษะการสอน", "มาตรฐานสากลสูงเกินไป"],
        correct: 0,
        explanation: "ประโยคแรกคือใจความสำคัญ ส่วนที่เหลือเป็นเหตุผลสนับสนุน",
      },
      {
        type: "fill",
        question: "เติมคำสันธานที่เหมาะสม: เขาทำงานหนัก ___ ยังคงไม่ประสบความสำเร็จ",
        answer: "แต่",
        hint: "ประโยคสองส่วนขัดแย้งกัน ใช้คำสันธานแสดงการ___",
      },
    ],
  },
  // ===== ก.พ. ชุดที่ 2 — ภาษาอังกฤษ =====
  {
    id: "kpe2-1",
    courseId: "kp-english-2",
    title: "Conversation (บทสนทนา)",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "บทสนทนาภาษาอังกฤษในข้อสอบ ก.พ.",
        content: "ข้อสอบ ก.พ. มักให้บทสนทนา 4-8 บรรทัด แล้วถามว่าควรตอบว่าอะไร หรือบทสนทนาเกี่ยวกับอะไร\n\n► รูปแบบที่พบบ่อย\n• การทักทาย/อำลา: Nice to meet you / See you later\n• การขอความช่วยเหลือ: Could you...? / Would you mind...?\n• การตอบรับ/ปฏิเสธ: Sure, no problem / I'm afraid I can't\n• การถามข้อมูล: What time...? / How do I get to...?\n• การแสดงความเห็น: I think... / In my opinion...\n\n→ เทคนิค\n• อ่านบริบทรอบๆ ก่อนเลือกคำตอบ\n• สังเกตระดับความสุภาพ (formal vs informal)\n• คำตอบต้องตรงกับคำถามหรือสถานการณ์",
      },
      {
        type: "quiz",
        question: "A: 'Excuse me, could you tell me where the nearest post office is?'\nB: '___'\n\nWhich response is most appropriate?",
        choices: ["I don't have a post office.", "Sure, it's just two blocks down this street on your left.", "Yes, I like post offices.", "The post office is very busy today."],
        correct: 1,
        explanation: "The question asks for directions — the appropriate response gives clear directions politely.",
      },
      {
        type: "quiz",
        question: "A: 'Would you mind if I opened the window?'\nB: '___'\n\nWhich response shows agreement?",
        choices: ["Yes, I would mind.", "I don't know about windows.", "No, go ahead. It's a bit stuffy in here.", "The window is already open."],
        correct: 2,
        explanation: "'Would you mind if...?' — saying 'No' means you don't mind, i.e., you agree. 'Go ahead' confirms permission.",
      },
      {
        type: "quiz",
        question: "A: 'I'm sorry, but I won't be able to attend the meeting tomorrow.'\nB: 'That's alright. ___'\n\nWhich best completes B's response?",
        choices: ["You should come anyway.", "The meeting is very important.", "I don't like meetings either.", "We'll send you the minutes afterwards."],
        correct: 3,
        explanation: "A professional response to an absence apology is to reassure and offer a practical solution like sharing meeting minutes.",
      },
      {
        type: "fill",
        question: "A: 'How do you do?'\nB: '___, how do you do?' \n\nเติมคำตอบที่ถูกต้อง",
        answer: "How do you do",
        hint: "'How do you do' เป็นการทักทายทางการ — ตอบด้วยประโยคเดิม",
      },
    ],
  },
  {
    id: "kpe2-2",
    courseId: "kp-english-2",
    title: "Vocabulary in Context",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "คำศัพท์ระดับ ก.พ.",
        content: "คำศัพท์ที่ออกสอบ ก.พ. มักเป็นคำทางการและวิชาการ\n\n► หมวดคำที่ออกบ่อย\n• นโยบาย: policy, regulation, legislation, mandate\n• การบริหาร: implement, allocate, streamline, optimize\n• ผลลัพธ์: outcome, impact, consequence, implication\n• ทัศนคติ: advocate, oppose, endorse, criticize\n\n→ เทคนิคเดาคำศัพท์\n• ดูรากศัพท์ (prefix/suffix)\n• อ่านบริบทรอบข้างให้เข้าใจความหมายรวม\n• ตัดตัวเลือกที่ไม่สมเหตุสมผลออก",
      },
      {
        type: "quiz",
        question: "The minister said the new law would 'mandate' all factories to reduce emissions by 40%.\n\nThe word 'mandate' means?",
        choices: ["require officially", "suggest", "allow", "prevent"],
        correct: 0,
        explanation: "'Mandate' means to officially require or order — stronger than suggest, it's a formal requirement.",
      },
      {
        type: "quiz",
        question: "The budget will be 'allocated' to three departments equally.\n\n'Allocated' means?",
        choices: ["wasted", "distributed", "borrowed", "hidden"],
        correct: 1,
        explanation: "'Allocate' means to distribute or assign resources to specific purposes.",
      },
      {
        type: "quiz",
        question: "Which word best completes: 'The new system will ___ manual paperwork, saving 3 hours per day.'",
        choices: ["increase", "complicate", "eliminate", "duplicate"],
        correct: 2,
        explanation: "'Eliminate' = ยกเลิก/กำจัด — makes the most sense: saving time by removing paperwork.",
      },
      {
        type: "fill",
        question: "คำว่า 'implement' แปลว่า ___ (ดำเนินการ/นำไปปฏิบัติ ตอบเป็นภาษาไทย)",
        answer: "ดำเนินการ",
        hint: "implement a policy = ___ นโยบาย",
      },
    ],
  },
  {
    id: "kpe2-3",
    courseId: "kp-english-2",
    title: "Grammar: Passive Voice & Tenses",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "Passive Voice และ Tenses ขั้นสูง",
        content: "Passive Voice = กรรม + to be + V.3\n\n► รูปแบบหลัก\n• Present Simple Passive: is/am/are + V.3\n  'The report is written by the team.'\n• Past Simple Passive: was/were + V.3\n  'The law was passed in 2023.'\n• Future Passive: will be + V.3\n  'The project will be completed next month.'\n\n→ Tenses ที่ต้องรู้\n• Present Perfect: has/have + V.3 (เพิ่งทำเสร็จ)\n• Past Perfect: had + V.3 (เสร็จก่อนเหตุการณ์อื่น)\n• Conditional: If + Past Simple, would + V.1",
      },
      {
        type: "quiz",
        question: "The new bridge ___ by the construction company last year.",
        choices: ["built", "has built", "is built", "was built"],
        correct: 3,
        explanation: "'last year' = Past tense + Passive → was built (Past Simple Passive)",
      },
      {
        type: "quiz",
        question: "By the time the manager arrived, the report ___ already ___.",
        choices: ["had / been submitted", "is / submitted", "was / submitting", "has / submitted"],
        correct: 0,
        explanation: "'By the time' + past event = Past Perfect Passive: had been submitted",
      },
      {
        type: "quiz",
        question: "If the budget ___ approved, the project would start immediately.",
        choices: ["is", "were", "was", "will be"],
        correct: 1,
        explanation: "Second Conditional (สมมติที่ไม่น่าจะเป็นจริง): If + Past Simple (were) + would + V.1",
      },
      {
        type: "fill",
        question: "แปลงเป็น Passive: 'The committee reviews all applications.'\nคำตอบ: All applications ___ by the committee.",
        answer: "are reviewed",
        hint: "Present Simple Passive: is/are + V.3",
      },
    ],
  },
  {
    id: "kpe2-4",
    courseId: "kp-english-2",
    title: "Reading Comprehension (อ่านจับใจความ)",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "การอ่านจับใจความภาษาอังกฤษ",
        content: "ข้อสอบ ก.พ. มีบทความภาษาอังกฤษ 2-3 ย่อหน้า ถาม 3-5 ข้อ\n\n► ประเภทคำถาม\n• Main idea: What is the passage mainly about?\n• Detail: According to the passage, ...\n• Vocabulary in context: The word '...' means?\n• Inference: What can be inferred from the passage?\n• Author's purpose: Why did the author write this?\n\n→ เทคนิค Skim & Scan\n1. อ่านคำถามก่อน — รู้ว่าต้องหาอะไร\n2. Skim ดูประโยคแรก-ท้ายแต่ละย่อหน้า\n3. Scan หาข้อมูลที่ตอบคำถามได้\n\n[!] ตอบจากบทความเท่านั้น ห้ามใช้ความรู้ภายนอก",
      },
      {
        type: "quiz",
        question: "Remote work has transformed the modern workplace. Studies indicate that employees working from home are 13% more productive than those in offices. However, concerns about team cohesion and communication remain significant challenges for many organizations.\n\nWhat is the main idea of this passage?",
        choices: ["Remote work should be banned in all organizations.", "Office workers are less happy than remote workers.", "Remote work increases productivity but presents communication challenges.", "Technology has improved communication in the workplace."],
        correct: 2,
        explanation: "The passage presents both a benefit (13% more productive) and a challenge (team cohesion) of remote work.",
      },
      {
        type: "quiz",
        question: "The project was delayed due to unforeseen circumstances, including supply chain disruptions and a shortage of skilled labor. Despite these setbacks, the team remained resilient and adapted their timeline accordingly.\n\nThe word 'resilient' in this context means?",
        choices: ["discouraged", "slow", "well-funded", "able to recover quickly"],
        correct: 3,
        explanation: "'Resilient' = able to withstand or recover from difficulties — shown by the team adapting despite setbacks.",
      },
      {
        type: "quiz",
        question: "Thailand's digital economy is growing rapidly, with e-commerce transactions increasing by 35% annually. The government has invested heavily in digital infrastructure to support this growth and attract foreign investment.\n\nWhat can be inferred from the passage?",
        choices: ["The Thai government sees the digital economy as important for growth.", "Thailand's economy depends entirely on e-commerce.", "Foreign investment has decreased in Thailand.", "E-commerce will replace all traditional businesses."],
        correct: 0,
        explanation: "Government investment in digital infrastructure implies they view the digital economy as strategically important.",
      },
      {
        type: "fill",
        question: "A passage that presents a problem then proposes a solution has what type of structure?\nAnswer in English: ___ - Solution",
        answer: "Problem",
        hint: "โครงสร้างที่นำเสนอปัญหาก่อนแล้วเสนอวิธีแก้ = ___ - Solution structure",
      },
    ],
  },
  // ===== ก.พ. ชุดที่ 2 — กฎหมายข้าราชการ =====
  {
    id: "kpl2-1",
    courseId: "kp-law-2",
    title: "พ.ร.บ. ระเบียบบริหารราชการแผ่นดิน",
    order: 1,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "พ.ร.บ. ระเบียบบริหารราชการแผ่นดิน พ.ศ. 2534",
        content: "กำหนดโครงสร้างการบริหารราชการไทยออกเป็น 3 ระดับ\n\n► โครงสร้างการบริหารราชการ\n1. ราชการส่วนกลาง — กระทรวง ทบวง กรม\n   • นายกรัฐมนตรีบังคับบัญชาข้าราชการทุกกระทรวง\n   • รัฐมนตรีว่าการบังคับบัญชาข้าราชการในกระทรวงตน\n\n2. ราชการส่วนภูมิภาค — จังหวัด อำเภอ\n   • ผู้ว่าราชการจังหวัด = หัวหน้าราชการส่วนภูมิภาคในจังหวัด\n   • นายอำเภอ = หัวหน้าราชการส่วนภูมิภาคในอำเภอ\n\n3. ราชการส่วนท้องถิ่น — อบต. อบจ. เทศบาล กทม. พัทยา\n   • มีอิสระในการบริหาร ไม่ขึ้นกับส่วนกลางโดยตรง\n\n▸ จำง่าย: กลาง-ภูมิภาค-ท้องถิ่น",
      },
      {
        type: "quiz",
        question: "ตาม พ.ร.บ. ระเบียบบริหารราชการแผ่นดิน การบริหารราชการไทยแบ่งออกเป็นกี่ส่วน?",
        choices: ["2 ส่วน", "3 ส่วน", "4 ส่วน", "5 ส่วน"],
        correct: 1,
        explanation: "แบ่งเป็น 3 ส่วน: ราชการส่วนกลาง ส่วนภูมิภาค และส่วนท้องถิ่น",
      },
      {
        type: "quiz",
        question: "ใครคือหัวหน้าราชการส่วนภูมิภาคในระดับจังหวัด?",
        choices: ["นายกรัฐมนตรี", "ปลัดกระทรวงมหาดไทย", "ผู้ว่าราชการจังหวัด", "นายอำเภอ"],
        correct: 2,
        explanation: "ผู้ว่าราชการจังหวัดเป็นหัวหน้าราชการส่วนภูมิภาคในจังหวัด รับผิดชอบต่อรัฐมนตรีว่าการกระทรวงมหาดไทย",
      },
      {
        type: "quiz",
        question: "ข้อใดคือ 'ราชการส่วนท้องถิ่น' ตามกฎหมาย?",
        choices: ["กรมการปกครอง", "สำนักงานจังหวัด", "ที่ว่าการอำเภอ", "องค์การบริหารส่วนตำบล (อบต.)"],
        correct: 3,
        explanation: "อบต. อบจ. เทศบาล กทม. และเมืองพัทยา คือราชการส่วนท้องถิ่น — มีอำนาจปกครองตนเอง",
      },
      {
        type: "fill",
        question: "ราชการส่วนกลางระดับสูงสุดของแต่ละกระทรวงคือ ___",
        answer: "รัฐมนตรี",
        hint: "หัวหน้าฝ่ายการเมืองของกระทรวงคือ ___ว่าการกระทรวง",
      },
    ],
  },
  {
    id: "kpl2-2",
    courseId: "kp-law-2",
    title: "พ.ร.ฎ.บ้านเมืองที่ดี และ พ.ร.บ.วิธีปฏิบัติราชการทางปกครอง",
    order: 2,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "พ.ร.ฎ. ว่าด้วยหลักเกณฑ์และวิธีการบริหารกิจการบ้านเมืองที่ดี พ.ศ. 2546",
        content: "กำหนดหลักการบริหารราชการเพื่อประโยชน์สุขของประชาชน\n\n► หลักการบ้านเมืองที่ดี 7 ประการ\n1. เกิดประโยชน์สุขของประชาชน\n2. เกิดผลสัมฤทธิ์ต่อภารกิจรัฐ\n3. มีประสิทธิภาพและคุ้มค่า\n4. ไม่มีขั้นตอนเกินความจำเป็น\n5. ปรับปรุงภารกิจให้ทันสมัย\n6. ประชาชนพึงพอใจ\n7. ประเมินผลการปฏิบัติงาน\n\n► พ.ร.บ. วิธีปฏิบัติราชการทางปกครอง พ.ศ. 2539\n• คำสั่งทางปกครอง = การใช้อำนาจตามกฎหมายที่มีผลต่อสิทธิ/หน้าที่บุคคล\n• ต้องให้โอกาสโต้แย้งก่อนออกคำสั่งที่กระทบสิทธิ\n• ต้องแจ้งเหตุผลและสิทธิอุทธรณ์",
      },
      {
        type: "quiz",
        question: "ตาม พ.ร.ฎ. บ้านเมืองที่ดี การปฏิบัติราชการต้องไม่มีขั้นตอนเกินความจำเป็น เพราะเหตุใด?",
        choices: ["เพื่อให้ประชาชนได้รับบริการอย่างสะดวกรวดเร็ว", "เพื่อลดงานธุรการ", "เพื่อประหยัดงบประมาณ", "เพื่อลดจำนวนข้าราชการ"],
        correct: 0,
        explanation: "หลักการลดขั้นตอนเพื่อให้ประชาชนพึงพอใจและได้รับบริการที่มีประสิทธิภาพ ตรงตามเป้าหมายบ้านเมืองที่ดี",
      },
      {
        type: "quiz",
        question: "ตาม พ.ร.บ. วิธีปฏิบัติราชการทางปกครอง 'คำสั่งทางปกครอง' หมายถึงอะไร?",
        choices: ["คำสั่งที่ออกโดยนายกรัฐมนตรีเท่านั้น", "การใช้อำนาจทางกฎหมายที่กระทบสิทธิหรือหน้าที่ของบุคคล", "คำสั่งให้ข้าราชการโยกย้าย", "ระเบียบภายในของหน่วยงาน"],
        correct: 1,
        explanation: "คำสั่งทางปกครองคือการใช้อำนาจปกครองที่มีผลทางกฎหมายต่อสิทธิ/หน้าที่ของบุคคลใดบุคคลหนึ่ง",
      },
      {
        type: "quiz",
        question: "เจ้าหน้าที่จะออกคำสั่งทางปกครองที่กระทบสิทธิของบุคคลได้ ต้องดำเนินการอะไรก่อน?",
        choices: ["ได้รับอนุมัติจากคณะรัฐมนตรี", "ประกาศในราชกิจจานุเบกษา", "ให้โอกาสบุคคลนั้นโต้แย้งและแสดงพยานหลักฐาน", "รายงานต่อ ป.ป.ช."],
        correct: 2,
        explanation: "หลัก Audi Alteram Partem — ฟังความสองฝ่าย — ต้องให้โอกาสผู้ถูกกระทบโต้แย้งก่อนออกคำสั่ง",
      },
      {
        type: "fill",
        question: "พ.ร.ฎ. บ้านเมืองที่ดี กำหนดหลักการบริหารราชการทั้งหมด ___ ประการ",
        answer: "7",
        hint: "จำตัวเลข: ประโยชน์-ผลสัมฤทธิ์-ประสิทธิภาพ-ขั้นตอน-ปรับปรุง-พึงพอใจ-ประเมินผล",
      },
    ],
  },
  {
    id: "kpl2-3",
    courseId: "kp-law-2",
    title: "ประมวลจริยธรรมข้าราชการพลเรือน",
    order: 3,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "ประมวลจริยธรรมข้าราชการพลเรือน พ.ศ. 2564",
        content: "กำหนดมาตรฐานทางจริยธรรมสำหรับข้าราชการพลเรือน\n\n► หลักจริยธรรม 7 ประการ\n1. ยึดมั่นในสถาบันหลักของชาติ\n2. ซื่อสัตย์สุจริต มีจิตสาธารณะ\n3. มีความกล้าหาญทางจริยธรรม\n4. ยึดถือประโยชน์ส่วนรวมเหนือส่วนตน\n5. วางตนเป็นกลางทางการเมือง\n6. ปฏิบัติหน้าที่อย่างเป็นธรรม ไม่เลือกปฏิบัติ\n7. ดำรงตนเป็นแบบอย่างที่ดี\n\n▸ พฤติกรรมต้องห้าม\n• ไม่รับของขวัญเกิน 3,000 บาทต่อปีต่อคน\n• ไม่นำทรัพย์สินราชการไปใช้ส่วนตัว\n• ไม่เปิดเผยข้อมูลลับโดยไม่มีอำนาจ\n• ไม่ปฏิบัติงานที่ขัดกันแห่งผลประโยชน์",
      },
      {
        type: "quiz",
        question: "ประมวลจริยธรรมข้าราชการพลเรือน พ.ศ. 2564 กำหนดให้ข้าราชการต้องวางตัวอย่างไรในเรื่องการเมือง?",
        choices: ["สนับสนุนพรรคการเมืองที่ตนชื่นชอบ", "ออกมาแสดงจุดยืนทางการเมืองได้อย่างเสรี", "ห้ามไปลงคะแนนเสียงเลือกตั้ง", "วางตนเป็นกลางทางการเมือง"],
        correct: 3,
        explanation: "หลักจริยธรรมข้อ 5 กำหนดให้ข้าราชการวางตนเป็นกลางทางการเมือง ไม่ใช้ตำแหน่งหน้าที่เอื้อพรรคการเมือง",
      },
      {
        type: "quiz",
        question: "ข้าราชการรับของขวัญในโอกาสใดก็ตาม ได้ไม่เกินคนละเท่าใดต่อปี?",
        choices: ["3,000 บาท", "1,000 บาท", "5,000 บาท", "10,000 บาท"],
        correct: 0,
        explanation: "ประมวลจริยธรรมกำหนดไว้ไม่เกิน 3,000 บาทต่อคนต่อปี หากเกินต้องส่งคืนหรือนำส่งหน่วยงาน",
      },
      {
        type: "quiz",
        question: "ข้อใดแสดงถึง 'ความกล้าหาญทางจริยธรรม' ของข้าราชการ?",
        choices: ["ทำตามคำสั่งผู้บังคับบัญชาทุกกรณีโดยไม่ตั้งคำถาม", "แจ้งเบาะแสการทุจริตของผู้บังคับบัญชาต่อหน่วยงานที่รับผิดชอบ", "หลีกเลี่ยงการตัดสินใจเพื่อไม่ให้เกิดปัญหา", "รายงานผลงานเกินความเป็นจริง"],
        correct: 1,
        explanation: "ความกล้าหาญทางจริยธรรมคือการกล้าทำในสิ่งที่ถูกต้อง แม้จะต้องรายงานผู้บังคับบัญชาหรือเผชิญแรงกดดัน",
      },
      {
        type: "fill",
        question: "ประมวลจริยธรรมข้าราชการกำหนดให้ยึดถือประโยชน์ ___ เหนือประโยชน์ส่วนตน",
        answer: "ส่วนรวม",
        hint: "Public interest = ประโยชน์___",
      },
    ],
  },
  {
    id: "kpl2-4",
    courseId: "kp-law-2",
    title: "กฎหมายอาญา: ความผิดต่อตำแหน่งหน้าที่",
    order: 4,
    xpReward: 90,
    steps: [
      {
        type: "info",
        title: "ประมวลกฎหมายอาญา: ความผิดต่อตำแหน่งหน้าที่ราชการ",
        content: "มาตรา 147-166 ว่าด้วยความผิดที่เจ้าพนักงานกระทำต่อหน้าที่\n\n► ความผิดสำคัญ\n• มาตรา 147: เจ้าพนักงานยักยอกทรัพย์หลวง — จำคุก 5-20 ปี หรือตลอดชีวิต\n• มาตรา 148: เจ้าพนักงานใช้อำนาจข่มขืนใจ (Extortion) — จำคุก 5-20 ปี\n• มาตรา 149: เจ้าพนักงานรับสินบน — จำคุก 5-20 ปี หรือตลอดชีวิต\n• มาตรา 151: เจ้าพนักงานกระทำการโดยมิชอบเพื่อให้เกิดความเสียหาย\n• มาตรา 157: เจ้าพนักงานปฏิบัติหน้าที่โดยมิชอบ — จำคุกไม่เกิน 1 ปี หรือปรับ\n\n[!] \"เจ้าพนักงาน\" ตามกฎหมายอาญา = ผู้ดำรงตำแหน่งตามกฎหมาย มีอำนาจรัฐ\nรวมถึงข้าราชการ พนักงานรัฐวิสาหกิจ และเจ้าหน้าที่อื่นตามที่กฎหมายกำหนด",
      },
      {
        type: "quiz",
        question: "เจ้าพนักงานรับเงินจากเอกชนเพื่อแลกกับการออกใบอนุญาต ผิดมาตราใดของประมวลกฎหมายอาญา?",
        choices: ["มาตรา 147", "มาตรา 151", "มาตรา 149", "มาตรา 157"],
        correct: 2,
        explanation: "มาตรา 149 — เจ้าพนักงานรับสินบน (Bribery) เพื่อกระทำการหรืองดเว้นกระทำการอันมิชอบ โทษจำคุก 5-20 ปี หรือตลอดชีวิต",
      },
      {
        type: "quiz",
        question: "นายดำ เจ้าหน้าที่รัฐ นำเงินงบประมาณไปใช้ส่วนตัว กระทำความผิดตามมาตราใด?",
        choices: ["มาตรา 149 รับสินบน", "มาตรา 157 ปฏิบัติมิชอบ", "มาตรา 148 ข่มขืนใจ", "มาตรา 147 ยักยอกทรัพย์"],
        correct: 3,
        explanation: "มาตรา 147 — เจ้าพนักงานยักยอกทรัพย์ที่อยู่ในความครอบครองโดยตำแหน่งหน้าที่ โทษจำคุก 5-20 ปี",
      },
      {
        type: "quiz",
        question: "ข้าราชการปฏิเสธไม่ออกใบอนุญาตโดยไม่มีเหตุผลชอบด้วยกฎหมาย เพื่อให้ประชาชนเดือดร้อน ผิดมาตราใด?",
        choices: ["มาตรา 157", "มาตรา 147", "มาตรา 149", "มาตรา 151"],
        correct: 0,
        explanation: "มาตรา 157 — เจ้าพนักงานปฏิบัติหน้าที่โดยมิชอบหรือละเว้นการปฏิบัติหน้าที่ เพื่อให้เกิดความเสียหาย",
      },
      {
        type: "fill",
        question: "ความผิดของเจ้าพนักงานในประมวลกฎหมายอาญาอยู่ในมาตรา ___ ถึง ___",
        answer: "147-166",
        hint: "เริ่มมาตรา 147 สิ้นสุดมาตรา 166",
      },
    ],
  },
];
